### ISSUE TITLE
the current level of optimiation

### ISSUE THREAD

**Issue by tthsqe12** [syzygy1/Cfish#1]
Before I dive into your code, I would just like to know the extent to which you have optimized things. For example
have you used absolute indices in pieces lists?
have you used tail recursion to move SetCheckInfo to end of DoMove?
are domove, undomove, islegal, givescheck, ... fully optimized?

**Comment by syzygy1** [comment]
position.c includes a new do_move() implementation (#define NEW_DOMOVE) which (at least for now) does not use piecelists. For the moment I'm still using the old do_move().

I have improved the old do_move() a bit, but it does not use absolute indices. I think the main improvement is replacing [us][pt] with [piece].

I have changed the calculation of the material hash key to be additive. It seems to lead to more collisions and recalculations of material hashtable entries, but it might still be worth it. It also makes it possible to encode piece counts into the material hash key.

I don't know if it makes sense to calculate checkinfo at the end of each do_move(). At the moment I call calc_checkinfo() where SF invokes (or used to invoke) the constructor (except in generate_quiet_checks() where the checkinfo data is already available). If calculated pins etc. are re-used in evaluate.c, which SF seems to be doing now, it might make sense to calculate them always. I still have to investigate this.

I don't think I have changed is_legal() much if at all.

I re-implemented is_pseudo_legal(), mainly to deal with en passant and promotions more efficiently.

I've split gives_check() in an inline function (the test already done in search.cpp) and gives_check_special().

I've added a see_test(pos, v) which determines whether see(pos) >= v while stopping as soon as possible. The generated assembly looked pretty ugly, though. The old see() is still needed to score evasions.

MovePicker, Stack, CheckInfo and StateInfo are all in Stack. The generated moves are stored in a separate array (the moves for the child node directly following those for the parent node, ss->endMoves keeping track of where we are). The Thread struct was moved into Pos.

Originally I re-implemented the move generation routines (in movegen.c) but then I copied those from SF to movegen2.c, which I am using now (so node counts are the same). It seems to me SF's move generation can be improved upon.

I've been experimenting with forcing the compiler to generate bt/bts/btr/btc instructions, but gcc is a bit stubborn. It knows how to generate bt, but most of the time it doesn't do it. bts/btr/btc can be done with inline assembly, but that takes away some flexibility from the compiler. Maybe I will look into fixing gcc :-).

I've removed the beta (=alpha+1) argument from the NonPV search and qsearch. (But in theory and perhaps practice the compiler can do the same.)

I don't think anything is "fully" optimised yet. And I'm afraid compilers + CPUs are even less predictable than CPUs alone.

**Comment by JoselitoPimPamFuego** [comment]
Ok



Enviado desde mi smartphone Samsung Galaxy.


-------- Mensaje original --------
De: syzygy1 <notifications@github.com>
Fecha: 6/9/17 4:12 (GMT+07:00)
Para: syzygy1/Cfish <Cfish@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Asunto: Re: [syzygy1/Cfish] the current level of optimiation (#1)


Closed #1<https://github.com/syzygy1/Cfish/issues/1>.
