### ISSUE TITLE
Display the latest SF patch applied

### ISSUE THREAD

**Issue by jjoshua2** [syzygy1/Cfish#10]
Obviously you can't apply all of them since the program is slightly different. But for [0,5] patches like Oct 25 (today's) Endgame malus for having a king in a pawnless flank, this would almost certainly help Cfish too, and if those patches aren't kept up with Cfish will be passed by, even staying faster. It would help us to know for analysis which version of SF would be most comparable, and if it gets too far back we can try some analysis with both, and if eventually you stop updating, we will all know where it was left if anyone else wants to pick back up or compare.
ASMFish does something like this by putting a date in, although I haven't read that it means he has put in all patches by that date, I think it is at least close.

**Comment by syzygy1** [comment]
My intention is to keep Cfish in sync, but it will not always be immediate. (I am aware of a patch from a while ago that is still missing.)
