### ISSUE TITLE
Suggestion: def INLINE for MSVC

### ISSUE THREAD

**Issue by d3vv** [syzygy1/Cfish#102]
Please, add define like "INLINE __forceinline" into types.h for Visual Studio support (#ifdef _MSC_VER)

**Comment by d3vv** [comment]
#define INLINE __forceinline static

**Comment by d3vv** [comment]
Also add for MSVC:
#define __attribute__(x) /* blank - should simply ignore thanks to C preprocessor */

**Comment by d3vv** [comment]
Also need for ssize_t:

#if defined(_MSC_VER)
#include <BaseTsd.h>
typedef SSIZE_T ssize_t;
#endif

**Comment by d3vv** [comment]
into misc.h need exclude from MSVC:

#ifndef _MSC_VER
#include <sys/time.h>
#include <unistd.h>
#endif

**Comment by d3vv** [comment]
offtopic - IMHO this is strange practice: 

bitboard.c:#include "bmi2-fancy.c"
bitboard.h:#include "bmi2-fancy.h"

**Comment by d3vv** [comment]
into thread.h code:

```
enum {
  THREAD_SLEEP, THREAD_SEARCH, THREAD_TT_CLEAR, THREAD_EXIT, THREAD_RESUME
};
```

Need to rename THREAD_RESUME into something like THREAD_PROLONG cause
THREAD_RESUME it is constant of winnt.h (part of windows.h):

`#define THREAD_RESUME                     0x1000`

**Comment by d3vv** [comment]
into ucioption.c need to exclude strings.h from Visual Studio compilation:

#ifndef _MSC_VER
#include <strings.h>
#endif

**Comment by syzygy1** [comment]
I'm not very interested in supporting MSVC.

I will look into THREAD_RESUME.

**Comment by d3vv** [comment]
But Please?
I almost ported Cfish for MSVC and Intel C..
It will not bring impact to your code, just need to implement my suggestions

**Comment by d3vv** [comment]
for misc.h need:

```
#ifdef _MSC_VER
#define __builtin_bswap32 _byteswap_ulong
#define __builtin_bswap16 _byteswap_ushort
#define __builtin_bswap64 _byteswap_uint64
#endif
```

**Comment by d3vv** [comment]
for types.h a strange stub for compatibility:

#ifdef _MSC_VER
#define __builtin_unreachable() do { printf("Oops!\n"); abort(); } while(0)
#endif

**Comment by d3vv** [comment]
fix for https://github.com/syzygy1/Cfish/issues/102#issuecomment-520807879

```
#ifndef _MSC_VER
#include <strings.h>
#else
#define strcasecmp _stricmp
#endif
```

**Comment by d3vv** [comment]
for misc.c port of gettimeofday:
```
#ifdef _MSC_VER
int gettimeofday(struct timeval* tp, struct timezone* tzp)
{
	// Note: some broken versions only have 8 trailing zero's, the correct epoch has 9 trailing zero's
	// This magic number is the number of 100 nanosecond intervals since January 1, 1601 (UTC)
	// until 00:00:00 January 1, 1970 
	static const uint64_t EPOCH = ((uint64_t)116444736000000000ULL);

	SYSTEMTIME  system_time;
	FILETIME    file_time;
	uint64_t    time;

	GetSystemTime(&system_time);
	SystemTimeToFileTime(&system_time, &file_time);
	time = ((uint64_t)file_time.dwLowDateTime);
	time += ((uint64_t)file_time.dwHighDateTime) << 32;

	tp->tv_sec = (long)((time - EPOCH) / 10000000L);
	tp->tv_usec = (long)(system_time.wMilliseconds * 1000);
	return 0;
}
#endif
```

**Comment by mausalimi** [comment]
why not fork it?
