### ISSUE TITLE
atomic_bool and Intel C

### ISSUE THREAD

**Issue by d3vv** [syzygy1/Cfish#104]
Porting Cfish for Intel C (Parallel Studio XE 2019) I found out that those lines:

```
$ grep "Signals.stop = " *
search.c:  Signals.stop = 1;
search.c:      Signals.stop = 1;
search.c:          Signals.stop = 1;
search.c:        Signals.stop = 1;
search.c:  Signals.stopOnPonderhit = Signals.stop = 0;
uci.c:        Signals.stop = 1;
uci.c:        Signals.stop = 1;
uci.c:        Signals.stop = 1;
```

brings not warnings, but cruel errors:
`Error		a value of type "int" cannot be assigned to an entity of type "atomic_bool"`

Reading https://software.intel.com/en-us/articles/using-cc-atomics don't understand how to  resolve that in simple..
Any suggestions?

**Comment by d3vv** [comment]
Expressions like:

`Signals.stop = 1;`

must be replaced like:

`atomic_store(&Signals.stop, true);`

w/o "magic" constants and with standard as well..
(Many thanx to vit9696 from applelife.ru)

**Comment by d3vv** [comment]
Expressions like:

`if (Signals.stopOnPonderhit)`

need be replaced into:

`if (atomic_load(&Signals.stopOnPonderhit))`

otherwise we have error into some compilers:

`expression must have arithmetic or pointer type`

**Comment by syzygy1** [comment]
Assignment (=) to an atomic _Bool is allowed by C11. See ISO/IEC 9899:201x, 6.5.16.1:

> One of the following shall hold:
> —  the left operand has atomic, qualified, or unqualified arithmetic type, and the right has arithmetic type;

Arithmetic types include integer types, and _Bool is an integer type (6.2.5, points 6, 7, 17, 18).

**Comment by d3vv** [comment]
And..? I Read file attached below:
[455861_ISO-IEC-9899-2018-4.pdf.zip](https://github.com/syzygy1/Cfish/files/3497811/455861_ISO-IEC-9899-2018-4.pdf.zip)

**Comment by d3vv** [comment]
```
#include <stdatomic. h> 
C atomic_load(const volatile A *obj ect) ; 
C atomic_load_explicit(const volatile A *obj ect, memory_order order) ;
```

**Comment by syzygy1** [comment]
So the Intel compiler does not accept legal C11.

**Comment by d3vv** [comment]
This is true, but my suggestion doesn't violating standard:

6.5.16.1 Simple assignment
6.5.16.2 Compound assignment
7.17.7.1 The atomic_store generic functions

**Comment by d3vv** [comment]
@syzygy1 , I successfully compile Cfish with Intel C. Please don't update repo and I send you patches in several days when MSVC versa will be ready.

**Comment by d3vv** [comment]
STC(10+0.1) with cutechess GUI:

```
Score of cfish vs cfish-intel: 16 - 22 - 62 [0.470]
Elo difference: -20.9 +/- 42.1, LOS: 16.5 %, DrawRatio: 62.0 %

100 of 100 games finished.
```

**Comment by syzygy1** [comment]
I'm unlikely to accept changes to support MSVC. I may change the atomic_bool assignments if that is the only thing to get it to compile with the Intel compiler (even though Intel should know better and make their compiler comply with C11).

You are of course free to maintain your own branch.

**Comment by d3vv** [comment]
For icc need to decide what is true - `atomic_store(&Signals.stop, true)` or `atomic_store(&Signals.stop, 1)`?

And if using Intel C into Windows, it integrated into Visual Studio and need some code which implemented for MSVC  :(

**Comment by syzygy1** [comment]
I have just successfully compiled Cfish with "icc version 19.1.1.219 (gcc version 10.1.1 compatibility)".

In the Makefile icpc has to be changed to icc. Otherwise no changes are needed.

I will therefore close this issue.
