### ISSUE TITLE
WINAPI: flockfile and funlockfile

### ISSUE THREAD

**Issue by d3vv** [syzygy1/Cfish#105]
Into misc.c we have:
`// The following two functions were taken from mingw_lock.c`

But this is implementation is very hardcoded, used critical sections, incompatible with modern winapi cause for example, modern placeholder's structures:
`struct "_iobuf" has no field "_flag"`

or we can't to use `(&__iob_func()[0])` and `(&__iob_func()[_IOB_ENTRIES-1])` cause:
`expression must be a pointer to a complete object type`

Let's do it simple, right and as well for `#ifdef _MSC_VER`:
Reading https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/lock-file?view=vs-2019

and do:

```
#define flockfile _lock_file
#define funlockfile _unlock_file
```

or:

```
void flockfile (FILE *stream)
{
    _flockfile(stream);
}

void funlockfile (FILE *stream)
{
    _funlockfile(stream);
}
```

Whatever you like..

**Comment by d3vv** [comment]
I did mistake above. Right code:

```
void flockfile(FILE* stream)
{
	_lock_file(stream);
}

void funlockfile(FILE* stream)
{
	_unlock_file(stream);
}
```

**Comment by syzygy1** [comment]
@d3vv 
Any idea why MinGW does not use _lock_file and _unlock_file?

**Comment by Chess13234** [comment]
@syzygy1 MSVCRT.DLL doesn't support it. Mingw wraps over it.

**Comment by d3vv** [comment]
@Chess13234 But:
![flock](https://user-images.githubusercontent.com/32866346/71839666-c1bbe680-30cc-11ea-89ea-cfa764e38230.png)

**Comment by Chess13234** [comment]
https://sourceforge.net/p/mingw/bugs/2304/ found this, the functions are loaded from MSVCR80.DLL

**Comment by d3vv** [comment]
@Chess13234 As for me mingw on strange way, cause:

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-lockfileex

**Comment by Chess13234** [comment]
"win-core" is the current system API, MSVCRxx is the C language API layer, which mingw uses because its much more stable.

**Comment by d3vv** [comment]
But kernel32.dll injected into any process by default even if it is not present into import section
Moreover mingw already used win-native calls via LoadLibrary and GetProcAddress

**Comment by syzygy1** [comment]
So it seems switching to _lock_file() and _unlock_file() would introduce problems that the current approach takes pains to avoid.

**Comment by d3vv** [comment]
@syzygy1 What kind of problems are you talking about?

**Comment by syzygy1** [comment]
@d3vv 
I don't want cfish.exe to depend on a dll that is not on every Windows XP machine and later.

**Comment by AlexB123** [comment]
> 
> 
> @d3vv
> I don't want cfish.exe to depend on a dll that is not on every Windows XP machine and later.

Thank you! Can we go back to the old Cfish which is working fabulously without dlls? Can't wait for update to Cfish 11!
