### ISSUE TITLE
search.c: define/undef true/false

### ISSUE THREAD

**Issue by d3vv** [syzygy1/Cfish#106]
Into search.c persist code below:

```
#define true 1
#define false 0

...
#include "qsearch.c"
...

#undef true
#undef false
```

Sure need to remove defines of true/false caused its used above code w/o any problem.
Sure need to remove undef-directives of true/false cause it stopping to use its  below for code.

**Comment by syzygy1** [comment]
It used to be necessary but not anymore. I will remove it.
