### ISSUE TITLE
Question about parameter NUMA

### ISSUE THREAD

**Issue by CoffeeOne** [syzygy1/Cfish#11]
Sorry to open another issue, it is only a question:
What are the possible values for the uci parameter NUMA? Is it only to turn off and on NUMA?

**Comment by syzygy1** [comment]
"off" to turn off.
"on" or "all" to turn on.

On Linux only:
"2" to use only node 2
"0-1" to use only nodes 0 and 1
"1,3" to use only nodes 1 and 3
etc.

**Comment by CoffeeOne** [comment]
Thank you.
