### ISSUE TITLE
To Author of Cfish: Why error in shift_bb(Left... modification

### ISSUE THREAD

**Issue by abdulbadii** [syzygy1/Cfish#110]
Why error in **shift_bb(Left**.. modification in **movegen.c**
as **shift_bb(Right**... of such works perfectly
here the working modded Cfish:
[Cfishsrc+Release.zip](https://github.com/syzygy1/Cfish/files/3666300/Cfishsrc%2BRelease.zip)

If just changing few letters from shift_bb(Left..  to **shiftLeft(Us,**  and the function 
**INLINE Bitboard shift_bb(int Direction, Bitboard b)** is completely removed it'll generate error:

...
Step 2/4. Running benchmark for pgo-build ...
./cfish bench 16 1 15 > /dev/null
/bin/sh: line 1:   592 Segmentation fault      ./cfish bench 16 1 15 > /dev/null
make: *** [Makefile:423: profile-build] Error 139

How do we figure out this way of failure? ...thanks before

**Comment by syzygy1** [comment]
I don't know why you would want to change shift_bb(Left, ...) into shiftLeft(...). The current approach is closest to SF's shift_bb<LEFT>(...). There is certainly no efficiency to gain here, since the compiler can easily optimise shift_bb(Left, ....).

**Comment by abdulbadii** [comment]
Fine, thanks informing me that.. Sorry bother
