### ISSUE TITLE
Is this not going to be updated anymore ?

### ISSUE THREAD

**Issue by wiseguy100** [syzygy1/Cfish#111]
Hi, It has not been updated for a few months. Is this not going to be updated anymore ?

**Comment by syzygy1** [comment]
It will be updated, perhaps in the coming weeks.

**Comment by wiseguy100** [comment]
Thank you very much. I am eagerly waiting for the updates.

**Comment by hero2017** [comment]
> Thank you very much. I am eagerly waiting for the updates.

We all are but it doesn't look like it's going to happen this year. Hopefully syzygy1 (or someone else who's capable) can find the time in January 2020.
