### ISSUE TITLE
Request..

### ISSUE THREAD

**Issue by AlexB123** [syzygy1/Cfish#112]
Hello mr.Ronald!
It would be nice if you would give at least some kind of answer. 
Many people are still wondering what happened with the author, and why engine is not updated (see issue #94)?
Will it be updated or not, a simple answer will be highly appreciated! 
Regards and many thanks for your work!

**Comment by MichaelB7** [comment]
Does anyone realize how rude people are  when they ask Ronald to update cfish.  That is not what open source sites like Github are about.  Github is about giving , not taking.  A very sad state of affairs.

**Comment by AlexB123** [comment]
> 
> 
> Does anyone realize how rude people are when they ask Ronald to update cfish. That is not what open source sites like Github are about. Github is about giving , not taking. A very sad state of affairs.

Hi Michael! 
I'm not sure who your comment is addressed to. I can only say that when someone is asking the author about his project (engine), if it will be updated or not, it mean that people is actually very interested on it, and they respect author's work. So there is no rudeness. :)

**Comment by MichaelB7** [comment]
I would be more respectful, obviously
If there are no updates for a period of time , he has something more important to attend to.

**Comment by wiseguy100** [comment]
> I would be more respectful, obviously
> If there are no updates for a period of time , he has something more important to attend to.

If there is something more important for him, he wouldn't check this thread.  Calm down & take a chill pill. Nothing wrong in asking if it is going to be updated.

**Comment by Chess13234** [comment]
He isn't paid to write code, its a hobby project. And since its open-source, nothing prevents you from forking and updating the code.

**Comment by AlexB123** [comment]
> 
> 
> I would be more respectful, obviously
> If there are no updates for a period of time , he has something more important to attend to.

Yes, of course. If he has something more important to attend to, that's perfectly understandable.
Just a quick reply to the "fans" of his work, would be very appreciated, that's all!
Without any rudeness to Ronald (or anyone else)!

**Comment by AlexB123** [comment]
> 
> 
> He isn't paid to write code, its a hobby project. And since its open-source, nothing prevents you from forking and updating the code.

Agree! The question is, who can update the code better than author? I can't for sure.. :(

**Comment by mausalimi** [comment]
https://github.com/syzygy1/Cfish/issues/111

**Comment by abdulbadii** [comment]
We will be sorry if only he's been sick and quite got serious illness

**Comment by mausalimi** [comment]
i guess cfish dead now.

**Comment by syzygy1** [comment]
No worries, I'm alive and well ;-)
Just busy with other things, but I will probably come back to this.

**Comment by mausalimi** [comment]
>> No worries, I'm alive and well ;-)
good to hear.  :)

>> Just busy with other things,
hehe, happens to most of us.

>> but I will probably come back to this.
ah well, that would be a lot of work i suppose.
