### ISSUE TITLE
I do apologize but I need help

### ISSUE THREAD

**Issue by abdulbadii** [syzygy1/Cfish#113]
As we see more and more coders enthusiastically work to improve
better chess engine in future so that I ask Cfish authors/you  huge favor to create a repo and put C++ Ethereal (of Ethereal in C by Andrew G) there.
https://github.com/abdulbadii/Ethereal_CPP/tree/master/src

along with your repos beside, in order that the c++ coders could colloborate to obtain this promising potentially strongest engine challenging SF.
I'm so sorry if this become vexation but I just don't know the correct way to improve and tune it...
I'm deleting the said repo URL as soon as it's granted and done so.

**Comment by MichaelB7** [comment]
Your social unawareness is amazing.
