### ISSUE TITLE
Android issue

### ISSUE THREAD

**Issue by AlexB123** [syzygy1/Cfish#117]
Hello mr.Ronald! I want to report a bug. Using last source code "Some cleanup.", during android compilations i'm getting the follow error. Can you take a look please? Thanks!
![bug](https://user-images.githubusercontent.com/19660133/87326082-f0fb5680-c53a-11ea-84ec-546e18d036cc.jpg)

**Comment by syzygy1** [comment]
Which compiler are you using? gcc-10.1 does not complain here for me.

Anyway, I have just split the line into two lines. Does that fix it?

**Comment by AlexB123** [comment]
> 
> 
> Which compiler are you using? gcc-10.1 does not complain here for me.
> 
> Anyway, I have just split the line into two lines. Does that fix it?

I use android's NDK (with clang 9.0.8) on Windows 64 bit. 
---------
From your last source, problem solved! Thank you very much!

**Comment by syzygy1** [comment]
Ok, good to know. I should compile with clang sometimes to see if there are any warnings. (At the moment there are none.)
