### ISSUE TITLE
Error in compiling 32bit with MSYS2

### ISSUE THREAD

**Issue by massimilianogoi** [syzygy1/Cfish#120]
make profile-build ARCH=x86-32 COMP=gcc

Config:
debug: 'no'
optimize: 'yes'
arch: 'i386'
bits: '32'
prefetch: 'yes'
popcnt: 'no'
sse: 'yes'
pext: 'no'

Flags:
CC: gcc
CFLAGS: -Wall -std=c11  -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto
LDFLAGS:  -lm -m32 -Wl,--no-as-needed -lpthread -Wall -std=c11  -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto

Testing config sanity. If this fails, try 'make help' ...

Step 1/4. Building instrumented executable ...
make ARCH=x86-32 COMP=gcc gcc-profile-make
make[1]: Entering directory '/home/Massimiliano Goi/Cfish-master/src'
make ARCH=x86-32 COMP=gcc \
EXTRACFLAGS='-fprofile-generate' \
EXTRALDFLAGS='-lgcov' \
all
make[2]: Entering directory '/home/Massimiliano Goi/Cfish-master/src'
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o benchmark.o benchmark.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o bitbase.o bitbase.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o bitboard.o bitboard.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o endgame.o endgame.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o evaluate.o evaluate.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o main.o main.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o material.o material.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o misc.o misc.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o movegen.o movegen.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o movepick.o movepick.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o pawns.o pawns.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o position.o position.c
position.c: In function ‘print_pos’:
position.c:120:3: warning: implicit declaration of function ‘flockfile’; did you mean ‘_flockfile’? [-Wimplicit-function-declaration]
  120 |   flockfile(stdout);
      |   ^~~~~~~~~
      |   _flockfile
position.c:148:3: warning: implicit declaration of function ‘funlockfile’; did you mean ‘_funlockfile’? [-Wimplicit-function-declaration]
  148 |   funlockfile(stdout);
      |   ^~~~~~~~~~~
      |   _funlockfile
position.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-pedantic-ms-format’
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o psqt.o psqt.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o search.o search.c
search.c: In function ‘mainthread_search’:
search.c:351:3: warning: implicit declaration of function ‘flockfile’; did you mean ‘_flockfile’? [-Wimplicit-function-declaration]
  351 |   flockfile(stdout);
      |   ^~~~~~~~~
      |   _flockfile
search.c:359:3: warning: implicit declaration of function ‘funlockfile’; did you mean ‘_funlockfile’? [-Wimplicit-function-declaration]
  359 |   funlockfile(stdout);
      |   ^~~~~~~~~~~
      |   _funlockfile
search.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-pedantic-ms-format’
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o tbprobe.o tbprobe.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o thread.o thread.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o timeman.o timeman.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o tt.o tt.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o uci.o uci.c
uci.c: In function ‘uci_loop’:
uci.c:319:7: warning: implicit declaration of function ‘flockfile’; did you mean ‘_flockfile’? [-Wimplicit-function-declaration]
  319 |       flockfile(stdout);
      |       ^~~~~~~~~
      |       _flockfile
uci.c:326:7: warning: implicit declaration of function ‘funlockfile’; did you mean ‘_funlockfile’? [-Wimplicit-function-declaration]
  326 |       funlockfile(stdout);
      |       ^~~~~~~~~~~
      |       _funlockfile
uci.c: At top level:
cc1: warning: unrecognized command line option ‘-Wno-pedantic-ms-format’
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o ucioption.o ucioption.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o numa.o numa.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o settings.o settings.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto   -c -o polybook.o polybook.c
gcc -o cfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o tbprobe.o thread.o timeman.o tt.o uci.o ucioption.o numa.o settings.o polybook.o -lgcov -lm -m32 -Wl,--no-as-needed -lpthread -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m32 -Wno-pedantic-ms-format -DNDEBUG -O3 -msse -flto
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcov.a when searching for -lgcov
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcov.a when searching for -lgcov
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcov.a when searching for -lgcov
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lgcov
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../libm.a when searching for -lm
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../libm.a when searching for -lm
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../libm.a when searching for -lm
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lm
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../libpthread.a when searching for -lpthread
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../libpthread.a when searching for -lpthread
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../libpthread.a when searching for -lpthread
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lpthread
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcov.a when searching for -lgcov
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcov.a when searching for -lgcov
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcov.a when searching for -lgcov
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lgcov
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcc_s.dll.a when searching for -lgcc_s
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcc_s.dll.a when searching for -lgcc_s
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lgcc_s
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcc.a when searching for -lgcc
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcc.a when searching for -lgcc
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcc.a when searching for -lgcc
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lgcc
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../libmsys-2.0.a when searching for -lmsys-2.0
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../libmsys-2.0.a when searching for -lmsys-2.0
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../libmsys-2.0.a when searching for -lmsys-2.0
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmsys-2.0
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -ladvapi32
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lshell32
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -luser32
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lkernel32
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcc_s.dll.a when searching for -lgcc_s
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcc_s.dll.a when searching for -lgcc_s
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lgcc_s
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcc.a when searching for -lgcc
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcc.a when searching for -lgcc
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-msys/9.3.0/libgcc.a when searching for -lgcc
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:524: cfish] Error 1
make[2]: Leaving directory '/home/Massimiliano Goi/Cfish-master/src'
make[1]: *** [Makefile:540: gcc-profile-make] Error 2
make[1]: Leaving directory '/home/Massimiliano Goi/Cfish-master/src'
make: *** [Makefile:451: profile-build] Error 2

**Comment by syzygy1** [comment]
I don't understand how -flto can be given as a flag here. I also don't understand how flockfile can be undefined. Did you make edits to the Makefile or other files?

I cannot test profile builds on windows. You could try COMP=mingw. Otherwise just do "make cfish".

**Comment by syzygy1** [comment]
It's really not clear to me on what kind of system you are trying to (cross?) compile.

**Comment by massimilianogoi** [comment]
> I don't understand how -flto can be given as a flag here. I also don't understand how flockfile can be undefined. Did you make edits to the Makefile or other files?
> 
> I cannot test profile builds on windows. You could try COMP=mingw. Otherwise just do "make cfish".

I just changed native = no and numa = no there, nothing else.

**Comment by syzygy1** [comment]
With that I don't see how -flto can end up between the compilation flags, so you must leaving out information.

You're not also telling me if "make cfish" works.

Closing.
