### ISSUE TITLE
Will there be a Cfish-NNUE ?

### ISSUE THREAD

**Issue by spasski** [syzygy1/Cfish#121]
The tests at discord sf-nnue looks amazing.

And team stockfish decided to make a fishtest for sf-nnue.

What is the next step?

Please be part of the future and make a Cfish-NNUE.

Thx for your attention.

**Comment by syzygy1** [comment]
I was actually just thinking about the same question :-).
I don't know yet, I haven't had a look at SF-NNUE so far.

**Comment by spasski** [comment]
Please look what happened at discord:

https://discord.com/channels/435943710472011776/718853716266188890

**Comment by syzygy1** [comment]
It makes no sense to work on this before SF-NNUE is part of the official Stockfish, which apparently will happen. Closing for now.
