### ISSUE TITLE
Cfish-NNUE

### ISSUE THREAD

**Issue by LouisZulli** [syzygy1/Cfish#122]
Not an issue, but a polite request.

I'd love to see a version of Cfish that uses NNUE, but which (unlike Stockfish) allows the user to make no use of the classical evaluation. In fact, Cfish with _only_ NNUE evaluation would be fine.

Stockfish has already become a chimera, as it develops according to the goal of maximizing self-play Elo at Fishtest time controls (a goal that doesn't interest me).

**Comment by syzygy1** [comment]
As long as it makes sense, Cfish will have the option Pure NNUE.
