### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by JavaMast** [syzygy1/Cfish#123]
Cfish_AVX2 stopped in CuteChess GUI

[Event "My Tournament"]
[Site "?"]
[Date "2020.08.17"]
[Round "1"]
[White "Cfish_x64_170820_N_ELTO_AVX2"]
[Black "Cfish_x64_030820_N_ELTO_popcnt"]
[Result "0-1"]
[ECO "B90"]
[Opening "Sicilian"]
[PlyCount "10"]
[Termination "abandoned"]
[TimeControl "1/move"]
[Variation "Najdorf"]

1. e4 {book} c5 {book} 2. Nf3 {book} d6 {book} 3. d4 {book} cxd4 {book}
4. Nxd4 {book} Nf6 {book} 5. Nc3 {book} a6 {book, White disconnects} 0-1

[Event "My Tournament"]
[Site "?"]
[Date "2020.08.17"]
[Round "1"]
[White "Cfish_x64_030820_N_ELTO_popcnt"]
[Black "Cfish_x64_170820_N_ELTO_AVX2"]
[Result "1-0"]
[ECO "B90"]
[Opening "Sicilian"]
[PlyCount "11"]
[Termination "abandoned"]
[TimeControl "1/move"]
[Variation "Najdorf, Byrne (English) attack"]

1. e4 {book} c5 {book} 2. Nf3 {book} d6 {book} 3. d4 {book} cxd4 {book}
4. Nxd4 {book} Nf6 {book} 5. Nc3 {book} a6 {book}
6. Be3 {+0.71/19 1.00s, Black disconnects} 1-0

===========================
Cfish_AVX2 does not work if **threads >1**
tried without GUI and in Aquarium - it started to "think" but then it stopped and closed.

==========================
This issue does not occur with modern build

make profile-build ARCH=x86-64-modern  lto=yes extra=yes native=no numa=yes  -j 8  COMP=mingw

=========================
Also AVX 2 build works fine in BuildTester

![Screenshot_907](https://user-images.githubusercontent.com/42765009/90379526-82527100-e083-11ea-8ad6-2484caf200ff.png)

**Comment by syzygy1** [comment]
Thanks. I've found the problem but I still have to fix it. A thread will crash depending on how it happens to align some data structure.

The BMI2/pext compile should be as fast as avx2 (and should crash as much). Maybe you compiled it with avx2=no?

**Comment by sf-x** [comment]
This was fixed in mainline by bumping C++ version, but there's nothing to bump to here. Maybe re-enable unaligned load hack?

**Comment by syzygy1** [comment]
I think this is a different problem. I am malloc()ing the structs that have the Accumulater in them without caring about alignment. Aligning the Accumulator within the struct doesn't help much if the memory allocated for the struct is not aligned.

The unaligned load hack would also help here (it is still there for older gcc versions) but it would needlessly cost efficiency.

**Comment by syzygy1** [comment]
The problem should be fixed now.

**Comment by syzygy1** [comment]
The avx2 version no longer crashes on my laptop. (My desktop is old...)

**Comment by JavaMast** [comment]
Can not build to test...



![Screenshot_919](https://user-images.githubusercontent.com/42765009/90398780-a1acc680-e0a2-11ea-990b-7dc4ebeadce7.png)


@echo off
for /f "tokens=2 delims==" %%a in ('wmic OS Get localdatetime /value') do set "dt=%%a"
set "YY=%dt:~2,2%" & set "YYYY=%dt:~0,4%" & set "MM=%dt:~4,2%" & set "DD=%dt:~6,2%"
set "datestamp=%DD%%MM%%YY%"

set PATH=C:\msys64\mingw64\bin;C:\msys\1.0.11\bin;%PATH%
cd "I:\MinGW\CFish\Test_44\Cfish-master_170820_1\Cfish-master\src"




make clean
make profile-build ARCH=x86-64-avx2  lto=yes extra=yes native=no numa=yes   -j 8  COMP=mingw
strip Cfish.exe
move Cfish.exe Cfish_NNUE_x64_%datestamp%_ELTO_AVX2_mingw_10.exe




make clean
pause

**Comment by JavaMast** [comment]
Config:
debug: 'no'
sanitize: 'no'
optimize: 'yes'
arch: 'x86_64'
bits: '64'
kernel: 'MINGW32_NT-6.2'
os: 'Windows_NT'
prefetch: 'yes'
popcnt: 'yes'
sse: 'yes'
ssse3: 'yes'
sse41: 'yes'
avx2: 'yes'
pext: 'no'
avx512: 'no'
vnni: 'no'
neon: 'no'

Flags:
CXX: g++
CXXFLAGS:
LDFLAGS:  -lm -m64 -Wall -std=c11  -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto -flto=jobserver

Testing config sanity. If this fails, try 'make help' ...


Step 1/4. Building instrumented executable ...
make ARCH=x86-64-avx2 COMP=mingw gcc-profile-make
make[1]: Entering directory `/i/MinGW/CFish/Test_44/Cfish-master_170820_1/Cfish-master/src'
make ARCH=x86-64-avx2 COMP=mingw \
        EXTRACFLAGS='-fprofile-generate' \
        EXTRALDFLAGS='-lgcov' \
        all
make[2]: Entering directory `/i/MinGW/CFish/Test_44/Cfish-master_170820_1/Cfish-master/src'
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o benchmark.o benchmark.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o bitbase.o bitbase.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o bitboard.o bitboard.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o endgame.o endgame.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o evaluate.o evaluate.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o main.o main.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o material.o material.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o misc.o misc.c
benchmark.c: In function 'benchmark':
benchmark.c:168:15: warning: implicit declaration of function 'aligned_alloc' [-Wimplicit-function-declaration]
  168 |   pos.stack = aligned_alloc(64, 217 * sizeof(*pos.stack));
      |               ^~~~~~~~~~~~~
benchmark.c:168:15: warning: incompatible implicit declaration of built-in function 'aligned_alloc'
benchmark.c:33:1: note: include '<stdlib.h>' or provide a declaration of 'aligned_alloc'
   32 | #include "uci.h"
  +++ |+#include <stdlib.h>
   33 |
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o movegen.o movegen.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o movepick.o movepick.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o pawns.o pawns.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o position.o position.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o psqt.o psqt.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o search.o search.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o tbprobe.o tbprobe.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o thread.o thread.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o timeman.o timeman.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o tt.o tt.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o uci.o uci.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o ucioption.o ucioption.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o numa.o numa.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o settings.o settings.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o polybook.o polybook.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto   -c -o nnue.o nnue.c
uci.c: In function 'uci_loop':
uci.c:245:15: warning: implicit declaration of function 'aligned_alloc' [-Wimplicit-function-declaration]
  245 |   pos.stack = aligned_alloc(64, 215 * sizeof(Stack));
      |               ^~~~~~~~~~~~~
uci.c:245:15: warning: incompatible implicit declaration of built-in function 'aligned_alloc'
uci.c:32:1: note: include '<stdlib.h>' or provide a declaration of 'aligned_alloc'
   31 | #include "uci.h"
  +++ |+#include <stdlib.h>
   32 |
gcc -o cfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o tbprobe.o thread.o timeman.o tt.o uci.o ucioption.o numa.o settings.o polybook.o nnue.o -lgcov -lm -m64 -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -fira-loop-pressure -fconserve-stack -fmodulo-sched -fmodulo-sched-allow-regmoves -fsched-pressure -flimit-function-alignment -fno-tree-pre -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_AVX2 -mavx2 -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -msse2 -DUSE_SSE2 -DNUMA -DNNUE -flto -flto=jobserver
make[3]: warning: jobserver unavailable: using -j1.  Add `+' to parent make rule.
make[3]: [C:\Users\Efimo\AppData\Local\Temp\cfish.exe.hf3wVB.ltrans1.ltrans.o] Error 1 (ignored)
make[3]: [C:\Users\Efimo\AppData\Local\Temp\cfish.exe.hf3wVB.ltrans3.ltrans.o] Error 1 (ignored)
make[3]: [C:\Users\Efimo\AppData\Local\Temp\cfish.exe.hf3wVB.ltrans2.ltrans.o] Error 1 (ignored)
make[3]: [C:\Users\Efimo\AppData\Local\Temp\cfish.exe.hf3wVB.ltrans0.ltrans.o] Error 1 (ignored)
c:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Efimo\AppData\Local\Temp\cfish.exe.hf3wVB.ltrans0.ltrans.o:<artificial>:(.text+0xce25): undefined reference to `aligned_alloc'
c:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\Efimo\AppData\Local\Temp\cfish.exe.hf3wVB.ltrans3.ltrans.o:<artificial>:(.text+0xb887): undefined reference to `aligned_alloc'
collect2.exe: error: ld returned 1 exit status
make[2]: *** [cfish] Error 1
make[2]: Leaving directory `/i/MinGW/CFish/Test_44/Cfish-master_170820_1/Cfish-master/src'
make[1]: *** [gcc-profile-make] Error 2
make[1]: Leaving directory `/i/MinGW/CFish/Test_44/Cfish-master_170820_1/Cfish-master/src'
make: *** [profile-build] Error 2
strip: 'Cfish.exe': No such file
Не удается найти указанный файл.
Для продолжения нажмите любую клавишу . . .

**Comment by syzygy1** [comment]
I just realised it myself. One moment.

**Comment by syzygy1** [comment]
You can try again (with latest commit).

**Comment by JavaMast** [comment]
Works fine!
Thank you!

**Comment by syzygy1** [comment]
You're welcome and thanks for testing!
