### ISSUE TITLE
Alternative SSE2 optimizations

### ISSUE THREAD

**Issue by sf-x** [syzygy1/Cfish#124]
SSE2 does not have int8 multiply, so needs unpacking to int16 on load. I did an alternate implementation of SSE2 vector code where int8s were unpacked on parameters load, not on every evaluation, and intermediate int8s were replaced with int16s too (https://github.com/sf-x/Stockfish/commits/offish_nnue_no_int8 ) and it was measured nearly 10% faster on SSE2-only hardware (see issue 2956 in official-stockfish ) but it was rejected as "too intrusive". Are you interested, or is it "too intrusive" for Cfish too?

**Comment by syzygy1** [comment]
I am interested!

**Comment by syzygy1** [comment]
So this improves the SSE2 but is not necessary when SSSE3 is available, right?

Could this approach work for MMX too?

**Comment by sf-x** [comment]
> So this improves the SSE2 but is not necessary when SSSE3 is available, right?

If you are talking about #125 , yes. For SSSE3 and higher this is harmful and should not be switched on.  By the way, `nnue_noint8` should be probably set to `yes` for suitable targets.
> Could this approach work for MMX too?

No reason why it wouldn't.

**Comment by syzygy1** [comment]
I don't think there is any need to keep the old SSE2 code, so I am throwing that out.

**Comment by JavaMast** [comment]
@syzygy1 
I just tested SSE2 with nnue_noint8=yes -- it almost same speed as SSSE3 build.
Also i notice that MMX build have wrong bench and it changes from run to run.

![Screenshot_941](https://user-images.githubusercontent.com/42765009/90557797-bfae2000-e1a3-11ea-9b72-f9daa1960136.png)
![Screenshot_942](https://user-images.githubusercontent.com/42765009/90557806-c472d400-e1a3-11ea-9b6d-162e426943f7.png)


=========
MMX build compiled with 
make profile-build ARCH=x86-64-mmx  lto=yes extra=yes native=no numa=yes  nnue_noint8=no   -j 11  COMP=mingw

**Comment by syzygy1** [comment]
x86-64-mmx does not actually use mmx, because x86-64 enables sse2.

To use mmx in a 64-bit compile, use "ARCH=general-64 mmx=yes".

**Comment by syzygy1** [comment]
Hmm what might be happening there is MMX being used where SSE2 code is missing. Although that shouldn't be the case with nnue_noint8=no.

With the latest commit this could be a problem though.

**Comment by JavaMast** [comment]
Same thing with MMX was before "WIP SSE2 code" commit

**Comment by syzygy1** [comment]
MMX is giving a bench of 4290577 for me, also when I compile for Windows with MinGW.

**Comment by JavaMast** [comment]
with "ARCH=general-64 mmx=yes" works fine.
Thank you!
