### ISSUE TITLE
What is the point of passing a single buffer to propagate()?

### ISSUE THREAD

**Issue by sf-x** [syzygy1/Cfish#129]
What is the point of passing a single buffer to `propagate()` and using it for intermediate results too, instead of using multiple smaller local buffers? Is it a speedup or needed for other reasons?

**Comment by syzygy1** [comment]
No point. This is just a remnant from the port of SF's code.

As a matter of fact, I have just rewritten this part.

**Comment by sf-x** [comment]
OK.
