### ISSUE TITLE
Possible overflow in clipping in `transform()`

### ISSUE THREAD

**Issue by sf-x** [syzygy1/Cfish#134]
New SSE2/MMX clamping code might possibly give incorrect result:
` out[i] = _mm_subs_epu16(_mm_adds_epi16(sum, k0x7f80), k0x7f80)`
if there's a component of  `sum` less than (int16_t)0x8080.
I understand that this is rare, and `transform()` does not guard against overflow anyway. Just checking if it's intentional.

**Comment by syzygy1** [comment]
Fun fact: _mm_max/min_epi16 is part of SSE2
