### ISSUE TITLE
Cfish.exe is auto quitting and infinity chess GUI is again and again trying to load it, but fails

### ISSUE THREAD

**Issue by absimaldata** [syzygy1/Cfish#135]
As mentioned in heading, I tried loading the process using Infinity Chess and also from my Custom Program Written in Java which hold System.In, Out and Err Streams of the process. After loading, process is automatically quitting itself withing 1 or 2 seconds.

And I have tried disabling LTO, NUMA etc, but nothing works.

I dont know how in Fritz GUI it works.

Can you please check?

**Comment by mtaktikos** [comment]
"Do you store a network file (nn-82215d0fd0df.nnue) in a same folder with Cfish?
Or set full path to file in GUI."

Had the same issue:
Stored a renamed Sergio net (nn-1010.nnue) in the same folder with Cfish, and wrote this net name as engine option EvalFile in the GUI. The engine crashed.
Then I renamed nn-1010.nnue to nn-82215d0fd0df.nnue. The engine started again and again, as described by absimaldata. Then I remembered, I had forgotten to change the GUI options to the new name of the EvalFile. After changing it to nn-82215d0fd0df.nnue, the engine works like a charm.
So to set the full path to file in the GUI is not enough, the file must be necessary named nn-82215d0fd0df.nnue, other names are not accepted. I guess something is broken with the setting of the option EvalFile

**Comment by syzygy1** [comment]
EvalFile seems to work fine for me as long as no typos are made.

**Comment by absimaldata** [comment]
Its working fine totally.
