### ISSUE TITLE
CFish compilation through Clang not happening

### ISSUE THREAD

**Issue by magicianofriga** [syzygy1/Cfish#136]
I understand an older issue was closed 3 days ago, but I am still getting some errors when trying to compile cfish through clang.
I am getting this error when doing the following:
C:\tools\msys64\mingw64\bin\ld: cannot find C:\tools\msys64\mingw64\lib\clang\10.0.1\lib\windows\libclang_rt.profile-x86_64.a: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Makefile:889: cfish] Error 1
make[2]: Leaving directory
make[1]: *** [Makefile:892: clang-profile-make] Error 2
make[1]: Leaving directory 
make: *** [Makefile:784: profile-build] Error 2
I have installed Clang already with the following command previously:
pacman -S mingw-w64-x86_64-clang

My make command was for best performance as listed in the makefile:
make pgo COMP=clang

Any way to resolve this?

**Comment by JavaMast** [comment]
@magicianofriga 
I also unable to make PGO with Clang, so i use:
make build COMP=clang

**Comment by magicianofriga** [comment]
Thanks JavaMast! My objective is to build the fastest version of CFish possible, so I was wondering what are the configurations and compilers to use. I think Clang is faster than GCC, but I request the makers and regular contributors of Cfish to help us resolve this.

**Comment by MichaelB7** [comment]
There is very little evidence that clang is makes a “faster” exe.   It may be slightly faster in compiling  exe.   But if you are able to build with either tool - that would be the exe to use - the difference in any possible Elo difference would be minimal.

**Comment by syzygy1** [comment]
Looks like a problem with your Clang installation. Not Cfish related.

**Comment by magicianofriga** [comment]
> Looks like a problem with your Clang installation. Not Cfish related.

I have installed Clang through Command line. Anything else I need to follow?

**Comment by syzygy1** [comment]
I don't know, this place is about Cfish development :)

I suggest you just use gcc if you want a profile build. Otherwise, Google is your friend.
