### ISSUE TITLE
Cfish does not release memory with TB using?

### ISSUE THREAD

**Issue by JavaMast** [syzygy1/Cfish#138]
I found strange behavior when start match in CuteChess GUI with 6 men TBs.
1 core 60+0.6 hash 64 MB.
Cfish is "eating" memory.
It does not release memory with ucinewgame?

![Screenshot_1028](https://user-images.githubusercontent.com/42765009/91656240-f814fe80-eabf-11ea-9aa8-8fcbe3870cc6.png)

![Screenshot_1030](https://user-images.githubusercontent.com/42765009/91656254-1e3a9e80-eac0-11ea-9c74-730a515cf8ba.png)

**Comment by JavaMast** [comment]
![Screenshot_1030](https://user-images.githubusercontent.com/42765009/91656429-52628f00-eac1-11ea-8469-2c171686feba.png)

**Comment by syzygy1** [comment]
Changing SyzygyPath and back releases it. I may add this to ucinewgame.

**Comment by syzygy1** [comment]
Added
