### ISSUE TITLE
Compile with new makefile produces errors

### ISSUE THREAD

**Issue by Denzwell** [syzygy1/Cfish#141]
mingw32-make.exe clean
mingw32-make.exe profile-build ARCH=x86-64-modern COMP=mingw
------------------------------------------------------ OUTPUT ---------------------------------------------
Config:
debug: 'no'
sanitize: 'no'
optimize: 'yes'
arch: ''
bits: '64'
kernel: 'MINGW32_NT-6.2'
os: 'Windows_NT'
prefetch: 'yes'
popcnt: 'yes'
pext: 'no'
sse: 'yes'
mmx: 'no'
sse2: 'yes'
ssse3: 'yes'
sse41: 'yes'
avx2: 'no'
avx512: 'no'
vnni: 'no'
neon: 'no'

Flags:
CC: gcc
CFLAGS: -Wall -std=c11  -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse -DUSE_POPCNT -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -DNUMA -DNNUE
LDFLAGS:  -lm -m64

Testing config sanity. If this fails, try 'make help' ...

mingw32-make: *** [Makefile:870: config-sanity] Error 1

**Comment by Denzwell** [comment]
I have to take an old makefile to compile

**Comment by Denzwell** [comment]
ok i see my error.
i need to change command line to compile

mingw32-make.exe profile-build ARCH=auto COMP=mingw
or
mingw32-make.exe profile-build COMP=mingw

**Comment by syzygy1** [comment]
ARCH=x86-64-modern should work too.

I suppose the Makefile can't find the "sed" program on your system. If you remove line 301 ("arch =") from the Makefile it will probably work again.

**Comment by Denzwell** [comment]
Ok thank you Syzygy, everything is fine now. I am using hybrid mode on playchess and it works great.

**Comment by syzygy1** [comment]
Great that it works. I'll modify the Makefile so it doesn't break so easily.
