### ISSUE TITLE
About simpler AVX2 code

### ISSUE THREAD

**Issue by sf-x** [syzygy1/Cfish#144]
I simplified the AVX2 code (transposed case), hoping for speedup, but instead got 1% speed loss (on default bench). Here it is (includes some debug code): https://github.com/sf-x/Cfish/tree/simpler_avx2 . Needs preprocessor define `NEW_CODE` to enable.
@JavaMast reports 3.5% speedup on pure NNUE here:
https://github.com/syzygy1/Cfish/commit/6dbb40863a758d3beba8e94d552b891b5f6f537e
Maybe there will be more reports.
I made a version with debug code removed and new code unconditionally enabled and pushed it to my repo, branch `pr_simpler_avx2` (https://github.com/sf-x/Cfish/tree/pr_simpler_avx2 )
What to do?

**Comment by JavaMast** [comment]
@sf-x 
this version slower than previous

![Screenshot_1065](https://user-images.githubusercontent.com/42765009/91888411-f05a8300-ec94-11ea-932b-b8093f801f1f.png)

**Comment by JavaMast** [comment]
@sf-x 
probably it's just noise
![Screenshot_1066](https://user-images.githubusercontent.com/42765009/91889396-70cdb380-ec96-11ea-8123-b904a7a1bbb4.png)

**Comment by sf-x** [comment]
Hm, and seems we have an explanation: compiler sensitivity to irrelevant stuff.  There is literally no functional difference.
@JavaMast Did you compile with identical settings, aside from `-DNEW_CODE`? And with default PGO bench?

**Comment by JavaMast** [comment]
@sf-x 
yes, all identical except -DNEW_CODE
==============
i added new testrun - it was just a noice

**Comment by JavaMast** [comment]
@sf-x 
also new tests shows even more speedup:

Build Tester: 1.4.7.0
Windows 10 (Version 10.0, Build 0, 64-bit Edition)
AMD Ryzen 9 3900X 12-Core Processor            
SafeMode: No 
Running In VM: No 
HyperThreading Enabled: Yes
CPU Warmup: No 
Command Line: bench 16 1 13  default depth pure
Tests per Build: 20
ANOVA: n/a

                Engine# (NPS)                     Speedup     Sp     Conf. 99.5%  S.S.
1  (1 960 482,0   ) ---> 2  (1 857 357,2   ) --->  5,552%  8 050,5      Yes       No 


Build Tester: 1.4.7.0
Windows 10 (Version 10.0, Build 0, 64-bit Edition)
AMD Ryzen 9 3900X 12-Core Processor            
SafeMode: No 
Running In VM: No 
HyperThreading Enabled: Yes
CPU Warmup: No 
Command Line: bench 16 1 13  default depth pure
Tests per Build: 20
ANOVA: n/a

                Engine# (NPS)                     Speedup     Sp     Conf. 99.5%  S.S.
2  (1 961 590,4   ) ---> 1  (1 857 191,9   ) --->  5,621%  10 308,0     Yes       No

**Comment by JavaMast** [comment]
> ==And does your tool interleave the runs of the engines under test?==

Yes

**Comment by JavaMast** [comment]
Small speedup on Intel Core i5-7600K
![01-09-2020-213553](https://user-images.githubusercontent.com/42765009/91893931-8eeae200-ec9d-11ea-8266-9de741bf1e73.jpg)
![01-09-2020-213847](https://user-images.githubusercontent.com/42765009/91893948-94482c80-ec9d-11ea-93e8-baa30d59c717.jpg)
![01-09-2020-214106](https://user-images.githubusercontent.com/42765009/91893996-a629cf80-ec9d-11ea-911d-41d4959e1f20.jpg)

**Comment by JavaMast** [comment]
Confirmed speedup on Ryzen 1800X

![image](https://user-images.githubusercontent.com/42765009/91900799-e68e4b00-eca7-11ea-8cbf-c38e718e58d9.jpg)

**Comment by sf-x** [comment]
For completeness, building both with `-march=native` makes the patched version run at the same speed as original for me (and slightly faster overall, but within the confidence interval), to +-0.5%; specifying `-march=foo` is something to consider, it would simplify the Makefile

**Comment by syzygy1** [comment]
Current code:
`	vmovd	%r9d, %xmm9`
`	vpunpcklbw	%ymm11, %ymm13, %ymm1`
`	vpbroadcastw	%xmm9, %ymm12`
`	vpunpckhbw	%ymm11, %ymm13, %ymm14`
`	vpmaddubsw	%ymm1, %ymm12, %ymm2`
`	vpmaddubsw	%ymm14, %ymm12, %ymm15`
`	vpermq	$14, %ymm2, %ymm10`
`	vpermq	$14, %ymm15, %ymm1`
`	vpmovsxwd	%xmm2, %ymm8`
`	vpmovsxwd	%xmm10, %ymm3`
`	vpmovsxwd	%xmm15, %ymm11`
`	vpmovsxwd	%xmm1, %ymm9`
`	vpaddd	%ymm7, %ymm8, %ymm7`
`	vpaddd	%ymm6, %ymm3, %ymm6`
`	vpaddd	%ymm4, %ymm11, %ymm4`
`	vpaddd	%ymm5, %ymm9, %ymm5`

Simpler code:
`	vmovd	%ecx, %xmm12`
`	vpunpcklbw	%ymm11, %ymm15, %ymm1`
`	vpunpckhbw	%ymm11, %ymm15, %ymm8`
`	vpbroadcastw	%xmm12, %ymm2`
`	vpmaddubsw	%ymm1, %ymm2, %ymm0`
`	vpmaddubsw	%ymm8, %ymm2, %ymm13`
`	vpsraw	$15, %ymm0, %ymm10`
`	vpsraw	$15, %ymm13, %ymm14`
`	vpunpcklwd	%ymm10, %ymm0, %ymm9`
`	vpunpckhwd	%ymm10, %ymm0, %ymm4`
`	vpunpcklwd	%ymm14, %ymm13, %ymm15`
`	vpunpckhwd	%ymm14, %ymm13, %ymm11`
`	vpaddd	%ymm9, %ymm5, %ymm5`
`	vpaddd	%ymm4, %ymm3, %ymm3`
`	vpaddd	%ymm15, %ymm6, %ymm6`
`	vpaddd	%ymm11, %ymm7, %ymm7`

So same number of instructions. However, the "simpler" code seems to have cheaper instructions. So I guess it is safe to switch.

I noticed that, in both cases, the memcpy() is not optimized away. I was quite sure the memcpy() did get optimized away in the SSE2 case (I have not re-checked this).

I guess in the longer term the NNUE evaluation code is a good candidate for implementation in assembly.

**Comment by syzygy1** [comment]
Committed
