### ISSUE TITLE
AVX512 code is currently partially unused

### ISSUE THREAD

**Issue by sf-x** [syzygy1/Cfish#145]
Since `TRANSPOSE` is enabled for all x86(-64) with SSE2, and there's no AVX512 code for the transposed case, AVX512 is used for the accumulator updates and the scalar product code only. While I suspect this is optimal, I'm not sure that's intentional.

**Comment by syzygy1** [comment]
Ah I see. No, this was not intentional but i guess it probably does not hurt.

I have anway to look carefully at all the NNUE code when I have time. But first I need to squash a bug that has somehow crept into the classical evaluation function.
