### ISSUE TITLE
Port the Cluster branch of SF as well for HPC applications?

### ISSUE THREAD

**Issue by absimaldata** [syzygy1/Cfish#148]
Hi,

I wanted a cluster branch of stockfish official repository to be ported to C also.

Can you please look into that?

**Comment by syzygy1** [comment]
Very unlikely that I will do that, but I can take a look some time.

**Comment by absimaldata** [comment]
Yes, Will be great, because the Cfish will be more Scalable on multiple nodes of cluster, which I have (5 nodes  of 96 Threads each).
So will benefit from the huge NPS gain over SF

**Comment by absimaldata** [comment]
@syzygy1 Did you take a look on cluster.cpp and cluster.h and its code in other places? Please check. It will be highly appreciated.

**Comment by syzygy1** [comment]
Maybe I will have a look at some point, but at the moment I'm not really interested.
