### ISSUE TITLE
NodeAffinity

### ISSUE THREAD

**Issue by hero2017** [syzygy1/Cfish#15]
Is the NUMA=all option supposed to work the same as asmFish's NodeAffinity=all option?

If so, what about the other options for specifying different numa nodes like in asmFish? Will NUMA=1 force cFish to use only NUMA node 1? If so then it's not working.

With asmFish I can set NodeAffinity=1 and it'll only use NUMA node 1 and the cores on NUMA node 1. This works because if I set an engine tournament like asmFish vs H5 and I have 2 cpu's and 36 cores then I can tell asmFish to use only NUMA node 1 and only 18 of its cores while cFish will use the other 18 cores on NUMA node 0. Both engines run at 50% cpu utilization which means my system is running at 100% cpu and all 36 cores and this would be correct.

If I try to set up the same tournament with H5 vs cFish and I set cFish's NUMA option to NUMA=1 then it still uses NUMA 0 and so does H5 and cpu utilization for each engine is then only 25% which is incorrect. Another words, the tournament would be unfair to one of the engines since both are fighting for the same resources...unfair or at least run inefficiently.

I assume the NUMA option in cFish doesn't have the same features as NodeAffinity in asmFish correct? Too bad.

**Comment by syzygy1** [comment]
https://github.com/syzygy1/Cfish/issues/11#issuecomment-258047763
