### ISSUE TITLE
Integrate Cfish in Xcode

### ISSUE THREAD

**Issue by GiordanoVicoli** [syzygy1/Cfish#151]
Hi,

Hi just created an Objective C project in Xcode and I added Cfish files.
When I try to compile I have several errors in the nnue.c file:

Below an example; The error is: "No member named 'dirtyPiece' in 'struct Stack'"

  Square ksq = orient(c, square_of(c, KING));
  DirtyPiece *dp = &(pos->st->dirtyPiece);
  for (int i = 0; i < dp->dirtyNum; i++) {
    Piece pc = dp->pc[i];
    if (type_of_p(pc) == KING) continue;
    if (dp->from[i] != SQ_NONE)
      removed->values[removed->size++] = make_index(c, dp->from[i], pc, ksq);
    if (dp->to[i] != SQ_NONE)
      added->values[added->size++] = make_index(c, dp->to[i], pc, ksq);
  }
}

is there anyone able to give me some suggestion?

Many thanks and regards,
Giordano

**Comment by syzygy1** [comment]
On Apple, you can compile with "make".
If that is not what you want, ask someone who knows Xcode.
