### ISSUE TITLE
Old NUMA issue

### ISSUE THREAD

**Issue by JavaMast** [syzygy1/Cfish#155]
This issue https://github.com/syzygy1/Cfish/issues/33 is still present with current Cfish

On a Dual Xeon (2 * 12 cores, HT disabled)
in engine matches on 1 thread with concurrency>12, all Cfish copies is binded on the first NUMA node.
Also in Aquarium IDeA with 22 copies of Cfish - used only first node.

![50343905948_5c5333c09d_o](https://user-images.githubusercontent.com/42765009/93250761-f3c53280-f79b-11ea-9ab5-21883080d078.jpg)

Of course there are no issue with Cfish compiled with NUMA=no, or if set NUMA=off in settings.
But not all knows about it, and asking me if there is a bug in Cfish.

Is it possible to add this commit https://github.com/official-stockfish/Stockfish/commit/bc3b148d5712ef9ea00e74d3ff5aea10a4d3cabe to fix it?

I was tried this changes:

`#include "uci.h"`

https://github.com/syzygy1/Cfish/blob/master/src/numa.c#L306
```
if (option_value(OPT_THREADS) < 9) {
    numaAvail = false;
    settings.numaEnabled = delayedSettings.numaEnabled = false;
  }
  else if (numNodes <= 1) {
    numaAvail = false;
    settings.numaEnabled = delayedSettings.numaEnabled = false;
  }
```
and it works fine in IDeA (not tested yet in engines matches)

**Comment by syzygy1** [comment]
The proper solution is indeed to disable NUMA, either by using a non-NUMA build or disabling it with the UCI option. The few people with NUMA systems who don't know how to do that are not a good enough reason for me to artificially handicap the NUMA implementation of Cfish.

At some point I will probably add the possibility to select a subset of NUMA nodes on which to run the threads (this is already possible on Linux), but this won't help a user who doesn't know how to disable NUMA (and it wouldn't be of much benefit for Aquarium).
