### ISSUE TITLE
Not able to compile Cfish for iOS while I am able to compile Stockfish

### ISSUE THREAD

**Issue by GiordanoVicoli** [syzygy1/Cfish#156]
Hi,

I am not able to compile Cfish for iOS under Xcode while I am able to compile Stockfish source!

Where is the problem?

I compiled other software written in C under iOS without problems.

Is there a binaries release for macOS?

Thanks and regards,
Giordano

**Comment by syzygy1** [comment]
Sorry, I cannot help you with iOS, and I don't have a macOS system. If someone else compiles Cfish 12 for Mac, I can put it up.

**Comment by syzygy1** [comment]
OK, I'll keep this open for a little while just in case there is an easy solution.

How do you compile Stockfish? Using its Makefile?

I have no idea about iOS or Xcode and I am not going to learn about it. But if there is a problem in the Makefile, I can see how to fix it.

**Comment by GiordanoVicoli** [comment]
OK, thank for keeping open this issue.

To include a C or a C++ program in a iOS application you can't generate the executable. You have to include the code in the application and the code will be compiled with the entire application. When I try to include Cfish I immediately get several  errors I am not able to understand. Tomorrow morning I'll post a screenshot of these errors. About compilation with makefile I didn't try. Tomorrow morning I'll try and I'll let you know.


Another useful thing is generate executable for MacOS. I can try to do it and I'll let you know.

Regards,
Giordano

**Comment by GiordanoVicoli** [comment]
Hi,

here is a screenshot I have in Xcode when I try to compile Cfish. The errors are in the file nnue.c
<img width="2374" alt="Schermata 2020-09-17 alle 08 02 09" src="https://user-images.githubusercontent.com/18027781/93426459-5f062600-f8bc-11ea-960c-c1f8cbfabe19.png">

**Comment by GiordanoVicoli** [comment]
Here is another screenshot when I try to compile Cfish under MacOs with make.
The command is : make profile-build ARCH=x86-64-bmi2 COMP=gcc

<img width="2327" alt="Schermata 2020-09-17 alle 08 16 44" src="https://user-images.githubusercontent.com/18027781/93427590-59114480-f8be-11ea-9833-626d2b3379a0.png">

**Comment by syzygy1** [comment]
Do you have a link to the source code of your project?

**Comment by GiordanoVicoli** [comment]
No, but I can send you the zipped file.

**Comment by syzygy1** [comment]
Well, I was wondering mainly if you were sticking to the terms of the GPLv3 license of Stockfish and Cfish. Incorporating the source code as part of another application is only allowed if that other application is released under the GPLv3. (I could not even give you permission for anything else, since I am not the sole copyright holder of Cfish.)

Your screenshot shows that you should #define NNUE (add -DNNUE) and not #define NUMA (not add -DNUMA).

**Comment by GiordanoVicoli** [comment]
No, I am not interested to include your Cfish in another application. I started saying so to better explain my problem. My main interest is to test this engine on Mac and on iOS because a friend of mine said me that this engine is 30% faster than Stockfish.

**Comment by syzygy1** [comment]
OK, so getting the #defines right should help. Compilation on Mac should be easy if you add COMP=clang (but I cannot test it).
