### ISSUE TITLE
Cannot get CFish to load in Fritz GUI using net nn-54f88d1580b4.nnue

### ISSUE THREAD

**Issue by lex312** [syzygy1/Cfish#158]
When I try to use the official Cfish from 15-09-20 nn-03744f8d56d8.nnue it works fine.
But when I try to change the net to nn-54f88d1580b4.nnue then I got this:

“Cfish 150920 64 NUMA” caused an exception.
This is a problem in the engine.

Win6.3 x64
65449 MB
Intel(R) Core(TM) i7-3930K CPU @ 3.20 GHz
N=1/P=1/C=6/L=12/G=1
Nvidia GeForce RTX 2080 TI
Nvidia GeForce RTX 2080 TI
Nvidia GeForce RTX 2080 TI
Nvidia GeForce RTX 2080 TI

See also: https://github.com/syzygy1/Cfish/issues/153

**Comment by MichaelB7** [comment]
AFAIK, Core i7 is not numa - but you are running a version that says it is for NUMA.
Just an observation, may not be the issue but maybe it is.

**Comment by syzygy1** [comment]
Rename the file to something simple to reduce typos. Enter the whole path starting from C:. No extra spaces, etc. Just be precise or it won't work.

**Comment by JavaMast** [comment]
@lex312 
close GUI and rename your network to nn-03744f8d56d8.nnue

@MichaelB7 
 Cfish always print "NUMA" if compiled with NUMA=yes

**Comment by syzygy1** [comment]
NUMA is not a problem here.

I have once and the EvalFile option works perfectly for me, both in the Linux and the Windows builds. If you can't get it typed right in Fritz, try it from a DOS prompt.

setoption name EvalFile value nn-54f88d1580b4.nue
go depth 10

Do not make any typing mistakes. I can't help with that...
Do not leave out ".nnue" just because you think it is not needed.
Etc.

**Comment by lex312** [comment]
Thx.
Entering the whole path works fine: C:\CFish\CF_EXT_160920_x32-x64\nn-dc9152fbd322.nnue 
Rename the network also works fine.

I would prefer a better solution.
1. delete old .nnue.
2. download new .nnue into the same folder.
3. Engine detect automatically the .nnue if there is one in the folder.

We have networks from sergiovieri, nodchip and noobpwnftw.
What are the differences?
Which one is the best?
Do we have small and big nets for weak and strong CPUs like i3 or r5 or 64 cores AMD Threadripper?
