### ISSUE TITLE
Wtime Btime

### ISSUE THREAD

**Issue by XsupremeX** [syzygy1/Cfish#16]
May I make a question?

what code I must add to engine source codes or what line I can modify to make engine play in a specific time and not depending on the GUI like Fritz to set the clock?
I mean is: engine plays for example 1 minute game in every game and not need to set time in the GUI or even engine not follow time in the GUI. Or it is not possible?!?!? Like using a no-GUI option

Gracias!

**Comment by syzygy1** [comment]
I never this issue, probably because you closed it quickly
If you're still interested: change this empty line 208
https://github.com/syzygy1/Cfish/blob/4ce2352b8a7a7d520d89e3d6e8eb5341a568bd71/src/uci.c#L207-L210
into
'  Limits.movetime = 60000;'
for 60 seconds (60000 milliseconds) per move.
