### ISSUE TITLE
nnue.c:1433:5 error: initializer element is not constant

### ISSUE THREAD

**Issue by Dhakshith** [syzygy1/Cfish#160]
make pgo
........
nnue.c:1433:5 error: initializer element is not constant
      TransformerStart + 4 + 2 * 256 + 2 * 256 * 64 * 641;

**Comment by syzygy1** [comment]
Which compiler?

**Comment by Dhakshith** [comment]
gcc

**Comment by syzygy1** [comment]
I think that is a bug in gcc-7.5, but I will probably work around it.
For now, you can replace "TransformerStart" with "3 * 4 + 177" (or just 189) to get it to compile.

**Comment by Dhakshith** [comment]
thanks
