### ISSUE TITLE
Not able anymore to compile 32bit armv7 or armv7-neon for Android on Linux.

### ISSUE THREAD

**Issue by massimilianogoi** [syzygy1/Cfish#162]
Platform: Linux mint, NDK perfectly installed. The armv8 compilation runs smoothly.

Not able anymore to compile 32bit.

armv7:

max@max-virtual-machine:/mnt/hgfs/Massimiliano Goi/Cfish-master/src$ **make build ARCH=armv7 COMP=ndk**

Config:
debug: 'no'
sanitize: 'no'
optimize: 'yes'
arch: 'armv7'
bits: '32'
kernel: 'Linux'
os: 'GNU/Linux'
prefetch: 'yes'
popcnt: 'no'
pext: 'no'
sse: 'no'
mmx: 'no'
sse2: 'no'
ssse3: 'no'
sse41: 'no'
avx2: 'no'
avx512: 'no'
vnni: 'no'
neon: 'no'
native: 'no'
embed: 'no'

Flags:
CC: armv7a-linux-androideabi16-clang
CFLAGS: -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE
LDFLAGS:  -lm -static -latomic -z muldefs -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE -fPIE

Testing config sanity. If this fails, try 'make help' ...

make ARCH=armv7 COMP=ndk all
make[1]: Entering directory '/mnt/hgfs/Massimiliano Goi/Cfish-master/src'
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o benchmark.o benchmark.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o bitbase.o bitbase.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o bitboard.o bitboard.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o endgame.o endgame.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o evaluate.o evaluate.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o main.o main.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o material.o material.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o misc.o misc.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o movegen.o movegen.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o movepick.o movepick.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o pawns.o pawns.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o position.o position.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o psqt.o psqt.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o search.o search.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o tbprobe.o tbprobe.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o thread.o thread.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o timeman.o timeman.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o tt.o tt.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o uci.o uci.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o ucioption.o ucioption.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o numa.o numa.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o settings.o settings.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o polybook.o polybook.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -flto=thin -fPIE   -c -o nnue.o nnue.c
nnue.c:1166:55: error: use of undeclared identifier 'SIMD_WIDTH'
  const unsigned numChunks = (16 * kHalfDimensions) / SIMD_WIDTH;
                                                      ^
1 error generated.
make[1]: *** [<builtin>: nnue.o] Error 1
make[1]: Leaving directory '/mnt/hgfs/Massimiliano Goi/Cfish-master/src'
make: *** [Makefile:818: build] Error 2

full parameters armv7:

max@max-virtual-machine:/mnt/hgfs/Massimiliano Goi/Cfish-master/src$ **make cfish COMP=ndk COMPCC="/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21" ARCH=armv7 numa=no embed=yes lto=yes**
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o benchmark.o benchmark.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o bitbase.o bitbase.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o bitboard.o bitboard.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o endgame.o endgame.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o evaluate.o evaluate.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o main.o main.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o material.o material.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o misc.o misc.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o movegen.o movegen.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o movepick.o movepick.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o pawns.o pawns.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o position.o position.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o psqt.o psqt.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o search.o search.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o tbprobe.o tbprobe.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o thread.o thread.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o timeman.o timeman.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o tt.o tt.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o uci.o uci.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o ucioption.o ucioption.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o numa.o numa.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o settings.o settings.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o polybook.o polybook.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -flto=thin -fPIE   -c -o nnue.o nnue.c
nnue.c:1166:55: error: use of undeclared identifier 'SIMD_WIDTH'
  const unsigned numChunks = (16 * kHalfDimensions) / SIMD_WIDTH;
                                                      ^
1 error generated.
make: *** [<builtin>: nnue.o] Error 1

armv7-neon:

max@max-virtual-machine:/mnt/hgfs/Massimiliano Goi/Cfish-master/src$ **make build ARCH=armv7-neon COMP=ndk**

Config:
debug: 'no'
sanitize: 'no'
optimize: 'yes'
arch: 'armv7'
bits: '32'
kernel: 'Linux'
os: 'GNU/Linux'
prefetch: 'yes'
popcnt: 'yes'
pext: 'no'
sse: 'no'
mmx: 'no'
sse2: 'no'
ssse3: 'no'
sse41: 'no'
avx2: 'no'
avx512: 'no'
vnni: 'no'
neon: 'yes'
native: 'no'
embed: 'no'

Flags:
CC: armv7a-linux-androideabi16-clang
CFLAGS: -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE
LDFLAGS:  -lm -static -latomic -z muldefs -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE -fPIE

Testing config sanity. If this fails, try 'make help' ...

make ARCH=armv7-neon COMP=ndk all
make[1]: Entering directory '/mnt/hgfs/Massimiliano Goi/Cfish-master/src'
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o benchmark.o benchmark.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o bitbase.o bitbase.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o bitboard.o bitboard.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o endgame.o endgame.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o evaluate.o evaluate.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o main.o main.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o material.o material.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o misc.o misc.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o movegen.o movegen.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o movepick.o movepick.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o pawns.o pawns.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o position.o position.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o psqt.o psqt.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o search.o search.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o tbprobe.o tbprobe.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o thread.o thread.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o timeman.o timeman.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o tt.o tt.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o uci.o uci.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o ucioption.o ucioption.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o numa.o numa.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o settings.o settings.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o polybook.o polybook.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE   -c -o nnue.o nnue.c
armv7a-linux-androideabi16-clang -o cfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o tbprobe.o thread.o timeman.o tt.o uci.o ucioption.o numa.o settings.o polybook.o nnue.o  -lm -static -latomic -z muldefs -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DUSE_POPCNT -DUSE_NEON -DNNUE -flto=thin -fPIE -fPIE
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: cfish: Input/output error
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Makefile:933: cfish] Error 1
make[1]: Leaving directory '/mnt/hgfs/Massimiliano Goi/Cfish-master/src'
make: *** [Makefile:818: build] Error 2
max@max-virtual-machine:/mnt/hgfs/Massimiliano Goi/Cfish-master/src$ 

I ran the command **make clean** before every compilation attempt.

**Comment by syzygy1** [comment]
Fixed
