### ISSUE TITLE
Also simultaneous release with Stockfish required.

### ISSUE THREAD

**Issue by vishwarajnair** [syzygy1/Cfish#164]
To check the performance please update CFish on a regular basis. I request you please.

**Comment by MichaelB7** [comment]
Good manners go a long way on Github , stating "Also simultaneous release with Stockfish **required** " is not good manners

https://gomakethings.com/open-source-etiquette/

**Comment by vishwarajnair** [comment]
I am really sorry if any of my words caused any pain. Did not meant the slightest. Actually I am CFish fan and love the speed of C over C++. So I was overly joyous when I posted the issue.

**Comment by vishwarajnair** [comment]
> ase with Stockfish **r**

And thanks a ton for spending so much time for CFish. It means a lot to us Chess fans.

**Comment by MichaelB7** [comment]
It is ok to make a request - but do not use imperative words such as , “required” , “must” etc - it comes across as if you are demanding these features.  Language is very  important , especially when it is written.

**Comment by vishwarajnair** [comment]
Yes all right. My first language is not English. Pardon that. ;) It is a request only.

**Comment by JavaMast** [comment]
@vishwarajnair 
here my compilations of Cfish
https://pixeldrain.com/u/CB6cgjwG

You can check performance with this version of Stockfish:
```
Author: Stefan Geschwentner
Date: Mon Sep 21 08:19:10 2020 +0200
Timestamp: 1600669150

Tweak hybrid treshold.

Increase the first hybrid threshold with more material.
Rewrite the hybrid rules for clarity.
```

![Screenshot_88](https://user-images.githubusercontent.com/42765009/94170601-f0ffc700-fe98-11ea-8946-77373e8ea197.png)


If you have some questions about this compilations, please ask me here http://outskirts.altervista.org/forum/viewtopic.php?f=12&t=83&p=18184#p18184
or here https://forchess.ru/showthread.php?p=152556#post152556

**Comment by MichaelB7** [comment]
+1 Excellent!

**Comment by vishwarajnair** [comment]
Thank you so much. I have played CFish against Stockfish many times now and CFish reaches a greater depth in very less time and hence wins the game many a times against stockfish development builds. I feel that the programming of Stockfish if done in C is a much better option. Because programmers are working on C and C++ both but if they only work on C it would reach the goal sooner by synergy. I will also use your versions of CFish and reply to you for the same. And thank you again for sharing your compilation. It means a lot to me. 👍
