### ISSUE TITLE
LP Issues

### ISSUE THREAD

**Issue by vishwarajnair** [syzygy1/Cfish#165]
I tried enabling large pages on Windows 10. And I think it is enabled but I am not sure but when I am running CFish on Fritz 17 GUI, it is showing an error that **unable to allocate large pages for the transportation table.** I am attaching images for the same issue. If anyone has any idea about what is wrong I am doing, please do share. Thanks. :)

![1](https://user-images.githubusercontent.com/70439984/94347345-f273ef80-0050-11eb-98af-19a9292c3b52.PNG)
![2](https://user-images.githubusercontent.com/70439984/94347347-f6a00d00-0050-11eb-86ee-bd010912fad1.PNG)
![3](https://user-images.githubusercontent.com/70439984/94347352-facc2a80-0050-11eb-8ecf-0faf82e4d86d.PNG)
![4](https://user-images.githubusercontent.com/70439984/94347355-fe5fb180-0050-11eb-99d2-afc0baa9ee5f.PNG)

**Comment by syzygy1** [comment]
There are LP guides on the internet.
