### ISSUE TITLE
CFish doesn't start on Scid

### ISSUE THREAD

**Issue by rankinmark** [syzygy1/Cfish#169]
Hello. I tried to install Cfish 12 on scid but it exit immediately after starting. It's because even if I set largepages to false and I put a relative or absolute path to the network file I use Scid don't pass those parameters. I saw that in log file. Normal stockfish works correctly and read the network file. I think it's a problem of CFish that somehow doesn't pass those values, and probably also other variables. Threads number is correct, but I don't see hash size I set on log file. Can you check please?
From command line I can set both the network file and largepages with setoption command. 
Thank you. Bye

**Comment by rankinmark** [comment]
I forgot to say that I use Window 10.

**Comment by syzygy1** [comment]
Use embedded network.

**Comment by rankinmark** [comment]
It can't find the embedded network too even from command line. However if it does't allow me to disable large pages from Scid it will still crash.

**Comment by syzygy1** [comment]
Use one of the .zip files. Those have the network embedded.

**Comment by syzygy1** [comment]
Embedded means the network is inside the executable and you don't need to set the EvalFile parameter.

**Comment by rankinmark** [comment]
The zip version reads external nets too and doesn't crash with largepages enabled.
Thank you.

**Comment by syzygy1** [comment]
The other version should work too, but it is easy to make a typo.
