### ISSUE TITLE
NEED to REPLACE >> if( useNNUE == EVAL_PURE ) v = nnue_evaluate(pos) * 5 / 4 + Tempo;

### ISSUE THREAD

**Issue by MikeKagansky** [syzygy1/Cfish#174]
[ **evaluate.c** / Line 873 ]

**Old Style:**
v = nnue_evaluate(pos) * 5 / 4 + Tempo;

**New Style:**
v = nnue_evaluate(pos) * ( 720 + mat / 32 ) / 1024 + Tempo;

[ OLD <--> NEW ] for solid **Pure**

**Comment by syzygy1** [comment]
You have a point!
(But 720 is 679 now.)
