### ISSUE TITLE
Error in arm7 compilation.

### ISSUE THREAD

**Issue by massimilianogoi** [syzygy1/Cfish#175]
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Tried the two ways to compile:

max@max-virtual-machine:/mnt/hgfs/Massimiliano Goi/Cfish-master/src$ **make build ARCH=armv7 COMP=ndk**
Default net: nn-62ef826d1a6d.nnue
Already available.

Config:
debug: 'no'
sanitize: 'no'
optimize: 'yes'
arch: 'armv7'
bits: '32'
kernel: 'Linux'
os: 'GNU/Linux'
prefetch: 'yes'
popcnt: 'no'
pext: 'no'
sse: 'no'
mmx: 'no'
sse2: 'no'
ssse3: 'no'
sse41: 'no'
avx: 'no'
avx2: 'no'
avx512: 'no'
vnni: 'no'
neon: 'no'
native: 'no'
embed: 'yes'

Flags:
CC: armv7a-linux-androideabi16-clang
CFLAGS: -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE
LDFLAGS:  -lm -static -latomic -z muldefs -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE -fPIE

Testing config sanity. If this fails, try 'make help' ...

make ARCH=armv7 COMP=ndk all
make[1]: Entering directory '/mnt/hgfs/Massimiliano Goi/Cfish-master/src'
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o benchmark.o benchmark.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o bitbase.o bitbase.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o bitboard.o bitboard.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o endgame.o endgame.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o evaluate.o evaluate.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o main.o main.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o material.o material.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o misc.o misc.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o movegen.o movegen.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o movepick.o movepick.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o pawns.o pawns.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o position.o position.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o psqt.o psqt.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o search.o search.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o tbprobe.o tbprobe.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o thread.o thread.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o timeman.o timeman.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o tt.o tt.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o uci.o uci.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o ucioption.o ucioption.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o numa.o numa.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o settings.o settings.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o polybook.o polybook.c
armv7a-linux-androideabi16-clang -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o nnue.o nnue.c
nnue.c:516:17: warning: unused function 'bit_shuffle' [-Wunused-function]
INLINE unsigned bit_shuffle(unsigned v, int left, int right, unsigned mask)
                ^
1 warning generated.
armv7a-linux-androideabi16-clang -o CF-011220-arm7 benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o tbprobe.o thread.o timeman.o tt.o uci.o ucioption.o numa.o settings.o polybook.o nnue.o  -lm -static -latomic -z muldefs -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE -fPIE
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: CF-011220-arm7: Input/output error
**clang: error: linker command failed with exit code 1 (use -v to see invocation)**
make[1]: *** [Makefile:963: CF-011220-arm7] Error 1
make[1]: Leaving directory '/mnt/hgfs/Massimiliano Goi/Cfish-master/src'
make: *** [Makefile:846: build] Error 2

max@max-virtual-machine:/mnt/hgfs/Massimiliano Goi/Cfish-master/src$ **make CF-011220-arm7 COMP=ndk COMPCC="/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21" ARCH=armv7**
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o benchmark.o benchmark.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o bitbase.o bitbase.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o bitboard.o bitboard.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o endgame.o endgame.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o evaluate.o evaluate.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o main.o main.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o material.o material.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o misc.o misc.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o movegen.o movegen.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o movepick.o movepick.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o pawns.o pawns.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o position.o position.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o psqt.o psqt.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o search.o search.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o tbprobe.o tbprobe.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o thread.o thread.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o timeman.o timeman.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o tt.o tt.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o uci.o uci.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o ucioption.o ucioption.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o numa.o numa.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o settings.o settings.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o polybook.o polybook.c
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE   -c -o nnue.o nnue.c
nnue.c:516:17: warning: unused function 'bit_shuffle' [-Wunused-function]
INLINE unsigned bit_shuffle(unsigned v, int left, int right, unsigned mask)
                ^
1 warning generated.
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/clang --target=armv7a-linux-androideabi21 -o CF-011220-arm7 benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o tbprobe.o thread.o timeman.o tt.o uci.o ucioption.o numa.o settings.o polybook.o nnue.o  -lm -static -latomic -z muldefs -Wall -std=c11  -D_DEFAULT_SOURCE -D_BSD_SOURCE -fPIE -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon -DNDEBUG -O3 -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -flto=thin -fPIE -fPIE
/home/max/ndk/android-ndk-r21d/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: fatal error: CF-011220-arm7: Input/output error
**clang: error: linker command failed with exit code 1 (use -v to see invocation)**
make: *** [Makefile:963: CF-011220-arm7] Error 1

**Comment by MichaelB7** [comment]
I have no issues with Clang under Android Studio with just the basic flags
below.
-DNNUE -DNNUE_EMBEDDED  -DNNUE_SPARSE  -std=c17 -O3  -fno-exceptions  -fPIE
-s
ifeq ($(TARGET_ARCH_ABI),armeabi-v7a)
  MY_ARCH_DEF += -DUSE_NEON -mthumb -march=armv7-a -mfloat-abi=softfp
-mfpu=neon
  LOCAL_ARM_NEON := true
endif

 -flto=thin  does not compile for me - errors  , I am not concerned.

No warnings , no errors.

**Comment by AlexB123** [comment]
I have no warnings or any kind of errors, cross compiling with NDK's Clang.

**Comment by AlexB123** [comment]
> 
> I have no issues with Clang under Android Studio with just the basic flags below. -DNNUE -DNNUE_EMBEDDED -DNNUE_SPARSE -std=c17 -O3 -fno-exceptions -fPIE -s ifeq ($(TARGET_ARCH_ABI),armeabi-v7a) MY_ARCH_DEF += -DUSE_NEON -mthumb -march=armv7-a -mfloat-abi=softfp -mfpu=neon LOCAL_ARM_NEON := true endif -flto=thin does not compile for me, errors out , I am not concerned. No warnings , no errors.
>
Hello Michael. Yes, for armv7 you need to change flag from `-flto=thin` to `-flto`, and you need to use `-std=c11` (instead of `-std=c17`).

**Comment by syzygy1** [comment]
So -flto=thin works for armv8 but not for armv7?

**Comment by syzygy1** [comment]
At least for -flto=thin compiles fine for armv7/NDK.

$ make COMP=ndk ARCH=armv7 numa=no build

or without LTO:

$ make COMP=ndk ARCH=armv7 numa=no build lto=no

**Comment by syzygy1** [comment]
It seems @massimilianogoi is not using an unmodified Makefile, since he apparently does not need numa=no and is compiling an embedded version without adding embed=yes.

**Comment by AlexB123** [comment]
> 
> 
> So -flto=thin works for armv8 but not for armv7?

I don't know about others, I personally use `-flto` for both (armv7-armv8). Engines with `-flto=thin` is a bit slower, than with `-flto`.

**Comment by massimilianogoi** [comment]
@syzygy1 indeed my Makefile was changed, otherwise I could not compile with the standard command **make build ARCH=armv7 COMP=ndk** because of NUMA activated.

Specifically it had the following changes:

nnue = yes
pure = no
sparse = yes
optimize = yes
**lto = yes**
debug = no
sanitize = no
**numa = no**
bits = 64
prefetch = no
popcnt = no
pext = no
sse = no
mmx = no
sse2 = no
ssse3 = no
sse41 = no
avx = no
avx2 = no
avx512 = no
vnni = no
neon = no
ARCH = auto
native = no
**embed = yes**
STRIP = strip

Could it be because of link time optimization activated?

**Comment by syzygy1** [comment]
Perhaps it is LTO (or specifically -flto=thin), but the Makefile is anyway enabling LTO for arm.

However, haven't you reported this input/output error before, and was the problem then with Cfish or with something in your set up?

Anyway, I am switching the Makefile to -flto instead of -flto=thin.
