### ISSUE TITLE
En passant capture miss

### ISSUE THREAD

**Issue by nuclearace** [syzygy1/Cfish#176]
In r1b1qrk1/1ppp1pp1/1b3Bnp/4P3/pPB5/2pQ1N2/P4PPP/R3R1K1 b - - 3 17, after the suggested engine move d5, CFish seems to completely forget en passant, eval goes from > 0 to < -5. After exd6, it again goes > 0. 

Doesn't seem to happen on latest SF dev.

Tested on f9fe7b1 build with `make build COMP=clang ARCH=x86-64-modern numa=no extra=no`

**Comment by nuclearace** [comment]
A more extreme example: `5B2/8/8/4RPpk/4pK1N/6P1/4qP2/8 w - g6 0 3`. fxg6# is not found it seems.

**Comment by nuclearace** [comment]
This seems to go back as far as I can compile cfish. Since `13a4179ac8161a94c71ddccbfee2a4731987facb` gets in the way, and I don't have time to resolve conflicts at the moment to do a `git bisect`.

**Comment by pi4chess** [comment]
> r1b1qrk1/1ppp1pp1/1b3Bnp/4P3/pPB5/2pQ1N2/P4PPP/R3R1K1 b - - 3 17

I couldn't reproduce your score variation with Cfish build as of 23/10/2020 and Cfish suggests the "en passant" move with accuracy. So all is fine. Chessman Compilation. x64-popcnt

**Comment by nuclearace** [comment]
@pi4chess are you able to test a master build with `make build COMP=clang ARCH=x86-64-modern numa=no extra=no` ?

**Comment by pi4chess** [comment]
> @pi4chess are you able to test a master build with `make build COMP=clang ARCH=x86-64-modern numa=no extra=no` ?

No. May be this specific compilation option is indeed a problem (?). All my Linux builds are numa no also but not x86-64-modern. I will test also.

**Comment by nuclearace** [comment]
I also see the issue when leaving the arch set to `auto`. So something weird is going on here.

**Comment by pi4chess** [comment]
> r1b1qrk1/1ppp1pp1/1b3Bnp/4P3/pPB5/2pQ1N2/P4PPP/R3R1K1 b - - 3 17

Same. Couldn't reproduce your score variation with build compiled by myself . Cfish with 22/10/2020 SF commits. ARCH=armv8 COMP=clang numa=no

**Comment by nuclearace** [comment]
>Have you tried to compile editing the make file for numa=no instead of giving the option in command line ?

I doubt it has anything to do with numa, since without `numa=no` it just explodes building.

You mentioned earlier you were on x86, but your last post mentions arm. You have both available to test, or only testing arm?

If it's not some x86 issue, I'm wondering if there's some Apple specific build path that might be coming into play, although the only Apple path that looks like it might matter at all is types.h:

```
ifndef __APPLE__
#define TEMPLATE(F,a,...) _Generic((a), \
    int: F##_int,              \
    uint64_t: F##_uint64_t,    \
    unsigned: F##_unsigned,    \
    int64_t: F##_int64_t,      \
    int16_t: F##_int16_t,      \
    uint8_t: F##_uint8_t,      \
    double: F##_double         \
) (a,__VA_ARGS__)
#else
```

But if something were wrong with that, I'd expect bigger fireworks than Cfish missing en passant.

**Comment by pi4chess** [comment]
Yes i have both x86_x64 and arm to test with. Good luck in finding the bug. Seems affects only Apple OS ?

**Comment by pi4chess** [comment]
> long: F##_long,

Just this line is not avail to Apple it seems.

**Comment by nuclearace** [comment]
>Yes i have both x86_x64 and arm to test with. Good luck in finding the bug. Seems affects only Apple OS ?

Looking that way. I've ruled out clang vs gcc. Hacking makefile to point to homebrew installed gcc doesn't change anything.

**Comment by syzygy1** [comment]
Looks like a bug in generate_evasions(), which doesn't seem to generate en passant moves capturing the checking piece.

**Comment by syzygy1** [comment]
Actually, the problem seems to be in the position set up code. At least for 5B2/8/8/4RPpk/4pK1N/6P1/4qP2/8 w - g6 0 3

**Comment by syzygy1** [comment]
The position set up bug is fixed. This fixes the second fen, not the first fen.

So the first position r1b1qrk1/1ppp1pp1/1b3Bnp/4P3/pPB5/2pQ1N2/P4PPP/R3R1K1 b - - 3 17 gives different node counts on Windows/Linux and Apple OS?

Current Cfish version:
position fen r1b1qrk1/1ppp1pp1/1b3Bnp/4P3/pPB5/2pQ1N2/P4PPP/R3R1K1 b - - 3 17
go depth 10
go depth 10
info string Hybrid NNUE evaluation using nn-62ef826d1a6d.nnue enabled.
info depth 1 seldepth 1 multipv 1 score cp -100 nodes 73 nps 4055 tbhits 0 time 18 pv g6f4
info depth 2 seldepth 2 multipv 1 score cp 151 nodes 112 nps 5333 tbhits 0 time 21 pv g6f4 d3c3 g7f6 e5f6
info depth 3 seldepth 3 multipv 1 score cp 151 nodes 152 nps 6909 tbhits 0 time 22 pv g6f4 d3c3 g7f6
info depth 4 seldepth 4 multipv 1 score cp 151 nodes 198 nps 8608 tbhits 0 time 23 pv g6f4 d3c3 g7f6 e5f6
info depth 5 seldepth 5 multipv 1 score cp -193 nodes 899 nps 29966 tbhits 0 time 30 pv g8h8 d3c3 h8g8 a2a3 g7f6 e5f6
info depth 6 seldepth 6 multipv 1 score cp -193 nodes 1100 nps 33333 tbhits 0 time 33 pv g8h8 d3c3 h8g8 a2a3 g7f6 e5f6
info depth 7 seldepth 7 multipv 1 score cp 151 nodes 1641 nps 43184 tbhits 0 time 38 pv g6f4 d3c3
info depth 8 seldepth 8 multipv 1 score cp 187 nodes 2749 nps 58489 tbhits 0 time 47 pv g6f4 d3e4 d7d5 e4f4 d5c4 f3d4
info depth 9 seldepth 10 multipv 1 score cp -3 nodes 7152 nps 83162 tbhits 0 time 86 pv d7d5 e5d6 c8e6 f6c3 c7d6 d3d6 e8d7 d6d7 e6d7 a2a3
info depth 10 seldepth 14 multipv 1 score cp 0 nodes 11284 nps 91739 tbhits 0 time 123 pv d7d5 e5d6 c8e6 f6c3 e6c4 d3c4 e8d7 d6c7 d7c7 c4c7
bestmove d7d5 ponder e5d6

Do you get a different number of nodes than 11284 on Apple OS? (Please check the latest version with bench 4278746 or make clear which version you are testing.)

**Comment by nuclearace** [comment]
@syzygy1 I believe that commit fixed both issues! After pulling latest master, I no longer see any issues with either FEN, nice work! I'll close this out.

**Comment by nuclearace** [comment]
@syzygy1 and to answer your question, I get the same nodes for that FEN, so I think we're all sane for now.

```
position fen r1b1qrk1/1ppp1pp1/1b3Bnp/4P3/pPB5/2pQ1N2/P4PPP/R3R1K1 b - - 3 17
go depth 10
info string Transposition table allocated using large pages.
info string Hybrid NNUE evaluation using nn-62ef826d1a6d.nnue enabled.
info depth 1 seldepth 1 multipv 1 score cp -100 nodes 73 nps 73000 tbhits 0 time 1 pv g6f4
info depth 2 seldepth 2 multipv 1 score cp 151 nodes 112 nps 112000 tbhits 0 time 1 pv g6f4 d3c3 g7f6 e5f6
info depth 3 seldepth 3 multipv 1 score cp 151 nodes 152 nps 152000 tbhits 0 time 1 pv g6f4 d3c3 g7f6
info depth 4 seldepth 4 multipv 1 score cp 151 nodes 198 nps 198000 tbhits 0 time 1 pv g6f4 d3c3 g7f6 e5f6
info depth 5 seldepth 5 multipv 1 score cp -193 nodes 899 nps 449500 tbhits 0 time 2 pv g8h8 d3c3 h8g8 a2a3 g7f6 e5f6
info depth 6 seldepth 6 multipv 1 score cp -193 nodes 1100 nps 550000 tbhits 0 time 2 pv g8h8 d3c3 h8g8 a2a3 g7f6 e5f6
info depth 7 seldepth 7 multipv 1 score cp 151 nodes 1641 nps 820500 tbhits 0 time 2 pv g6f4 d3c3
info depth 8 seldepth 8 multipv 1 score cp 187 nodes 2749 nps 916333 tbhits 0 time 3 pv g6f4 d3e4 d7d5 e4f4 d5c4 f3d4
info depth 9 seldepth 10 multipv 1 score cp -3 nodes 7152 nps 1192000 tbhits 0 time 6 pv d7d5 e5d6 c8e6 f6c3 c7d6 d3d6 e8d7 d6d7 e6d7 a2a3
info depth 10 seldepth 14 multipv 1 score cp 0 nodes 11284 nps 1253777 tbhits 0 time 9 pv d7d5 e5d6 c8e6 f6c3 e6c4 d3c4 e8d7 d6c7 d7c7 c4c7
bestmove d7d5 ponder e5d6
```

**Comment by syzygy1** [comment]
@nuclearace Are you sure that the problem with r1b1qrk1/1ppp1pp1/1b3Bnp/4P3/pPB5/2pQ1N2/P4PPP/R3R1K1 b - - 3 17 is now gone? The problem I fixed occurs only when the position being set up has ep rights (which would be ignored). Your fen doesn't have ep rights.

**Comment by syzygy1** [comment]
Hmm, perhaps you forced d5 by hand and then searched the resulting position (which does have ep rights).

**Comment by nuclearace** [comment]
@syzygy1 Yes, I was just using ChessX with Cfish to flip through _that_ Dubov game and when I noticed the issue. The issue isn't with the initial FEN not finding the en passant capture, but rather after playing d5. I'm not sure how UCI analysis is supposed to be done, but ChessX just sends `position fen ...` after moves. Which then would hit the position setup bug.

**Comment by syzygy1** [comment]
Yes, that is probably what ChessX did.
Most GUIs would probably send "position fen [original fen] moves d7d5", which would not have triggered the bug.

Anyway, thank you for pointing out this bug!!
