### ISSUE TITLE
macOS Mojave 10.14.6 profile (pgo) build fails.

### ISSUE THREAD

**Issue by fischerandom** [syzygy1/Cfish#179]
I built Cfish with:
$ make profile-build ARCH=x86-64-bmi2 COMP=clang numa=no native=yes

Step 3/4. Building optimized executable ...
/Library/Developer/CommandLineTools/usr/bin/make ARCH=x86-64-bmi2 COMP=clang objclean
/Library/Developer/CommandLineTools/usr/bin/make ARCH=x86-64-bmi2 COMP=clang clang-profile-use
llvm-profdata merge -output=cfish.profdata *.profraw
**/bin/sh: llvm-profdata: command not found**
make[1]: *** [clang-profile-use] Error 127
make: *** [profile-build] Error 2

The solution that worked for me was to add **xcrun** to the Makefile, here:

clang-profile-use:
	**xcrun** llvm-profdata merge -output=cfish.profdata *.profraw
	$(MAKE) ARCH=$(ARCH) COMP=$(COMP) \
	EXTRACFLAGS='-fprofile-instr-use=cfish.profdata' \
	EXTRALDFLAGS='-fprofile-use ' \
	all

**Comment by syzygy1** [comment]
Thanks!
