### ISSUE TITLE
Cfish Development

### ISSUE THREAD

**Issue by Denzwell** [syzygy1/Cfish#182]
Is Cfish up to date with news stockfish development ?

it's been 20 days since the source code was modified.

**Comment by syzygy1** [comment]
No nagging. Thanks

**Comment by AlexB123** [comment]
> 
> 
> No nagging. Thanks

Hello Ronald! Hopefully you are fine and healthy! :) Can you tell to Cfish fans please, when the CF 13 will be released (approximately)? 
Thank you, and regards!
