### ISSUE TITLE
this v12 has no NNUE?

### ISSUE THREAD

**Issue by tissatussa** [syzygy1/Cfish#188]
i just did a successfull "git clone" of the newest v12 source. But which SF version is this really ?  It does not seem to have NNUE, other CFish forks have that

**Comment by tissatussa** [comment]
in the right column of https://github.com/syzygy1/Cfish i see "Releases 6 / Cfish 12 [Latest] / on Sep 14, 2020 / + 5 releases" so people know the current ('latest') version : 12.  This could mean this CFish is based on SF 12 but i see no further explanation.

**Comment by syzygy1** [comment]
Cfish 12 indeed corresponds to SF 12, NNUE included

**Comment by syzygy1** [comment]
However, git clone gives you a clone of the full repository. If you don't know git very well, it is easier to download just the Cfish 12 source or a Cfish 12 compile.

**Comment by syzygy1** [comment]
https://github.com/syzygy1/Cfish/releases/tag/cfish_12
