### ISSUE TITLE
Engine Exits without Exit Code on Scid vs PC Ubuntu 20.04

### ISSUE THREAD

**Issue by magicianofriga** [syzygy1/Cfish#191]
Hi all,
I cloned the Cfish repository and then compiled CFish using the following command:
make pgo sparse=yes
The compilation and bench happened without problems. But when running the engine on a GUI like Scid vs PC, it crashes. Can someone offer a solution.

**Comment by JavaMast** [comment]
@magicianofriga 
make sure the network file is in the same folder with the engine
or try **make pgo sparse=yes embed=yes**

**Comment by syzygy1** [comment]
That should indeed solve it.
