### ISSUE TITLE
Updating Cfish code to use more books

### ISSUE THREAD

**Issue by magicianofriga** [syzygy1/Cfish#193]
Hi all,
I would like to update Cfish to use more than two books. Where all should I be changing the code? 
I tried modifying uci options to include book 3 and book 4. I also created two more objects of polybook in polybook.h. Anything else I should be doing?

**Comment by syzygy1** [comment]
Search through the source for polybook2 and do the same for polybook3 and 4.

**Comment by magicianofriga** [comment]
Hi, can you show me the specific places where I need to do this? I am still a novice at coding. Please help!

**Comment by syzygy1** [comment]
You can use any text editor to search through the source.
