### ISSUE TITLE
Support for bigger network.

### ISSUE THREAD

**Issue by AlexB123** [syzygy1/Cfish#196]
Hello. It seеms that Cfish still has an issue with loading bigger networks. Since there is a new default 45.5 mb network ( nn-8a08400ed089.nnue), can you please fix the compatibility?
Thanks.

**Comment by JavaMast** [comment]
@AlexB123 
this is not issue.
Stockfish also cannot use bigger networks without SRC changing.

**Comment by AlexB123** [comment]
> 
> 
> @AlexB123
> this is not issue.
> Stockfish also can not use another networks without SRC changing.
> You can try current SF master with old network - it does not work anymore.

From my point of view it is an issue. For example, Stockfish repertoire has patches, where people can see what kind of changes they need to do in the source code, to make SF to work with bigger or smaller nets. **But Cfish doesn't have any instructions regarding this**. It would be nice if Cfish's repertoire would had similar "instructions", so people would know, what and where they can change in the source code to make Cfish work with eg bigger network. It can be a simple patch, which can be not included in the Master, it will be something like a tip.

**Comment by syzygy1** [comment]
Cfish does not support other network sizes.

**Comment by AlexB123** [comment]
> 
> 
> Cfish does not support other network sizes.

Ah, that's sad. Anyway, can Cfish get (some) further updates? I have an AMD Ryzen 7 1800X, 8 cores / 16 threads, 64-bit, 3.60 GHz, 16 GB RAM, Windows 10 pro, i can help with testing new patches in CuteChess (using concurrency 15, 1 core per engine, around 12000 games per test with TC: 60+0.6).

**Comment by magicianofriga** [comment]
Hi,
Any plans on updating the Cfish architecture to support the larger network? It has produced a lot of elo gains for the original Stockfish.
