### ISSUE TITLE
Possible compilation error on AVX512, VNNI512 and VNNI256.

### ISSUE THREAD

**Issue by massimilianogoi** [syzygy1/Cfish#197]
Not sure if it's because of my processor (I have an Intel i7-4771).

I get this error while trying to compile for AVX512, VNNI512 or VNNI256:

massi@DESKTOP-L0HH8U4 MINGW64 ~/Cfish-master/src
$ make profile-build ARCH=x86-64-avx512 COMP=mingw
Default net: nn-62ef826d1a6d.nnue
Already available.

Config:
debug: 'no'
sanitize: 'no'
optimize: 'yes'
arch: 'x86_64'
bits: '64'
kernel: 'MINGW64_NT-10.0-19042'
os: 'Windows_NT'
prefetch: 'yes'
popcnt: 'yes'
pext: 'yes'
sse: 'yes'
mmx: 'no'
sse2: 'yes'
ssse3: 'yes'
sse41: 'yes'
avx: 'yes'
avx2: 'yes'
avx512: 'yes'
vnni: 'no'
neon: 'no'
native: 'no'
embed: 'no'

Flags:
CC: gcc
CFLAGS: -Wall -std=c11  -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE
LDFLAGS:  -lm -m64

Testing config sanity. If this fails, try 'make help' ...

Step 1/4. Building instrumented executable ...
make ARCH=x86-64-avx512 COMP=mingw gcc-profile-make
make[1]: Entering directory '/home/massi/Cfish-master/src'
make ARCH=x86-64-avx512 COMP=mingw \
EXTRACFLAGS='-fprofile-generate' \
EXTRALDFLAGS='-lgcov' \
all
make[2]: Entering directory '/home/massi/Cfish-master/src'
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o benchmark.o benchmark.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o bitbase.o bitbase.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o bitboard.o bitboard.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o endgame.o endgame.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o evaluate.o evaluate.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o main.o main.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o material.o material.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o misc.o misc.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o movegen.o movegen.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o movepick.o movepick.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o pawns.o pawns.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o position.o position.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o psqt.o psqt.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o search.o search.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o tbprobe.o tbprobe.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o thread.o thread.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o timeman.o timeman.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o tt.o tt.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o uci.o uci.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o ucioption.o ucioption.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o numa.o numa.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o settings.o settings.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o polybook.o polybook.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m64 -DNDEBUG -O3 -DIS_64BIT -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -msse4 -mbmi2 -DUSE_AVX2 -mavx2 -DUSE_AVX512 -mavx512f -mavx512bw -DUSE_SSE41 -msse4.1 -DUSE_SSSE3 -mssse3 -DUSE_SSE2 -msse2 -msse -DUSE_SSE -DNUMA -DNNUE   -c -o nnue.o nnue.c
gcc -o cfish benchmark.o bitbase.o bitboard.o endgame.o evaluate.o main.o material.o misc.o movegen.o movepick.o pawns.o position.o psqt.o search.o tbprobe.o thread.o timeman.o tt.o uci.o ucioption.o numa.o settings.o polybook.o nnue.o -lgcov -lm -m64
make[2]: Leaving directory '/home/massi/Cfish-master/src'
make[1]: Leaving directory '/home/massi/Cfish-master/src'

Step 2/4. Running benchmark for pgo-build ...
./cfish bench 16 1 15 default depth nnue > /dev/null
**make: *** [Makefile:863: profile-build] Error 132**

In line 863 of Makefile there is the PGO-BUILD command.

**Comment by syzygy1** [comment]
Are you cross compiling on Linux for Windows? Then you have to replace cfish with cfish.exe in the PGO BUILD component. On Windows this should not be a problem (but perhaps it's the shell you are using).

**Comment by massimilianogoi** [comment]
> Are you cross compiling on Linux for Windows? Then you have to replace cfish with cfish.exe in the PGO BUILD component. On Windows this should not be a problem (but perhaps it's the shell you are using).

No, it's MSYS2 on Windows.

**Comment by JavaMast** [comment]
@massimilianogoi 
i7-4771 does not support AVX 512 and VNNI  https://ark.intel.com/content/www/us/en/ark/products/77656/intel-core-i7-4771-processor-8m-cache-up-to-3-90-ghz.html
so you can only made a non PGO build.

If you need it, i can made AVX512, VNNI512 and VNNI256 builds.

**Comment by syzygy1** [comment]
@JavaMast: well spotted!

@massimilianogoi you can't make profile builds for architectures incompatible with your CPU.

**Comment by massimilianogoi** [comment]
For a while I was able to compile for those architectures too, strange... Anyway, I can close the issue now because of the above explanation.
