### ISSUE TITLE
Large pages not working.

### ISSUE THREAD

**Issue by hero2017** [syzygy1/Cfish#2]
Tested asmFish with LP and it's fine including numa. While cFish's numa seems to be working for me large pages are not. Using Win'2008 R2 Ent. with 64 GB ram, 2 x E5-2696v3.

**Comment by syzygy1** [comment]
Large pages on Windows should work now. Let me know if there is still a problem. (I cannot test this myself.)

**Comment by hero2017** [comment]
Confirmed. Working beautifully now with numa and LP! Excellent work syzygy1!! Keep up the great work.
