### ISSUE TITLE
Black magic move generation

### ISSUE THREAD

**Issue by ChessMan3** [syzygy1/Cfish#20]
I just compile CFish with MAGIC_BLACK and on my machine (Phenom II x6) it's slightly faster than MAGIC_PLAIN.  https://postimg.org/image/yr7ymwjg5/

1 core, 0.25 sec/move:

Score of CFish_x64_120817_popcnt_710gcc vs CFish_x64_120817_Black_magic_popcnt_710gcc: 35 - 48 - 153 [0.472]
ELO difference: -19.16 +/- 26.27

236 of 2000 games finished.

Of course, there are only 236 games...

**Comment by ChessMan3** [comment]
Just one notice: i used modernized makefile (2 - 3.5% faster) for both compiles.
You can see diff here: https://github.com/ChessMan3/CF_r/commit/cc0b57485b5452e3cdc390ee16a67d893f4606d8

**Comment by syzygy1** [comment]
What happens if you load the two versions in reverse order in Build Tester? So 1. magic_plain, 2. black_magic?

**Comment by ChessMan3** [comment]
MAGIC_BLACK still faster:
https://postimg.org/image/n2av1t2cl/

**Comment by syzygy1** [comment]
Thanks, I was just curious.

Your Makefile adds link-time optimization (-flto). For some reason that has never worked for me, but I will try it on my laptop. I remember someone saying it helped more for more recent processors.

**Comment by CoffeeOne** [comment]
I seem to have a speed up for magic black on Opteron 6386SE (no pext) , too:
Windows, GCC 7.1, profile build 64 modern, both builds with lto
Command Line: bench 16 1 15  default depth
Tests per Build: 30
Engine 1 CFish Master
Engine 2 CFish #define MAGIC_BLACK
                Engine# (NPS)                     Speedup     Sp     Conf. 95%    S.S.
2  (1 640 520,6   ) ---> 1  (1 613 256,7   ) --->  1,690%  31 122,4     Yes       No
