### ISSUE TITLE
CFish with  -march=native

### ISSUE THREAD

**Issue by ChessMan3** [syzygy1/Cfish#22]
For some reason CFish with Native=yes is worst than without, on my PC:

Phenom II x6 1090T @ 3.6 GHz
RR\1 core per engine\ 0.25 sec per move\ Cute Chess 0.9.4\ 16MB\ book:Hert500.pgn

     Program                           Elo    +    -   Games   Score   Av.Op.  Draws

   1 CFish_x64_180817_popcnt  __________  : 3207 __    2  __  2 __ 5000 __   52.0 %  __  3193 __  62.2 %
   2 CFish_x64_180817_Native_popcnt __  : 3193  __  2  __ 2 __ 5000 __   48.0 % __  3207 __   62.2 %

Games: http://www24.zippyshare.com/v/zZgTIsqb/file.html

**Comment by MichaelB7** [comment]
Not surprised.  Try March=native and then followed by O2 and msse3.  Each machine , cpu are different in what works best. also mtune=native .  Ymmv.
