### ISSUE TITLE
Wrong bench

### ISSUE THREAD

**Issue by ChessMan3** [syzygy1/Cfish#24]
Hi! After update CFish to "Prevent Stockfish from exiting if DTZ table is not present" bench is (a little) different (compared to Stockfish):  541752**3** instead of 541752**1**

https://postimg.org/image/cpeqcf7md/

**Comment by syzygy1** [comment]
I am aware of this, see the commit message:
https://github.com/syzygy1/Cfish/commit/716c2a6710648faef794bac857f75df941cc81b5

The difference occurs in position 19/42 at ply 13. I will investigate this later.

Unfortunately there is no deviation when starting a fresh search from the position (I checked up to d25):
2K5/p7/7P/5pR1/8/5k2/r7/8 w - - 0 1 moves g5g6 f3e3 g6g5 e3f3
(Type "position fen 2K5/..." in the console or set up the position and perform moves g5g6 f3e3 g6g5 e3f3.)

This makes debugging a bit annoying, though not impossible.

If you happen to come across a position where Cfish's node count deviates from SF's at a relatively early depth, that could be helpful.

**Comment by ChessMan3** [comment]
I'm sorry) I first write - then read)))

**Comment by ChessMan3** [comment]
I added the patches one by one and found where the bench deviates: check patch **"Simplify away non-normal moves in SEE"**  https://github.com/official-stockfish/Stockfish/commit/bf485f4affc37cd408a65b66b8a3aad059bad5f3

must be **5713905** but it's 571390**7**

https://postimg.org/image/kt0c3ts2d/

**Comment by syzygy1** [comment]
A fresh search of position 19/42 does not show a deviation, but interestingly a fresh seach of position 18/42 does.

Stockfish:
position fen 3b4/5kp1/1p1p1p1p/pP1PpP1P/P1P1P3/3KN3/8/8 w - - 0 1
go depth 4
info depth 1 seldepth 1 multipv 1 score cp 130 nodes 12 nps 12000 tbhits 0 time 1 pv d3c3
info depth 2 seldepth 2 multipv 1 score cp 317 nodes 34 nps 34000 tbhits 0 time 1 pv d3c3 g7g6 f5g6 f7g7
info depth 3 seldepth 4 multipv 1 score cp 127 nodes 110 nps 110000 tbhits 0 time 1 pv d3c3 d8c7 c3d3
info depth 4 seldepth 4 multipv 1 score cp 138 nodes **238** nps 238000 tbhits 0 time 1 pv c4c5 b6c5 e3c4 d8c7
bestmove c4c5 ponder b6c5

Cfish:
position fen 3b4/5kp1/1p1p1p1p/pP1PpP1P/P1P1P3/3KN3/8/8 w - - 0 1
go depth 4
info depth 1 seldepth 1 multipv 1 score cp 130 nodes 12 nps 3000 tbhits 0 time 4 pv d3c3
info depth 2 seldepth 2 multipv 1 score cp 317 nodes 34 nps 6800 tbhits 0 time 5 pv d3c3 g7g6 f5g6 f7g7
info depth 3 seldepth 4 multipv 1 score cp 127 nodes 110 nps 22000 tbhits 0 time 5 pv d3c3 d8c7 c3d3
info depth 4 seldepth 4 multipv 1 score cp 138 nodes **268** nps 53600 tbhits 0 time 5 pv c4c5 b6c5 e3c4 d8c7
bestmove c4c5 ponder b6c5

I'll try to fix it tomorrow.

**Comment by syzygy1** [comment]
Unfortunately the mismatch at depth 4 for position 18/42 is unrelated to the bench mismatch.

Stockfish no longer treats the first repetition of the root position as a draw. I think this is wrong, so I have implemented that behaviour only for benches. Maybe I should reconsider this or make it configurable, but I checked that node counts for the 18/42 position are identical if 18/42 is run as a bench (save the position to a file pos18_42.txt, then run "cfish 16 1 13 pos18_42.txt").

The bench mismatch will have to wait for tomorrow.

**Comment by syzygy1** [comment]
OK, the bench mismatch is related to draw detection after all. My small hack to fix bench numbers probably does not work correctly if the bench position is a fen followed by a couple of moves.

**Comment by syzygy1** [comment]
OK, this is the problem: 19/42 sets up a position with a repeated root position. So in this case, SF does count the first repetition as draw. But my hack does not test whether the root position was repeated (in game history) when tricking Cfish into not detecting the first repetition of the root position as a draw.

**Comment by syzygy1** [comment]
Fixed.
