### ISSUE TITLE
"Update TB probing code."

### ISSUE THREAD

**Issue by ChessMan3** [syzygy1/Cfish#26]
Hello! After patch **"Update TB probing code."**  CFish began to play worse. 

 Score of CFish_x64_150917_Make_ss_ply_720mingw vs CFish_x64_150917_V2_Update_TB_probing_code_720mingw: 161 - 115 - 454 [0.532]
Elo difference: 21.92 +/- 15.47

730 of 2000 games finished.

*** 
Do not pay attention to the date in the title - I just forgot to change it in the bat file...

**Comment by syzygy1** [comment]
Strange. The versions before and after have the same bench. I have just compiled both and the version after the update has a very slightly faster bench (for no good reason, so that's just noise).

Did you test with or without TBs enabled?
Does one achieve (much) higher nps than the other?

I will run a short test to see if I notice any difference.

**Comment by ChessMan3** [comment]
I test without TBs. And i test version before this patch.  "Update TB probing code." is little faster than "Make ss->ply == 0 in the root node." but weaker.

Score of CFish_x64_150917_Make_ss_ply_720mingw vs CFish_x64_150917_V2_Update_TB_probing_code_720mingw: 233 - 163 - 656 [0.533]
Elo difference: 23.15 +/- 12.85

1052 of 2000 games finished.

========
Sometimes patches that do not change the bench significantly change the strength of the playing.

**Comment by ChessMan3** [comment]
I noticed this when I tested the new version against the September 12 version  **"Updated to "Extend ShelterWeakness array by dimension isKingFile"."**

Score of CFish_x64_170917_NUMA_popcnt_720mingw vs CFish_x64_120917_popcnt_720mingw: 48 - 76 - 187 [0.455]
Elo difference: -31.37 +/- 24.34

311 of 2000 games finished.

**Comment by syzygy1** [comment]
Yes, the size increased. That is fine.
So far my test run is not showing anything strange, but I will let it run longer.
Do you see crashes or time losses or other strange things?

**Comment by ChessMan3** [comment]
Yes, very much crashes (on windows) but no more than before this patch.
I will run new test tomorrow.

**Comment by syzygy1** [comment]
Cfish crashes on Windows? It should not.
Or does Stockfish crash too?

**Comment by ChessMan3** [comment]
No, only CFish at Win7 x64, CPU phenom II x6 1090T

**Comment by ChessMan3** [comment]
New test is finished.


     Program                                                 Elo    +    -   Games   Score   Av.Op.  Draws

   1 CFish_x64_150917_Make_ss_ply_720mingw                 : 3205    2    2  5000    51.4 %   3195   62.2 %
   2 CFish_x64_150917_V2_Update_TB_probing_code_720mingw   : 3195    2    2  5000    48.6 %   3205   62.2 %


PGN: http://www24.zippyshare.com/v/BYNZO4za/file.html

==========
I started new one with fresh compilations in MinGW 7.2.0, without any changes in makefile.

===========
The crash report: https://postimg.org/image/4o1jfle85/

**Comment by ChessMan3** [comment]
New test & 8 crashes in 218 games

Score of CFish_x64_180917_Update_TB_probing_code_orig_MF_720mingw vs CFish_x64_180917_Make_ss-ply__original_MF_720mingw: 32 - 53 - 133 [0.452]
Elo difference: -33.57 +/- 28.75

218 of 5000 games finished.

**Comment by syzygy1** [comment]
My own test gave 484-538-1978 in favour of "Update_TB_probing_code" (within error margins and there is no reason why one would be stronger than the other).

I did notice something that is probably a bug in 3-fold repetition detection. I have not looked into this yet. But it seems to be present in both versions anyway.

I will see if I can reproduce crashes on Windows. If you have a position on which Cfish crashes, that would be helpful.

**Comment by ChessMan3** [comment]
CFish also crashed in "Human vs PC" game: http://i94.fastpic.ru/big/2017/0919/bb/a82625942efb7f6166742e1feaa153bb.jpg

But i don't see any crashes in infinite analyse.

PGN from one of my tests: http://www24.zippyshare.com/v/BYNZO4za/file.html

=================

Strange, in 2 my tests with 5000 games each, CFish with this patch loses.

**Comment by ChessMan3** [comment]
rnbqk2r/ppp1bppp/4p3/5n2/2PP4/2N2N2/PP3PPP/R1BQKB1R w KQkq - 0 9
rn3rk1/p3qppp/b3p3/2pn4/PpNP4/5NP1/1PQ1PPBP/R2R2K1 b - - 0 13
rn1qkb1r/1p3pp1/p2p4/3Pp2p/8/1N1bBP2/PPP3PP/R2QK2R w KQkq - 0 12

**Comment by ChessMan3** [comment]
Another test run. This time i compile CFish from your latest SRC  (CFish_x64_170917_NUMA_popcnt_720mingw). In CFish_x64_190917_NUMA_popcnt_720mingw i deleted patch "Update TB probing code."
 1 core, 0.5 sec per move:

     Program                                    Elo    +    -   Games   Score   Av.Op.  Draws

   1 CFish_x64_190917_NUMA_popcnt_720mingw    : 3207    3    3  2000    52.0 %   3193   66.0 %
   2 CFish_x64_170917_NUMA_popcnt_720mingw    : 3193    3    3  2000    48.0 %   3207   66.0 %
===============

Test from PaulieD http://immortalchess.net/forum/showpost.php?p=790045&postcount=1364
i7 6700HQ | 4 @ 2.6-3.5 | Win10x64-16GB |Gui = CuteChess 1.0.0 
Book = TopGM_2move.pgn | Hash=8MB | Cores=1 | HT=On 
Concurrency 7 | Ponder = No | TB = No | Time = 10"+.1" (=32")

Not enough games, results well within error bars

 # PLAYER                                    :  RATING  ERROR  PLAYED   (%)    W     D    L  D(%)
   1 CFish_x64_190917_NUMA_popcnt_720mingw    :    3201      4    2000  50.3  326  1361  313  68.0
   2 CFish_x64_170917_NUMA_popcnt_720mingw    :    3199      4    2000  49.7  313  1361  326  68.0

**Comment by ChessMan3** [comment]
Thank you! Now CFish works fine.

Score of CFish_x64_2909_Fix_a_bug_in_repetition_detection vs CFish_x64_230917_popcnt_720mingw: 326 - 230 - 817 [0.535]
Elo difference: 24.33 +/- 11.67

1378 of 2000 games finished. 0.25s

**Comment by syzygy1** [comment]
But I suppose Cfish still crashes occasionally on your computer?

**Comment by ChessMan3** [comment]
No crashes anymore!

Score of CFish_x64_2909_Fix_a_bug_in_repetition_detection vs CFish_x64_230917_popcnt_720mingw: 326 - 230 - 817 [0.535]
Elo difference: 24.33 +/- 11.67

1378 of 2000 games finished. 0.25s
