### ISSUE TITLE
cfish for android

### ISSUE THREAD

**Issue by Alexei1981** [syzygy1/Cfish#28]
Hello. There was a problem. I compile
Cfish on android and until November all
versions worked fine. But since
cfish-031117 appeared bug. It shows up
when the engine exits the book and
does its own move. For example, in the
following example, cfish makes a black
move 9. ..d5 ?? , spends on it only 2
ms. 1. e4 d6 2. d4 g6 3. Nf3 Bg7 4.
Nc3 Nf6 5. h3 c6 6. a4 Qa5 7. Bd2
Nbd7 8. Bc4 OO 9. Qe2 {[15] 0.66 1.4s
796.9knps Qe2 Qd8} 9 .. . d5 ?? {[1]
0.05 2ms !! 81.0knps ..d5} 10. Nxd5
{[15] 2.39 1.8s 795.0knps Nxd5 Qd8}
10 ... Qd8 {[17] -2.47 2.1s 866.5knps
..Qd8 Nf4} This bug appears only when
you exit the book and (for example, 2m
+ 1s). In a fixed time control (1,2,3
seconds per move) everything is in
order. This bug only appears in versions
released in November, starting from the
3rd date. I'm checking Stockfish
released in November, in the same
numbers, it's all right. I tried different
compilers, the result is the same. Error
in Cfish. I specially compiled the last
cfish of October and it works fine.

**Comment by Alexei1981** [comment]
With a fixed time control (1.2.3 seconds
per turn), there are no such problems.

**Comment by syzygy1** [comment]
Thanks. It sounds like a problem in the update to "Replace easyMove with simple scheme". I'll check if I can find a mistake in my changes.

**Comment by syzygy1** [comment]
I think it is solved now. Please let me know if there are still problems (or new problems).

It seems the cause of the problem was already present before 3 November, but it was not triggered (or only less obviously).

I also corrected a mistake related to pondering (it should allocate 25% more time when pondering, but it did not, probably since the time management changes).

**Comment by Alexei1981** [comment]
Thanks to Mr. De Man. Now everything
works fine, the problem is solved.
