### ISSUE TITLE
Warings while compiling under Msys64 GCC 7.2.0

### ISSUE THREAD

**Issue by Saugstrahler** [syzygy1/Cfish#29]
position.c: In function 'print_pos':
position.c:128:31: warning: unknown conversion type character 'l' in format [-Wformat=]
   printf("\nFen: %s\nKey: %16llX\nCheckers: ",
                                                ^
position.c:128:10: warning: too many arguments for format [-Wformat-extra-args]
   printf("\nFen: %s\nKey: %16llX\nCheckers: ",
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
position.c:128:31: warning: unknown conversion type character 'l' in format [-Wformat=]
   printf("\nFen: %s\nKey: %16llX\nCheckers: ",
                                                ^
position.c:128:10: warning: too many arguments for format [-Wformat-extra-args]
   printf("\nFen: %s\nKey: %16llX\nCheckers: ",
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by syzygy1** [comment]
Probably a bogus warning, unless the actual output is incorrect.

**Comment by syzygy1** [comment]
Should be fixed now.

**Comment by Saugstrahler** [comment]
Yep, just tested and it's gone.
