### ISSUE TITLE
Missing files for Cerebellum support.

### ISSUE THREAD

**Issue by Denzwell** [syzygy1/Cfish#31]
Hi,

This version stop to move after last book move

Best regards

**Comment by MichaelB7** [comment]
I have not seen that behavior under xBoard on macOS, have you tried a different GUI to confirm? Can we assume if you turn the book off , it plays normally but only when book it activated , it plays book moves and then no moves after that?  Many GUI's have have a logging mode which is helpful to debug, can you turn logging on and post the output?

**Comment by syzygy1** [comment]
Fixed
