### ISSUE TITLE
TB hit reporting

### ISSUE THREAD

**Issue by Saugstrahler** [syzygy1/Cfish#32]
Hi Ronald,
I'm using CFish with Arena and made a deep Analysis of one of the Google-Stockfish games. You may know that Arena "writes" a new line every ply. After 33 minutes I got depth 56, ~33 Billion nodes, 600+ Million TB hits....the next line was 1h11m, depth 57, ~ 128 Billion nodes and 1 TB hit. So I guess there was an error reporting more than 1 Billion TB hits....and I don't know if it is CFish or Arena that has this "bug". Can you check if your Cfish is able to report > 1 Billion TB hits correctly?

Saugi

PS: Any release date for (at least) 5-men DTM files?

**Comment by syzygy1** [comment]
Must be a problem with Arena. tb_hits is a 64-bit unsigned int.
