### ISSUE TITLE
Possible HT issue 

### ISSUE THREAD

**Issue by ChessMan3** [syzygy1/Cfish#33]
Hello!
On a Windows machines with hyper-threading enabled, Cfish is playing bad in 1-core testing with concurrency more than number of real cores.

-----------------
 **Test on server with 2 CPU (total 12 cores/24 threads):** 

Games Completed = 17530 of 100000 (Avg game length = 30.432 sec)
Settings = RR/32MB/Book/10000ms+100ms/M 1000cp for 12 moves, D 120 moves/PGN:C:\Users\Burcontovk\Desktop\Lbbooks\Mybookbullet.pgn(299)
Time = 35861 sec elapsed, 168710 sec remaining
 **1.  CFish_x64_281217_NUMA_popcnt_720mingw	8135.0/17530	2375-3635-11520** 
(L: m=755 t=34 i=0 a=2846)	(D: r=8358 i=1593 f=405 s=94 a=1070)	(tpm=235.4 d=18.00 nps=1117936)

 **2.  stockfish_281217_x64_popcnt	9395.0/17530	3635-2375-11520**
(L: m=457 t=0 i=0 a=1918)	(D: r=8358 i=1593 f=405 s=94 a=1070)	(tpm=232.2 d=18.64 nps=1209669)

Concurrency 15 or more.
PGN with games: http://www75.zippyshare.com/v/LEYXO33P/file.html 

--------------------
 **Test on i7 6700HQ  (4 cores/8 threads):**

i7 6700HQ Quad @ 3.5 | OS: Win10x64-16GB | Gui CuteChess 1.0.0 
TopGM_2move.pgn| Hash=16MB | HT~On | Ponder=No | TB=No
Cores=1 | Concurrency 7 | Elo Ordo 1.26 | Time: 10"+.1" (64")

    PLAYER                         :  RATING  ERROR  PLAYED   (%)    W     D    L  D(%)  CFS(%)
   1 CFish_x64_281217_NUMA_popcnt_720mingw    :    3200      4    2200  50.0  325  1552  323  70.5      53
   2 stockfish_281217_x64_popcnt              :    3200      4    2200  50.0  323  1552  325  70.5     ---

-----------------
**Test on my AMD FX-8150 (8cores/8 threads):**

Win 10, Cutechess 0.9.4, TC: 10+0.1, hash 16 MB, 1 core, concurrency 7

Score of CFish_x64_281217_NUMA_popcnt_720mingw vs stockfish_281217_x64_popcnt:
 1883 - 1292 - 6825 [0.530]
ELO difference: 20.56 +/- 3.82

10000 of 10000 games finished.

**Both engines have same bench**

**Comment by CoffeeOne** [comment]
Hi chessman,
About 1) Both Stockfish and CFish bind the threads 2 nodes on multi-node Windows machines. This is applicable here, you did test with a 2 node machine. The difference is that Stockfish has a logic to disable that binding (let the OS decide) with less than 8 threads, Cfish does not have that logic as far as I know.

That means all 1-thread-tasks reside on the same CPU for CFish, that means with concurrency 15, 15 CFish threads are running on one six-core/12 thread CPU, that is not good. Stockfish will spread it's threads randomly over the 2 CPUs, that's a big advantage.

About 2) and 3) I don't know what the problem is here. 3) looks OK, but no idea why at run 2) CFish scores only 50%. But you should run exactly the same test (same opening book and same number of games), you ran only 3200 games in run 2.

**Comment by ChessMan3** [comment]
@CoffeeOne 
Unfortunately, I do not have a processor other than FX-8150. Therefore, I can not verify this thoroughly.
I asked Intel owners with HT support to help me with the tests, but for now it's vain.

**Comment by syzygy1** [comment]
I guess @CoffeeOne has correctly identified the problem. The solution is to set the NUMA uci option to "off" (without the quotes).

Note that the NUMA uci option only shows up if the Cfish is running on a NUMA machine.

**Comment by ChessMan3** [comment]
On systems without NUMA (like i7 6700HQ), this option is not displayed, so it can not be disabled. Could it be that Cfish in a single-core mode tries to use only physical cores, ignoring logical ones?

The owner of the i7 6700HQ said that compilation with NUMA disabled (in the makefile) is even worse, though there were very few games.

**Comment by syzygy1** [comment]
If it is not displayed, NUMA is disabled and Cfish leaves everything to the OS (like SF).
The i7 6700 HQ run is probably just unlucky.
In any event, there is nothing in Cfish that could affect HT performance.

**Comment by ChessMan3** [comment]
@CoffeeOne , @syzygy1 
You were both right, "there is nothing in Cfish that could affect HT performance"

Some peoples from http://immortalchess.net helped me with the testing.

I compared the ratio of the speed of CFish and Stockfish with different number of parallel games in Little Blitzer

**марк захаров test run:**

Intel Xeon x5650

Games Completed = 21 of 200
1 core
CFish_x64_2812_N_pop_720m nps=1889223
stockfish_281217_x64_popcnt nps=1501703
ratio = 1889223/1501703 = 1,258053689710948

Games Completed = 35 of 200
ratio 1,192376387750959

Games Completed = 56 of 200
ratio 1,154414419581349

**new test**
Games Completed = 200 of 200
**23 threads (2 CPU * 12 threads -1)**
1313288/1289647 = 1,018331372848539 

**A large speed drop for CFish.**

==================

**Nikola test run:**

Core i7 7820x

8 CPU Actual:1 HT-OFF
ratio 1,10985052201394

8 CPU Actual:8 HT-OFF
ratio 1,128085113325514

16 CPU Actual:1 HT-ON
ratio 1,105650565472697

16 CPU Actual:8 HT-ON
ratio 1,114605436794911

16 CPU Actual:15 HT-ON
ratio 1,138956691936937

16 CPU Actual:16 HT-ON
ratio 1,140256060677636

**For Cfish HT is even better than for Stockfish in this test.**

==============

**andrzejka test run**

Core i7 3770k

Games Completed = 27 of 200
1 core
ratio 1,326617275389092

Games Completed = 90 of 200
3 cores (i think)
ratio 1,312884451834339


Games Completed = 200 of 200
7 threads (i think)
ratio 1,309628920925441

**A little speed drop for CFish.**

============

I hope my conclusions are correct.

**Comment by syzygy1** [comment]
The ratios are Cfish nps : SF nps (both running with the same number of threads)?

**Comment by ChessMan3** [comment]
Yes. Only changes is concurrency (from run to run)

**Comment by ChessMan3** [comment]
results for my FX-8150 (8cores/8 threads):

c1
Games Completed = 8 of 500 (Avg game length = 15.778 sec)
Settings = RR/16MB/10000ms+10ms/M 10000cp for 500 moves, D 5000 moves/PGN:E:\Bases\1LittleBlitzer-2.75\test1.pgn(100)
Time = 130 sec elapsed, 8016 sec remaining
 1.  CFish_x64_281217_NUMA_popcnt_720mingw	3.5/8	0-1-7  	(L: m=1 t=0 i=0 a=0)	(D: r=5 i=2 f=0 s=0 a=0)	(tpm=164.0 d=17.34 nps=1865043)
 2.  stockfish_281217_x64_popcnt	4.5/8	1-0-7  	(L: m=0 t=0 i=0 a=0)	(D: r=5 i=2 f=0 s=0 a=0)	(tpm=161.3 d=18.38 nps=1574239)  
**ratio 1,184726715574954**

c4
Games Completed = 27 of 500 (Avg game length = 16.630 sec)
Settings = RR/16MB/10000ms+10ms/M 10000cp for 500 moves, D 5000 moves/PGN:E:\Bases\1LittleBlitzer-2.75\test1.pgn(100)
Time = 229 sec elapsed, 4014 sec remaining
 1.  CFish_x64_281217_NUMA_popcnt_720mingw	14.5/27	6-4-17  	(L: m=4 t=0 i=0 a=0)	(D: r=15 i=2 f=0 s=0 a=0)	(tpm=136.8 d=18.99 nps=1772222)
 2.  stockfish_281217_x64_popcnt	12.5/27	4-6-17  	(L: m=6 t=0 i=0 a=0)	(D: r=15 i=2 f=0 s=0 a=0)	(tpm=137.6 d=17.96 nps=1437323) 
**ratio 1,233001907017421**


c8
Games Completed = 89 of 500 (Avg game length = 17.775 sec)
Settings = RR/16MB/10000ms+10ms/M 10000cp for 500 moves, D 5000 moves/PGN:E:\Bases\1LittleBlitzer-2.75\test1.pgn(100)
Time = 387 sec elapsed, 1789 sec remaining
 1.  CFish_x64_281217_NUMA_popcnt_720mingw	49.5/89	22-12-55  	(L: m=12 t=0 i=0 a=0)	(D: r=44 i=8 f=2 s=1 a=0)	(tpm=132.0 d=17.78 nps=1601290)
 2.  stockfish_281217_x64_popcnt	39.5/89	12-22-55  	(L: m=22 t=0 i=0 a=0)	(D: r=44 i=8 f=2 s=1 a=0)	(tpm=134.4 d=16.69 nps=1299014) 
**ratio 1,232696491338815**

**Comment by ChessMan3** [comment]
@syzygy1 
 in all tests they run only on 1 core, with different numbers of concurrency

**Comment by ChessMan3** [comment]
Same PC as in 1-st post (Dual Xeon e5645 2*12 threads), Cfish compiled with **NUMA=no** in makefile

1 core, concurrency 24

Games Completed = 33693 of 100000 (Avg game length = 30.412 sec)
Settings = RR/32MB/Book/10000ms+100ms/M 1000cp for 12 moves, D 120 moves/PGN:C:\Users\Burcontovk\Desktop\Lbbooks\Mybookbullet.pgn(299)
Time = 43897 sec elapsed, 86388 sec remaining
 1.  CFish_x64_281217_popcnt_720mingw	17511.0/33693	6375-5046-22272  	(L: m=988 t=2 i=0 a=4056)	(D: r=16134 i=3071 f=811 s=169 a=2087)	(tpm=233.5 d=18.33 nps=1122763)
 2.  stockfish_281217_x64_popcnt	16182.0/33693	5046-6375-22272  	(L: m=1367 t=2 i=0 a=5006)	(D: r=16134 i=3071 f=811 s=169 a=2087)	(tpm=233.3 d=17.89 nps=953712)

Games: http://rgho.st/6xGztMD9P
