### ISSUE TITLE
compiler warnings

### ISSUE THREAD

**Issue by Saugstrahler** [syzygy1/Cfish#38]
I get a lot of warnings for various files...all same message:

benchmark.c:209:21: warning: ISO C does not support the 'I' ms_printf length modifier [-Wformat=]

and

benchmark.c:223:19: warning: ISO C does not support the 'I64' ms_printf length modifier [-Wformat=]

**Comment by syzygy1** [comment]
Did you update your MSYS installation after https://github.com/syzygy1/Cfish/issues/29 ?

It seems MSYS/MinGW doesn't know what it wants.

**Comment by syzygy1** [comment]
Ah, I thought these warning were caused by the changes I made then, but that's not true.

**Comment by syzygy1** [comment]
The problem is that fixing this by using the %z modifier for both Linux and Windows breaks cross-compilation for Windows with MinGW on Linux. (I could just cast the size_t values to int and use %d to work around the problem, but there is an annoying inconsistency in MinGW.)

**Comment by syzygy1** [comment]
Adding a compilation flag may have done the trick. At least it works now for MinGW on Linux.
https://github.com/syzygy1/Cfish/commit/1e615f5069655a14da0b13fd8b5b72b7f4bc94b4

**Comment by Saugstrahler** [comment]
nope, it's not fixed and now I get additional warnings.....

a) benchmark.c:209:35: warning: unknown conversion type character 'z' in format [-Wformat=]
     fprintf(stderr, "\nPosition: %zu/%zu\n", ++j, num_fens - num_opts);

b) benchmark.c:209:21: warning: too many arguments for format [-Wformat-extra-args]
     fprintf(stderr, "\nPosition: %zu/%zu\n", ++j, num_fens - num_opts);

c) benchmark.c:223:19: warning: ISO C does not support the 'I64' ms_printf length modifier [-Wformat=]

**Comment by syzygy1** [comment]
Do you get those errors with COMP=mingw or with the (default) COMP=gcc?

**Comment by Saugstrahler** [comment]
COMP=gcc (7.3.0)
I get warnings in:
benchmark.c
position.c
search.c
tt.c

**Comment by syzygy1** [comment]
OK, please try again with the latest commit.

**Comment by Saugstrahler** [comment]
works fine, no warnings anymore........but final executable increased size from 196k to 221k

**Comment by syzygy1** [comment]
Yes, because it now links in a standard-compliant version of printf.
Without it you need to give %I, but then the compiler complains.
