### ISSUE TITLE
With SyzygyPath included compile crashes

### ISSUE THREAD

**Issue by ik4u** [syzygy1/Cfish#4]
With SyzygyPath included in the source compile crashes during PGOBENCH at position 31/37
![crash](https://cloud.githubusercontent.com/assets/5150233/18553789/ed0ded32-7b72-11e6-8747-919fb3805e38.JPG)

**Comment by syzygy1** [comment]
How do you include a SyzygyPath in the PGOBENCH?

**Comment by syzygy1** [comment]
Found the bug and fixed it. Thanks for reporting!

**Comment by ik4u** [comment]
How do you include a SyzygyPath in the PGOBENCH?
By simply added the path in the source before compile.

Thank you for the fix and keep up the good work
cheers
