### ISSUE TITLE
** Not an issue **

### ISSUE THREAD

**Issue by glennsamuel32** [syzygy1/Cfish#42]
Sorry for posting here :)

Is there a way to pre-set the Syzygy options during compilation ?

Like path, probe depth and probe limit ?

Thanks...

**Comment by syzygy1** [comment]
Yes, you can edit ucioption.c.
https://github.com/syzygy1/Cfish/blob/9b9647d7d5e148d4812f93e79979484f3fc23ddd/src/ucioption.c#L106-L130
For SPIN and CHECK options the first value is the default value.
For STRING options you have to change the "&lt;empty&gt;" string into "C:/syzygy/345;C/syzygy/6", for example.

**Comment by glennsamuel32** [comment]
Thanks a lot !!

**Comment by glennsamuel32** [comment]
The compilation showed this but it compiled successfully...
ucioption.c:121:45: warning: non-ISO-standard escape sequence, '\e'
   { "SyzygyPath", OPT_TYPE_STRING, 0, 0, 0, "<X:\egtb>", on_tb_path, 0, NULL },
                                             ^~~~~~~~~~~
But the exe shows this...
option name SyzygyPath type string default <X:gtb>

[https://s20.postimg.org/qyl8vpawd/Capture.jpg](url)

**Comment by glennsamuel32** [comment]
Sorry, it works fine...
I didn't see the / instead of \ 
Thanks again !!

**Comment by syzygy1** [comment]
If you prefer \ you have to type \\

**Comment by syzygy1** [comment]
Hmm that should have been double backslashes: `\\`
