### ISSUE TITLE
Strange response to uci stop command

### ISSUE THREAD

**Issue by LouisZulli** [syzygy1/Cfish#45]
20 threads, 32 GB hash, 6-man tables:

info depth 66 seldepth 94 multipv 1 score cp -836 nodes 4603616284472 nps 53102871 hashfull 999 tbhits 31002107665 time 86692417 pv a7a8 a3a2 a8a5 e6e7 a5a8 e7d6 g2f3 g6g5 f3e2 d6e6 a8e8 e6d7 e8a8 g5h4 g3h4 f6f5 e2f3 d7c6 a8c8 c6b6 c8b8 b6c7 b8a8 c7b7 a8a3 b7c6 d2c4 c5d3 c4e3 d3c1 a3a8 a1b1 e3c2 b1b2 c2e3 b2b8 a8a5 b8b1 e3c2 b1b2 c2a1 c6b6 a5a8 b2b1 a1c2 b6c5 a8c8 c5d5 c8a8 b1b2 c2e3 d5c6 a8a3 c6c5 a3a5 b2b5 a5a8 b5b1 e3c2 b1b2 c2e1 c5c4 f3f4 b2b1 a8c8 c4b3 c8b8 b3c3 b8c8 c3b2 c8c2 b2b3 c2a2 c1a2 e1f3 b3b4 f4f5 b1d1 f5f4 b4c5 f4e3 a2b4 e3e2 d1b1 f3g5 b1b2 e2e1 b4d3 e1d1 d3f2 d1e1
info depth 67 currmove a7a8 currmovenumber 1
stop
info depth 67 seldepth 94 multipv 1 score cp -836 nodes 4939319895868 nps 53190320 hashfull 999 tbhits 33894567834 time 92861255 pv a7a8 a3a2 a8a5 e6e7 a5a8 e7d6 g2f3 g6g5 f3e2 d6e6 a8e8 e6d7 e8a8 g5h4 g3h4 f6f5 e2f3 d7c6 a8c8 c6b6 c8b8 b6c7 b8a8 c7b7 a8a3 b7c6 d2c4 c5d3 c4e3 d3c1 a3a8 a1b1 e3c2 b1b2 c2e3 b2b8 a8a5 b8b1 e3c2 b1b2 c2a1 c6b6 a5a8 b2b1 a1c2 b6c5 a8c8 c5d5 c8a8 b1b2 c2e3 d5c6 a8a3 c6c5 a3a5 b2b5 a5a8 b5b1 e3c2 b1b2 c2e1 c5c4 f3f4 b2b1 a8c8 c4b3 c8b8 b3c3 b8c8 c3b2 c8c2 b2b3 c2a2 c1a2 e1f3 b3b4 f4f5 b1d1 f5f4 b4c5 f4e3 a2b4 e3e2 d1b1 f3g5 b1b2 e2e1 b4d3 e1d1 d3f2 d1e1
info depth 69 seldepth 129 multipv 1 score cp -265 nodes 4939319895868 nps 53190319 hashfull 999 tbhits 33894567834 time 92861256 pv d2c4 a3a2 c4e3 c5d3 a7a6 e6d7 e3d5 d3e1 g2f1 f6f5 f1e2 e1d3 e2d3 a1d1 d3e3 a2a1q a6a1 d1a1 d5f4 a1a6 e3d2 d7e7 d2e2 a6a2 e2f3 a2a3 f3g2 a3a6 f4d5 e7f8 g2f3 a6a5 d5f4 a5a3 f3e2 f8f7 f4h3 f7f6 e2f1 a3a4 f1e2 a4e4 e2f3 e4b4 f3g2 f6e5 g2f3 b4c4 h3f4 c4c3 f3g2 c3c6 g2f3 c6d6 f3e3 d6b6 e3f3 b6a6 f3g2 e5e4 f4e2 a6f6 e2c3 e4d3 c3d5 f6d6 d5f4 d3e4 f4e2 d6a6 e2f4 a6b6 f4e2 b6d6 e2f4 d6f6 f4e2 e4e5 e2f4 f6d6 g2f3 d6c6 f3g2 e5d4
bestmove d2c4 ponder a3a2

**Comment by syzygy1** [comment]
The "depth 69" line comes from another thread than the main thread. Is this different than what Stockfish does? (Perhaps the "depth 67" line after "stop" should have been suppressed.)

**Comment by LouisZulli** [comment]
Not sure what Stockfish does currently. But having observed engine 
outputs for many years, this one simply *seemed* strange.

**Comment by syzygy1** [comment]
This is SF behaviour, so closing.
