### ISSUE TITLE
Can probe depth 0 do probing in qsearch

### ISSUE THREAD

**Issue by jjoshua2** [syzygy1/Cfish#46]
With nvme drives like 960 pro and 900p optane being orders of magnitude faster than previous SSDs, and even 64/128GB of ram to cache most of the 6 pieces not being that expensive I would like the option to test strength of doing TB proving in qsearch since I think now it could give a strength gain when it couldn't before, and see how much NPS slowdown different storage mediums have.
I imagine the last time this was tested was at best with SATA3 SSD? Thanks!

**Comment by syzygy1** [comment]
Maybe at some point in the future for important tables where the evaluation is likely to go wrong. In general, probing in the qsearch will be too expensive.
