### ISSUE TITLE
Large Pages are not that large

### ISSUE THREAD

**Issue by Krgp** [syzygy1/Cfish#48]
Cfish https://github.com/syzygy1/Cfish/commit/404b260b0d9ba6c96dcdaf781a41219819618065 bench

This is what I (Intel i7 4790K, Windows 10 Pro 64 bit) got

Base = No LP

Test = Large Pages

Results for 20 tests for each version:

            Base      Test      Diff      
    Mean    2833006   2826956   6050      
    StDev   20152     23290     33079     

p-value: 0.427
speedup: -0.002

**Comment by ChessMan3** [comment]
Small hash size.
With hash 4096 MB, LP is about ~10% faster.

My tests on Immortalchess:
http://immortalchess.net/forum/showpost.php?p=812787&postcount=2069

**Comment by Krgp** [comment]
Build Tester: 1.4.7.0
Windows 10 Pro (Version 10.0, Build 0, 64-bit Edition)
Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
SafeMode: No 
Running In VM: No 
HyperThreading Enabled: Yes
CPU Warmup: Yes
Command Line: bench 4096 1 14  default depth
Tests per Build: 10
ANOVA: n/a

                Engine# (NPS)                     Speedup     Sp     Conf. 99.5%  S.S.
2  (3,228,308.6   ) ---> 1  (3,214,353.2   ) --->  0.434%  12,683.2     No        No 

(Engine 1 = Large Pages and Engine 2 = No large pages)

Even with 4096 MB it's slower for me.

@ChessMan3  your tests on immortalchess appear to be in respect of other build (https://github.com/syzygy1/Cfish/commit/842bdcaed16daed1df77d6a0b15ee727692de899)

**Comment by ChessMan3** [comment]
Yes you are right LP does not work well
https://postimg.org/image/af1mdrgd9/

============
Cfish 100318 64 POPCNT by Syzygy based on Stockfish
bench
info string Transposition table allocated using large pages.

Position: 1/42

**Comment by Krgp** [comment]
Perhaps this https://github.com/syzygy1/Cfish/commit/5e6c94af08f8377599fbe49a225c9c086cc9dca8 breaks LP.

**Comment by gogamoga1** [comment]
on my PC it seems to work fine
start pos for 1 min
Cfish with LP - 9896 kN/s
SF  with LP    - 9368 kN/s

**Comment by ChessMan3** [comment]
@gogamoga1
Try Cfish without LP. Same speed?
And hash size?

**Comment by gogamoga1** [comment]
@ChessMan3 
9540 kN/s, 1.5gb hash

**Comment by syzygy1** [comment]
Do you get a speedup from LP on Windows with cfish_9?
https://github.com/syzygy1/Cfish/releases/tag/cfish_9

**Comment by syzygy1** [comment]
And if you run a recent cfish.exe from the command line, does it tell you that LP works (on Windows)?

Something like this:

setoption name Hash value 4096
isready
info string Transposition table allocated using large pages.
readyok

I don't see how the TT initialisation change can affect LP on Windows.

**Comment by Krgp** [comment]
I had tried. All i could gather is at present LP is broken. One needs to compile each commit and locate the culprit ... I tried a couple (https://github.com/syzygy1/Cfish/commit/5e6c94af08f8377599fbe49a225c9c086cc9dca8) and (https://github.com/syzygy1/Cfish/commit/513ec184435efb6d3934ee00d6c805949824d653)   ... however this https://github.com/syzygy1/Cfish/issues/40 issue makes it to locate the exact culprit.

**Comment by ChessMan3** [comment]
I tried LP in GUI - looks like works fine.
4 GB hash, 1 core
https://postimg.org/gallery/3hg5gvumm/

**Comment by ChessMan3** [comment]
I retest Cfish 050118 and 100318 after reboot and LP is working for both, but for 050118 is a bit better (noise?)
https://postimg.org/image/ddhvt3fel/

**Comment by Krgp** [comment]
I always do LP tests by re-booting ... for me no difference whatever ... i.e. LP doesn't work at my PC for current Cfish master. Whereas it works fine for Cf 9 ...

**Comment by syzygy1** [comment]
@Krgp 
Do you get the message that the TT was allocated using large pages? (And do you not get that message when you are testing without LP?)

**Comment by Krgp** [comment]
@syzygy1 
Yes. when i start Cfish as administrator and set hash and parse isready (_if i dont set hash i get no message, but i believe default ucioption is 1_) i get the message that the TT was allocated using large pages. (And I do not get that message when I am testing without LP - i.e. when i start Cfish as user (just click exe without running as administrator)

**Comment by Krgp** [comment]
@syzygy1 
I also do not get any speed up during actual game play with LP on. Checked in 'Little Blitzer' and 'Fritz 15' GUI which keep track and report current nps.

**Comment by Krgp** [comment]
@syzygy1 
If i get time i will build each commit from Cf9, do tests and report here ...

**Comment by Krgp** [comment]
@syzygy1 
One last thing, I build with no NUMA as i have a single socket system. But i fail to see how NUMA on/off can affect LP ...

**Comment by syzygy1** [comment]
There is no need to leave out NUMA on a single socket system (except perhaps on Linux to remove a dependency on libnuma), but it should not make a difference for LP.

**Comment by Krgp** [comment]
@syzygy1 
Well after a cold boot, i started current Cfish master as a user (NOT running as administrator).
On 'isready', i get (without setting any hash value)

Cfish 100318 64 BMI2 by Syzygy based on Stockfish
isready
info string Transposition table allocated using large pages.
readyok  

This should not happen. It seems this is reproducible. (just start Cfish.exe and parse isready)
Can someone else please confirm ?

**Comment by Krgp** [comment]
Well this (info string Transposition table allocated using large pages.) happens to even Cfish9 on 'isready', even when started as user (NOT running as administrator). Perhaps to all Cfish. 

Can someone on Windows please confirm?

**Comment by syzygy1** [comment]
Yes that should happen. LP is on by default.

**Comment by Krgp** [comment]
For large pages to be effective on Windows, It's my understanding that an exe must be run as Administrator. 

In case of SF (with lp)/ Brainfish or even Houdini, LP are not operative if they are not run as Administrator.

And just to quote you a few posts above "_Do you get the message that the TT was allocated using large pages? (And do you not get that message when you are testing without LP?)_" made me believe that LP should not be operative if not run as Administrator.

Anyway, once you say that should happen, ... then i don't have any further say in the matter. (Honestly)

Thanks

**Comment by ChessMan3** [comment]
I never run Cfish as administrator to enable LP. I enable LP in OS for current user.

**Comment by syzygy1** [comment]
If you type "uci" in Cfish, you get the list of options and their default values. LP's default value is true. So if LP are available (which on Windows depend on the version of Windows and user privileges), Cfish will try to use them unless the user has set the option to false.

If Cfish detects on start-up that large pages are not supported, it will not show the LP option.

If on your system large pages only work for the Administrator, the Administrator should see considerably larger nps than other users when using a large hash. The difference is large enough that a single bench should easily tell the difference. (Well, two benches.)

**Comment by syzygy1** [comment]
And the Administrator should see the same nps as other users if you type "setoption name LargePages value false" before letting the engine run.

**Comment by Krgp** [comment]
@syzygy1 
Thanks. My system is configured in such a way that i login only as admin. LP are true by default. So Cfish always say that LP are on.

However, one thing is certain, whenever i run Cfish as administrator (right click run as administrator) i get low nps for current master. In case of Cfish 9, whenever i run as administrator, I get expected higher nps.

Thanks again.

**Comment by syzygy1** [comment]
Different versions of cfish and stockfish have different nps. What you should compare is nps with LP set to true and nps with LP set to false, otherwise same version and settings.  Ideally from a dos prompt, so you can see if LP allocation was successful.
