### ISSUE TITLE
Simplify KBPKB endgame with opposite bishops

### ISSUE THREAD

**Issue by ChessMan3** [syzygy1/Cfish#50]
Hello!
You forgot something: 
https://github.com/official-stockfish/Stockfish/commit/d9cac9a41492c3e54f3bb471606ec3a922a8ea0f#diff-e88e03386a215910d76a232ae9603922L803

"-"            // Endgame with opposite-colored bishops and no other pieces (ignoring pawns)
" -"            // is almost a draw, in case of KBP vs KB, it is even more a draw.
 "+ "           // Endgame with opposite-colored bishops and no other pieces is almost a draw
              if (   pos.non_pawn_material(WHITE) == BishopValueMg
                  && pos.non_pawn_material(BLACK) == BishopValueMg)
 "-"                sf = more_than_one(pos.pieces(PAWN)) ? 31 : 9;
 "+"                sf = 31;

**Comment by syzygy1** [comment]
It seems I did! Thanks!!
