### ISSUE TITLE
Fix Cfish for android

### ISSUE THREAD

**Issue by Alexei1981** [syzygy1/Cfish#51]
Hello, Mr. De Man.I do cfish compilations on Android and have to write code all the time.
You could add the following changes to the following file misc.h and misc.c:

misc.h
```
#define IO_UNLOCK pthread_mutex_unlock(&io_mutex)
#else

extern HANDLE io_mutex;
#define IO_LOCK WaitForSingleObject(io_mutex, INFINITE)
#define IO_UNLOCK ReleaseMutex(io_mutex)
int large_pages_supported(void);
extern size_t large_page_minimum;
#endif
#if defined __WIN32__||defined __ANDROID__
ssize_t getline(char **lineptr, size_t *n, FILE *stream);
#endif
```

misc.c
```
#if defined __WIN32__||defined __ANDROID__
ssize_t getline(char **lineptr, size_t *n, FILE *stream)
{
  if (*n == 0)
    *lineptr = malloc(*n = 100);
```

Also in the bitbase file.c 
when compiling the engine on Android using the compiler 4.9 + there is the following error: conflicting types with variable [index] .I fixed it this way [_index] (added an underscore).
There, this variable is used seven times.
Can this be fixed?
Thanks.

**Comment by syzygy1** [comment]
Hi Alexei. It should be fixed now.
If there are any other problems, let me now.

**Comment by Alexei1981** [comment]
Thanks.
