### ISSUE TITLE
Fix getline function

### ISSUE THREAD

**Issue by Alexei1981** [syzygy1/Cfish#52]
Hi mr. De Man.I have at compile for android climbs here is a warning:

misc.c: In function 'getline':
misc.c:125:29: warning: comparison is always true due to limited range of data type [-Wtype-limits]
 
```
while ((c = getc(stream)) != EOF) {                               
                                           ^~
```   

This warning appears in both gcc-7.2 and gcc-4.9+.      
On other platforms, there are no warnings because of the default char sign. It is unsigned on ARM by default.

**Comment by syzygy1** [comment]
Thanks, I will fix it this evening. I think the correct solution is to make c an int.

**Comment by Alexei1981** [comment]
@syzygy1 
Yeah, I thought about that too.

**Comment by syzygy1** [comment]
Should be fixed now.
