### ISSUE TITLE
Strange evaluation 

### ISSUE THREAD

**Issue by ChessMan3** [syzygy1/Cfish#53]
When using contempt White/Black in analysis i have unexpectable evaluation:

8/1Bb5/p4k2/1p4p1/1P5P/P3P1P1/5K2/8 b - - 0 46

https://postimg.cc/image/pu943vfez/
https://postimg.cc/image/cq3jrmicr/

Stockfish have not this issue.

**Comment by syzygy1** [comment]
It is fixed now. Thanks for reporting!

**Comment by ChessMan3** [comment]
@syzygy1 
Thank you! How about "both" option in contempt combo box, like in Stockfish?
