### ISSUE TITLE
time issuue

### ISSUE THREAD

**Issue by 867701** [syzygy1/Cfish#55]
Cfish 2018-04-29 64 popc chess engine losing games on time management, how can i adjust to play quicker, and not ponder on certain moves

**Comment by syzygy1** [comment]
It is supposed to behave identical to SF in this respect, and there were no recent changes.

**Comment by 867701** [comment]
adjusted overhead to 60, engine seems to play better 
regards 


-----Original Message-----

**Comment by ChessMan3** [comment]
@867701  which GUI? Did you use 6-men TB's?

**Comment by 867701** [comment]
Fritz GUI and some of the 6-men tablebase were used


-----Original Message-----

**Comment by 867701** [comment]
at the time of problems,i was using windows 10 64bit, i have since gone back to windows 7 ultimate 64bit



-----Original Message-----

**Comment by guru64** [comment]
I have the same problem. It seems that Cfish moves pieces slower than Stockfish.

**Comment by syzygy1** [comment]
There have been many changes to time management in the meantime. Please create a new issue if there are still problems.
