### ISSUE TITLE
Issue with Infinity Chess at the end of an engine-engine game

### ISSUE THREAD

**Issue by CoffeeOne** [syzygy1/Cfish#57]
Hi,
There is an issue when playing engine games on Infinitychess (Windows GUI).
At the end of a game when the result is not a mate or stalemate, for example game was ruled to draw by an Administrator, the game is over, but there is a message "Close Window" for 10 seconds, and the time counts down to 0. I can see in the game window that engine is still running, I see variants being calculated. This is the case for all engines stockfish, houdini, komodo, cfish.
The point is here that cfish sometimes crashes at this point (program caused an exception)
This is weird, because the game is already over :)
I asked on Infinity chess if there is a possibility to see the uci communication, but got no answer.

Is there an option in Cfish to check the uci communications, there must a sequence which causes a problem in Cfish.

With Houdini, there is the option to log the uci communication, I tried it to see what commands are sent by the GUI:

I see there a sequence at the end of a game (which was not mate), so this 10 seconds thing comes:
```
<< info currmove f3f4 currmovenumber 1
<< info time 5001 nodes 790677363 nps 158103000 tbhits 19 hashfull 284
<< info time 6001 nodes 949254033 nps 158182000 tbhits 19 hashfull 285
<< info time 7002 nodes 1107600164 nps 158183000 tbhits 19 hashfull 285
<< info time 8003 nodes 1265205018 nps 158091000 tbhits 19 hashfull 285
<< info time 9001 nodes 1422403286 nps 158027000 tbhits 19 hashfull 285
<< info time 10000 nodes 1579054283 nps 157905000 tbhits 19 hashfull 287
<< info multipv 1 depth 39 seldepth 63 score cp 0 time 10305 nodes 1627233218 nps 157907000 tbhits 19 hashfull 287 pv f3f4 e5g5 b7b1 f8f7 b1b7 f7f8
<< info currmove f3f2 currmovenumber 2
<< info time 11000 nodes 1736066350 nps 157824000 tbhits 19 hashfull 288
>> stop
>> stop
>> quit
<< bestmove f3f4 ponder e5g5
```
So at the end, IC GUI sends 2 times stop and then quit (?)

It would be great, if we could get rid of this problem.
Of course it's not a problem for the already ended game, but usually in the next game (playing in a tour), the engine does not move.

**Comment by ChessMan3** [comment]
@CoffeeOne  
Did you use a bin book at that moment?

**Comment by CoffeeOne** [comment]
Yes

**Comment by ChessMan3** [comment]
Same problem happen in fritz GUI, but only when used BIN book. With ctg books this issue not happen (not detected).

**Comment by syzygy1** [comment]
@ChessMan3
That problem seems to be caused by a recent change I made (which I will fix in a moment). I suspect it is not the reason for @CoffeeOne's problem.

I don't know what could cause @CoffeeOne's problem.

**Comment by CoffeeOne** [comment]
@syzygy1 I found out a little bit.
The problem happens only in Infinity Chess tournaments, never in normal engine-engine games. IC chess admins have the possiblity to "rule" a game. They do it, when they think a game is dead draw, for example or it is won for one side, but the weaker side does not resign.
So something bad happens when the game is "forcefully" terminated.
I hope, I can find out the sequence of UCI commands sent by IC GUI.

**Comment by syzygy1** [comment]
Can you get the engine to crash from the command line by typing quit?
Maybe it has to do with TBs being loaded.

**Comment by CoffeeOne** [comment]
I tried in the following way:
setoption name SyzygyPath value D:\syzygy
setoption name Threads value 40
setoption name Hash value 16384
position fen 6k1/5p2/6p1/8/7p/8/6PP/6K1 b - - 0 0
go infinite

gives millions of TB hits very quickly
and then after some seconds
quit

always worked, no problem.

**Comment by CoffeeOne** [comment]
Another remark: I try to reproduce the issue again in an IC tour, and come back here.

**Comment by CoffeeOne** [comment]
@syzygy1 I cannot reproduce issues anymore at the end of a game in the Infinity Chess game. But there are still issues when IC GUI *starts* a game. Please note, that this is not only an Issue for Cfish, also for brainfish and asmfish, but NOT for offical stockfish. 

Remark. Most likely has nothing to do with the starting problems, but I noticed, that the following sequence (I did that for a pull request in stockfish, you know)
cat commands.txt - | time ./cfish

with a command file like
setoption name Threads value 8
setoption name Hash value 8192
ucinewgame
ucinewgame
ucinewgame
ucinewgame
ucinewgame
ucinewgame
ucinewgame
ucinewgame
ucinewgame
ucinewgame
quit
does not work with Cfish.  you get 0 seconds. It only works when you put an "isready" after setting the hash.

With official stockfish this sequence works (without an additional "isready").

**Comment by syzygy1** [comment]
ucinewgame now allocates the TT if that has not yet happened.

**Comment by CoffeeOne** [comment]
yes, you are right, that was different before, but now it's similar.

**Comment by CoffeeOne** [comment]
@syzygy1 Your last commit seems to solve those problems, I make more tests, but looks very good. 👍

**Comment by CoffeeOne** [comment]
The issue at the end of a game is still here. I closed the windows in Infinity Chess GUI (game was already ended, but I saw engine still calculating, see also above).
and then:
![grafik](https://user-images.githubusercontent.com/18207826/40934672-d67af054-6835-11e8-8754-761704bc90ab.png)

**Comment by CoffeeOne** [comment]
I don't think it is of any help, but here is the IC GUI log entry from today - highest line (which is highlighted).

![grafik](https://user-images.githubusercontent.com/18207826/40937481-153ceffa-683f-11e8-8919-35d3f0032370.png)

**Comment by CoffeeOne** [comment]
@syzygy1 Do you have an idea how to find the cause of the issue?
I had the issue yesterday 3 times in an IC tourney, it seems to happen more often with large hashes, I used 16GB hash and 80 threads.

**Comment by CoffeeOne** [comment]
Happened again today:
Crash when game was ended:

IC log file:
```
System.InvalidOperationException: No process is associated with this object.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_HasExited()
   at App.Model.UCIEngine.SendEngine(String command) UCI Process : System.Diagnostics.Process (cfish-2018-07-01) StandardInput : System.IO.StreamWriter IsReadyOk : True Game : App.Model.Game
```

**Comment by CoffeeOne** [comment]
I am now 99% sure, that it is all about Infinity Chess Gui. Their latest update made it better, but there are still problems (not only with Cfish, also with original stockfish).
The only issue that remains, is a possible debug feature for crappy GUIs: Log UCI communication (like Houdini's, stockfish does NOT have it). @syzygy1 Are you interested in that?
