### ISSUE TITLE
Compilation cpu options

### ISSUE THREAD

**Issue by darko999** [syzygy1/Cfish#6]
First, thank you for your time and for keeping up Cfish, I find it very solid and very good performance so far it's my favorite engine outhere. I do compile it myself using MinGW with no issues.
I have seen other ports that have options for avx bm1 bmi2 avx2 and so on that you can set on file before compiling. Is there any chance of that here in Cfish, what files should I look into to edit and make this options available? Thanks for your time and work.

**Comment by CoffeeOne** [comment]
Hello darko999 and Ronald,
I have an input relating CPU options.
@Ronald: You introduced for gcc -march=native to the compiler extra flags. According to my speed measurements (I did a lot of it), it gave me between 2.1 and 2.2% speed up (Windows, GCC6.2, AMD), which is a lot. Only problem is this option is not taken when doing profile-build! Maybe you can fix it, that march=native is taken into account for profile builds, too.

**Comment by syzygy1** [comment]
@CoffeeOne 
I have redone the Makefile a bit. Make profile-build now adds -march=native too.

The -march=native flag tells gcc to use all instructions supported by the CPU on which the compiler is running. It should therefore not be used for compiling an executable that should be capable of running also on other (older) CPUs. To disable -march=native, add "native=no" to the make command:
$ make profile-build native=no

@darko999 
The current Makefile is quite similar to that of default Stockfish. The main differences are that I have set some default values to what I use myself and that I have added "numa" and "native" options. Please have a look at this part of the Makefile:
https://github.com/syzygy1/Cfish/blob/master/src/Makefile#L43-L75
You can edit the default values under 2.1 yourself, or you can override them in the make command.
For example:
$ make profile-build pext=yes
Specifying ARCH=x86-64-bmi2 (for example) should also override some of the default values.

**Comment by darko999** [comment]
@syzygy1 Thank you for such informative reply, the new Makefile is great. Just compiled with no issues at all : D
