### ISSUE TITLE
Speedup with -static

### ISSUE THREAD

**Issue by ChessMan3** [syzygy1/Cfish#60]
Hello!
I noticed that with 
LDFLAGS += $(EXTRALDFLAGS) **-static** -lm
Under Linux Mint cinnamon 18.2, Cfish is faster about 4%

make profile-build ARCH=x86-64-modern lto=yes extra=no native=no numa=no -j 7  COMP=gcc

without strip, size ~1670 KB

chessman@CM-desktop ~ $ cd Pyshbench/pyshbench-master
chessman@CM-desktop ~/Pyshbench/pyshbench-master $ ./pyshbench /home/chessman/Pyshbench/pyshbench-master/cfish_pop_S /home/chessman/Pyshbench/pyshbench-master/cfish_pop 20
run base test diff
1 1800787 1705093 -95694
2 1801400 1720609 -80791
3 1795900 1712262 -83638
4 1805701 1726219 -79482
5 1789224 1717818 -71406
6 1808168 1715035 -93133
7 1810641 1722288 -88353
8 1794075 1717261 -76814
9 1792860 1723971 -68889
10 1802013 1718933 -83080
11 1798952 1725094 -73858
12 1812501 1723410 -89091
13 1795291 1711709 -83582
14 1804470 1721169 -83301
15 1788620 1723410 -65210
16 1803241 1711155 -92086
17 1797730 1720050 -77680
18 1789829 1721169 -68660
19 1795291 1716704 -78587
20 1792860 1722288 -70572

Result of 20 runs

base (.../cfish_pop_S) = 1798978 +/- 3076
test (...er/cfish_pop) = 1718782 +/- 2388
diff = -80195 +/- 3827

speedup = -0.0446
P(speedup > 0) = 0.0000

CPU: 4 x AMD FX(tm)-8150 Eight-Core Processor
Hyperthreading: on

**Comment by ChessMan3** [comment]
Actually for latest Cfish **-static** does not helps - no speedup.

My previous test was based on: "Fix crash when freeing the book."

Also it helps for "Updated to "Update search.cpp"."

chessman@CM-desktop ~/Pyshbench/pyshbench-master $ ./pyshbench /home/chessman/Pyshbench/pyshbench-master/cfish_Upd_search_static /home/chessman/Pyshbench/pyshbench-master/cfish_Upd_search 20
run       base       test     diff
  1    1808785    1708394  -100391
  2    1793467    1711155   -82312
  3    1808785    1706742  -102043
  4    1803241    1712262   -90979
  5    1804470    1706742   -97728
  6    1804470    1702352  -102118
  7    1810022    1708394  -101628
  8    1800175    1707293   -92882
  9    1805701    1708394   -97307
 10    1776020    1708394   -67626
 11    1804470    1705093   -99377
 12    1790434    1710050   -80384
 13    1804470    1707843   -96627
 14    1794075    1710050   -84025
 15    1811880    1703447  -108433
 16    1797730    1707843   -89887
 17    1800787    1706742   -94045
 18    1809403    1706192  -103211
 19    1798341    1707843   -90498
 20    1805085    1710602   -94483

Result of  20 runs

base (...earch_static) =    1801591  +/- 3669
test (...h_Upd_search) =    1707791  +/- 1066
diff                   =     -93799  +/- 4187

speedup        = -0.0521
P(speedup > 0) =  0.0000

CPU: 4 x AMD FX(tm)-8150 Eight-Core Processor
Hyperthreading: on

**Comment by CoffeeOne** [comment]
Latest is "Fix compilation under MingW. "
It compiles!

**Comment by ChessMan3** [comment]
Also -static not gives speedup for Cfish 9.
I'll try to find from wich patch it gives speedup.

@CoffeeOne  yes but: "Actually for latest Cfish -static does not helps - **no speedup**."

**Comment by syzygy1** [comment]
There is no reason why -static would give a speedup. Cfish does not spend time on executing code that it links to, whether statically or dynamically.

**Comment by ChessMan3** [comment]
**I found that first commit which have speedup with -static is:**

**Merge branch '7men'
syzygy1 committed 18 days ago**


chessman@CM-desktop ~/Pyshbench/pyshbench-master $ ./pyshbench /home/chessman/Pyshbench/pyshbench-master/cfish_merge_branch_7men_static /home/chessman/Pyshbench/pyshbench-master/cfish_merge_branch_7men 20
run       base       test     diff
  1    1856121    1754723  -101398
  2    1856763    1753576  -103187
  3    1852275    1751858  -100417
  4    1856763    1752430  -104333
  5    1859982    1752430  -107552
  6    1866454    1751858  -114596
  7    1859337    1753003  -106334
  8    1857406    1755297  -102109
  9    1836422    1731500  -104922
 10    1777988    1714346   -63642
 11    1849720    1735983  -113737
 12    1843364    1735422  -107942
 13    1855479    1742185  -113294
 14    1807950    1721498   -86452
 15    1822075    1722604   -99471
 16    1784494    1706167   -78327
 17    1829532    1741054   -88478
 18    1841465    1746155   -95310
 19    1840833    1737108  -103725
 20    1854837    1748432  -106405

Result of  20 runs

base (..._7men_static) =    1840463  +/- 10865
test (..._branch_7men) =    1740381  +/- 6407
diff                   =    -100082  +/- 5484

speedup        = -0.0544
P(speedup > 0) =  0.0000

CPU: 4 x AMD FX(tm)-8150 Eight-Core Processor
Hyperthreading: on 




**For commit "Updated to "Penalty for bad bishop with blocked central files".  …
syzygy1 committed 22 days ago"
-static does not gives speedup**

chessman@CM-desktop ~/Pyshbench/pyshbench-master $ ./pyshbench /home/chessman/Pyshbench/pyshbench-master/cfish_penalty_for_bad_bishop_static /home/chessman/Pyshbench/pyshbench-master/cfish_penalty_for_bad_bishop 20
run       base       test     diff
  1    1770359    1762217    -8142
  2    1768025    1765697    -2328
  3    1771529    1751286   -20243
  4    1765116    1763376    -1740
  5    1770359    1765116    -5243
  6    1768025    1759327    -8698
  7    1772114    1758750   -13364
  8    1772114    1764536    -7578
  9    1770944    1761060    -9884
 10    1769191    1758750   -10441
 11    1770359    1759904   -10455
 12    1768025    1764536    -3489
 13    1770944    1760482   -10462
 14    1763955    1761060    -2895
 15    1754723    1759904    +5181
 16    1769191    1763955    -5236
 17    1769775    1761060    -8715
 18    1766279    1762217    -4062
 19    1769775    1764536    -5239
 20    1769775    1766279    -3496

Result of  20 runs

base (...ishop_static) =    1768529  +/- 1713
test (...r_bad_bishop) =    1761702  +/- 1495
diff                   =      -6826  +/- 2298

speedup        = -0.0039
P(speedup > 0) =  0.0000

CPU: 4 x AMD FX(tm)-8150 Eight-Core Processor
Hyperthreading: on 

---------------------------------------
**All builds with:  make profile-build ARCH=x86-64-modern  native=no  numa=no lto=yes extra=no  -j 7 comp=gcc**

**numa=yes does not works for me with -static**


Binaries: https://www79.zippyshare.com/v/hQcqa0Ew/file.html

I hope -static gives speedup not only for me?
