### ISSUE TITLE
TB restructuring finished?

### ISSUE THREAD

**Issue by CoffeeOne** [syzygy1/Cfish#62]
Hi, not sure if it makes sense to report this error, there seems to be refactoring ongoing ....
I have at the moment (Windows MSYS2), compiled with COMP=mingw, same error with COMP=gcc
thread.c: In function 'threads_init':
thread.c:334:3: error: 'io_mutex' undeclared (first use in this function); did you mean 'do_move'?
   io_mutex = CreateMutex(NULL, FALSE, NULL);
   ^~~~~~~~
   do_move
thread.c:334:3: note: each undeclared identifier is reported only once for each function it appears in
thread.c: In function 'threads_exit':
thread.c:365:15: error: 'io_mutex' undeclared (first use in this function); did you mean 'do_move'?
   CloseHandle(io_mutex);
               ^~~~~~~~
               do_move
tbprobe.c: In function 'test_tb':
tbprobe.c:184:12: warning: passing argument 1 of 'close' makes integer from pointer without a cast [-Wint-conversion]
     close (fd);
            ^~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/unistd.h:10:0,
                 from misc.h:31,
                 from search.h:24,
                 from tbprobe.c:15:
C:/msys64/mingw64/x86_64-w64-mingw32/include/io.h:328:15: note: expected 'int' but argument is of type 'FD {aka void *}'
   int __cdecl close(int _FileHandle) __MINGW_ATTRIB_DEPRECATED_MSVC2005;
               ^~~~~

**Comment by syzygy1** [comment]
The master branch is supposed to compile, so thanks for reporting.
Should be fixed now, and I have now verified that compilation for Windows works.
