### ISSUE TITLE
Warnings when compiling x86-32

### ISSUE THREAD

**Issue by guru64** [syzygy1/Cfish#65]
misc.c: In function 'file_size':
misc.c:201:28: warning: left shift count >= width of type [-Wshift-count-overflow]
   return ((size_t)sizeHigh << 32) | (size_t)sizeLow;
                            ^~

thread.c: In function 'thread_create':
thread.c:152:41: warning: passing argument 3 of 'CreateThread' from incompatible pointer type [-Wincompatible-pointer-types]
   HANDLE thread = CreateThread(NULL, 0, thread_init, (void *)(intptr_t)idx,
                                         ^~~~~~~~~~~
In file included from C:/msys64/mingw32-810/i686-w64-mingw32/include/winbase.h:29,
                 from C:/msys64/mingw32-810/i686-w64-mingw32/include/windows.h:70,
                 from types.h:53,
                 from endgame.h:24,
                 from material.h:24,
                 from thread.c:23:
C:/msys64/mingw32-810/i686-w64-mingw32/include/processthreadsapi.h:163:127: note: expected 'LPTHREAD_START_ROUTINE' but argument is of type 'DWORD (*)(void *)' {aka 'long unsigned int (*)(void *)'}
   WINBASEAPI HANDLE WINAPI CreateThread (LPSECURITY_ATTRIBUTES lpThreadAttributes, SIZE_T dwStackSize, LPTHREAD_START_ROUTINE lpStartAddress, LPVOID lpParameter, DWORD dwCreationFlags, LPDWORD lpThreadId);
                                                                                                        ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~

**Comment by ChessMan3** [comment]
I also have warnings.

-----------------------------------------------------------------
**MinGW 7.3.0**

gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o movegen.o movegen.c
misc.c: In function 'file_size':
misc.c:201:28: warning: left shift count >= width of type [-Wshift-count-overflow]
   return ((size_t)sizeHigh << 32) | (size_t)sizeLow;
                            ^~
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o movepick.o movepick.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o pawns.o pawns.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o position.o position.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o psqt.o psqt.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o search.o search.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o tbprobe.o tbprobe.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o thread.o thread.c
thread.c: In function 'thread_create':
thread.c:152:41: warning: passing argument 3 of 'CreateThread' from incompatible pointer type [-Wincompatible-pointer-types]
   HANDLE thread = CreateThread(NULL, 0, thread_init, (void *)(intptr_t)idx,
                                         ^~~~~~~~~~~
In file included from c:/Program Files (x86)/mingw-w64/i686-7.3.0-posix-dwarf-rt_v5-rev0/mingw32/i686-w64-mingw32/include/winbase.h:29:0,
                 from c:/Program Files (x86)/mingw-w64/i686-7.3.0-posix-dwarf-rt_v5-rev0/mingw32/i686-w64-mingw32/include/windows.h:70,
                 from types.h:53,
                 from endgame.h:24,
                 from material.h:24,
                 from thread.c:23:
c:/Program Files (x86)/mingw-w64/i686-7.3.0-posix-dwarf-rt_v5-rev0/mingw32/i686-w64-mingw32/include/processthreadsapi.h:163:28: note: expected 'LPTHREAD_START_ROUTINE' but argument is of type 'DWORD (*)(void *) {aka long unsigned int (*)(void *)}'
   WINBASEAPI HANDLE WINAPI CreateThread (LPSECURITY_ATTRIBUTES lpThreadAttributes, SIZE_T dwStackSize, LPTHREAD_START_ROUTINE lpStartAddress, LPVOID lpParameter, DWORD dwCreationFlags, LPDWORD lpThreadId);
                            ^~~~~~~~~~~~
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o timeman.o timeman.c


----------------------------------------------------------
**MinGW 8.1.0:**

gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o movepick.o movepick.c
misc.c: In function 'file_size':
misc.c:201:28: warning: left shift count >= width of type [-Wshift-count-overflow]
   return ((size_t)sizeHigh << 32) | (size_t)sizeLow;
                            ^~
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o pawns.o pawns.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o position.o position.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o psqt.o psqt.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o search.o search.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o tbprobe.o tbprobe.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o thread.o thread.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o timeman.o timeman.c
thread.c: In function 'thread_create':
thread.c:152:41: warning: passing argument 3 of 'CreateThread' from incompatible pointer type [-Wincompatible-pointer-types]
   HANDLE thread = CreateThread(NULL, 0, thread_init, (void *)(intptr_t)idx,
                                         ^~~~~~~~~~~
In file included from c:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/i686-w64-mingw32/include/winbase.h:29,
                 from c:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/i686-w64-mingw32/include/windows.h:70,
                 from types.h:53,
                 from endgame.h:24,
                 from material.h:24,
                 from thread.c:23:
c:/Program Files (x86)/mingw-w64/i686-8.1.0-posix-dwarf-rt_v6-rev0/mingw32/i686-w64-mingw32/include/processthreadsapi.h:163:127: note: expected 'LPTHREAD_START_ROUTINE' but argument is of type 'DWORD (*)(void *)' {aka 'long unsigned int (*)(void *)'}
   WINBASEAPI HANDLE WINAPI CreateThread (LPSECURITY_ATTRIBUTES lpThreadAttributes, SIZE_T dwStackSize, LPTHREAD_START_ROUTINE lpStartAddress, LPVOID lpParameter, DWORD dwCreationFlags, LPDWORD lpThreadId);
                                                                                                        ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o tt.o tt.c
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -Wno-pedantic-ms-format -m32 -DNDEBUG -O3 -msse -flto   -c -o uci.o uci.c

**Comment by CoffeeOne** [comment]
No warnings here, MSYS 2 gcc 7.3

**Comment by syzygy1** [comment]
I have fixed the first warning but am not entirely sure about the second warning in thread.c.

**Comment by ChessMan3** [comment]
No warnings for me (MinGW 7.3.0 & 8.1.0).

**Comment by guru64** [comment]
No warnings. Thanks, Syzygy!
