### ISSUE TITLE
Fix function 'uci_loop'

### ISSUE THREAD

**Issue by Alexei1981** [syzygy1/Cfish#69]
Hello Mr De Man.When I compile on GCC-8 Cfish for Android ,climbs the following warnings.Fix.

```
uci.c: In function ‘uci_loop’:
uci.c:318:7: warning: implicit declaration of function ‘flockfile’; did you mean ‘close_file’? [-Wimplicit-function-declaration]
       flockfile(stdout);
       ^~~~~~~~~
       close_file
uci.c:325:7: warning: implicit declaration of function ‘funlockfile’; did you mean ‘unmap_file’? [-Wimplicit-function-declaratio]
       funlockfile(stdout);
       ^~~~~~~~~~~
       unmap_file
```

**Comment by Alexei1981** [comment]
In stdio.h flockfile occurs once:

stdio.h gcc-8
/* Acquire ownership of STREAM.  */
extern void flockfile (FILE *__stream) __THROW;

stdio.h gcc-7.2
#if __POSIX_VISIBLE >= 199506
void	 flockfile(FILE *);
int	 ftrylockfile(FILE *);
void	 funlockfile(FILE *);

**Comment by syzygy1** [comment]
I thought the -D_POSIX_C_SOURCE =199506 flag added in the Makefile would set the __POSIX_VISIBLE variable.

**Comment by Alexei1981** [comment]
Thanks!

**Comment by syzygy1** [comment]
Do you mean you solved the problem by adding -D_POSIX_C_SOURCE=199506 to the gcc command? The Makefile was supposed to do that by itself. Did that not work or were you using a custom Makefile?

**Comment by Alexei1981** [comment]
No,I'm using your makefile,but for arm 64 bit, I had to modify it.
