### ISSUE TITLE
BMI1 support

### ISSUE THREAD

**Issue by ChessMan3** [syzygy1/Cfish#71]
Hello!
Can you please add BMI1 support?
On Ryzens, BMI2 builds (with PEXT)  works extremely slow. 
I was try to add it for my self:  https://github.com/ChessMan3/Cfish/tree/BMI1
I'm not sure i make it correctly...
At least, BMI1 gives a small speed-up on my Ryzen 7 1700X:

![screenshot_678](https://user-images.githubusercontent.com/25572058/44110093-8077547c-a007-11e8-9f2b-9d6892e2b9f3.png)

**Comment by CoffeeOne** [comment]
What do you expect from that change?
Basically you set CFLAGS += -mbmi -DUSE_BMI1
Well -mbmi will have an effect, but only if you compile without native by explicitely stating `native=no`, -march=native will activate ALL available options for your CPU.
And USE_BMI1 is used nowhere, so .... ?

**Comment by ChessMan3** [comment]
@CoffeeOne  
1. I expect speed-up (confirmed on screenshot and my tests)
2. I don't use native optimization. I use make profile-build ARCH=x86-64-bmi1 lto=yes extra=yes native=no numa=yes -j 14 comp=mingw
3. DUSE_BMI1 used here https://github.com/ChessMan3/Cfish/commit/073f1ba91e5edbeaede124c2da67f02a917735f7#diff-0a1f40fc150a973726797865e772a344R81 (for **include <immintrin.h>**)
and here https://github.com/ChessMan3/Cfish/commit/073f1ba91e5edbeaede124c2da67f02a917735f7#diff-0a1f40fc150a973726797865e772a344R108
and here https://github.com/ChessMan3/Cfish/commit/073f1ba91e5edbeaede124c2da67f02a917735f7#diff-4a37aac5c8f7e438572f91c0ed94cfcbR74 (for output internal name Cfish 64 BMI1 instead of  Cfish 64 POPCNT )

![screenshot_679](https://user-images.githubusercontent.com/25572058/44157243-afe23980-a0ba-11e8-9d13-55653451e042.png)

===========
Score of Cfish_x64_0607_ELTO_BMI1_810mingw vs Cfish_x64_0607_ELTO_popcnt_810mingw: 3430 - 3323 - 9223 [0.503]
Elo difference: 2.33 +/- 3.50

15990 of 20000 games finished. 10+0.1

*ELTO ===   extra=yes + lto=yes

I can make new tests, more games and/or another conditions.
Even if @syzygy1  don't added this to Cfish, I'm hoping for Cfish optimization advice for Ryzen processors.

**Comment by CoffeeOne** [comment]
about your point 3) OK, you use DUSE_BMI1 only for an include. That construct is for Intel and MS compiler but NOT for gcc. I understand that you use gcc, so for your compilation nothing changed. So the only functional change is setting `-mbmi`

**Comment by ChessMan3** [comment]
You're right. But for some reason without point 3, the speed is less ...

=========
Good point about -march=native  --- i have 1.5% speed-up.
On my Phenom II and FX-8150, builds with -march=native had not positive effect --- they was slightly slower...

**Comment by RomeoA23** [comment]
AMD Ryzen 7 1700X, Win 10 x64
CuteChess 1.0, RR, 1 thread, concurrency 14
TC 15s+0.15s, 16 MB, book: test1.pgn, LP=off

PLAYER                                       :  RATING  ERROR  PLAYED   (%)     W     D     L  D(%)  CFS(%)
   1 CFish_040918_x64_N_pop_ELTO_BMI1_810mingw    :    3203      2   12055  50.8  **2219  7811  2025**  64.8     100
   2 CFish_040918_x64_N_pop_ELTO_810mingw         :    3197      2   12055  49.2  **2025  7811  2219**  64.8     ---

White advantage = 37.42 +/- 2.14
Draw rate (equal opponents) = 65.90 % +/- 0.40


==============
And asmFish bmi1 vs popcnt:

PLAYER                          :  RATING  ERROR  PLAYED   (%)     W     D     L  D(%)  CFS(%)
   1 asmFishWCP_2018-09-05_bmi1      :    3208      2   12228  52.2  2318  8126  1784  66.5     100
   2 asmFishWCP_2018-09-05_popcnt    :    3192      2   12228  47.8  1784  8126  2318  66.5     ---

White advantage = 26.07 +/- 2.11
Draw rate (equal opponents) = 67.20 % +/- 0.42

*asmFish uses `tzcnt`
