### ISSUE TITLE
Book .bin support is partially broken 

### ISSUE THREAD

**Issue by gogamoga1** [syzygy1/Cfish#72]
Since the last two commits you can get the [following](https://i.imgur.com/oOlfhvE.jpg) as the book reply

How to reproduce:

1. Play a game as usual, everything will work as intended
2. Press 'New game' button in GUI (tested both in Fritz and Arena)  
3. You'll most likely get an absolutely false book reply

**Comment by CoffeeOne** [comment]
I agree with @gogamoga1 .
reverting commit `Updated to "Introduce voting system for best move selection".` solves the problem.

**Comment by syzygy1** [comment]
Has the problem been fixed?

**Comment by gogamoga1** [comment]
Yes, thank you.
