### ISSUE TITLE
Fix Numa mode for processors which have nodes without direct memory access

### ISSUE THREAD

**Issue by drdwo** [syzygy1/Cfish#75]
numa_all_nodes_ptr points to a bitmask that is allocated by the library with bits representing all nodes on which the calling task may allocate memory. Under linux (kernel 4.18.4) the AMD 2990 WX processor has 4 Numa nodes, but only nodes 0+2 are marked. This means, if we define 64 threads, they are allocated only to the 2 nodes with direct memory access, only 16 cores are used, node count per second is drastically reduced. Numa mode is now almost twice as fast under windows compared to linux. Only a single processor is affected - Epycs have more memory channels and don't suffer from this issue. But unfortunately it is the currently fastest single "consumer" processor measured by "cfish bench". I can help testing a fix on my 2990 WX.

**Comment by syzygy1** [comment]
Does it help to set NUMA to "all"?
setoption name NUMA value all

I've checked in a possible fix, but it probably won't change the behaviour after setting NUMA to "all".

**Comment by syzygy1** [comment]
I'm closing this issue for lack of feedback.
