### ISSUE TITLE
Multithread benchmark comparison on big machine

### ISSUE THREAD

**Issue by CoffeeOne** [syzygy1/Cfish#8]
Hello,
This is not an "issue", only information, you can immediately close it after reading.
I compared with date of today 2016-Oct-10 Stockfish-Master, PedantFish, Asmfish and CFish.
Machine: 4way Opteron 6386SE. OS: Windows 2012 R2 Server.
Fish and Stockfish compiled with GCC6.2 under mingw64.
3 runs of "bench 1024 64 24", then averaged. before benchmarks were started for AsmFish/PedantFish, LargePages were turned on with the UCI-command.
Result:
1) Stockfish-Master: 26.63MN/s
2) AsmFish: 52.06MN/s
3) PedantFish: 52.47MN/s
4) CFish: 59.49MN/s
The result speaks for itsself.
Good job!

**Comment by syzygy1** [comment]
Thanks!

How does single-threaded Cfish compare to asmFish/pedantFish?
How did you compile Cfish? Just make profile-build or did you enable LTO?

Compiling with LTO somehow results in a slow down on my machine (on Linux). I have not tried LTO on Windows yet.

**Comment by CoffeeOne** [comment]
I made some very quick single thread test: 5 Times bench 16 1 15 and averaged:
SINGLE BENCHES:
CFish: 1.07 MN/s
PedantFish: 1.39 MN/s
AsmFish: 1.45 MN/s
Stockfish Master:  1.14 MN/s
These results are very weird. Stockfish Master faster than CFish? Please note, that stockfish master has 42 positions in bench, Cfish only 37, maybe it makes a difference.

Then I compiled CFish also with LTO + PGO (the existing values were only PGO = profile build)
SINGLE: bench 16 1 15 (5 runs): 1.10 MN/s
bench 1024 64 24 (3 runs): 60.71 MN/s

**Comment by syzygy1** [comment]
Very interesting indeed.
The extra 5 positions in SF bench are mate positions and do not even change the bench number. So they make no difference.
Cfish does not have the lastest (1-line) patch from SF master, but that patch seems to lower nps if anything. (I think Cfish and pedantfish have the same updates now and thus identical bench.)

I don't know why single-threaded Cfish is slower than SF master on your system.
I also don't know how Cfish can make up for such a speed difference with asmfish/pedantfish when going to 64 cores.

**Comment by tthsqe12** [comment]
I have tried the separate compact table for the moves in movegen and found that it is 0.5% faster for asmFish.
If cfish is using smaller tables for the movegen, this might affect 1->64 cores.
I can really only optimize asmFish for my system, where I found that smaller lookup tables where a loss on 1 to 4 threads.

**Comment by CoffeeOne** [comment]
Let me add some more benchmarks:
First I investigated a little bit about Stockfish Master under Windows (I know it's off-topic here):
I compared the version BEFORE comitting "Use per thread CMH" with Use per thread CMH: 
Before (bench 1024 64 24):  avg: 32,11 MN/s
After committing user per thread CMH: avg. 26,14 MN/s. This is a contradiction to M. Costalba's commit message: "...As expected the speed-up more than compensates the filling
rate ....." Hmm there is no speedup at all at least NOT on this machine under WINDOWS!

OK, but now back to the topic:
Values for LINUX on the same machine: Ubuntu 16.04 gcc 5.4:
I did both 5 runs for single thread, also 5 runs for multi-thread 64 threads. Single thread values have low variation, but unfortantely NOT the 64 thread tests .... 
Stockfish-Master: Single (bench 16 1 15) 1,51 MN/s Multi (bench 1024 64 24) 61,01MN/s
Cfish: Single: 1,53 MN/s Multi: 63,22 MN/s
AsmFish: Single 1,55 MN/s Multi: 59,71 MN/s
PedantFish: Single: 1,57 MN/s Multi: 60,77 MN/s

**Comment by CoffeeOne** [comment]
One is missing: CFISH with LTO (Ronald has turned it off, but it seemed faster for me under Windows). Also note, that Stockfish Master was done with PGO LTO (LTO is turned on in Stockfish-Master for COMP=gcc!)

CFish LTO (and PGO): Single 1.59 MN/s Multi: 64,80MN/s

So under Linux CFish is fastest for both single and multi thread performance on this machine!!! Nevertheless stockfish master does very well, too.
So I desperately need CFish only for Windows ;-)

**Comment by syzygy1** [comment]
So Cfish (and SF) take a big hit when going from Linux to Windows, but the gap becomes smaller (relatively speaking) when increasing the number of cores.

I have some ideas about why gcc produces slower code on Windows (difference in x86-64 calling conventions), but it is not clear to me why the situation improves with more cores. Probably other things (like CPU cache being shared among cores) become more limiting.

Windows on your system seems to get confused when trying to run SF on 64 cores.

**Comment by tthsqe12** [comment]
How does pfish compare with cfish on your intel linux box?

**Comment by CoffeeOne** [comment]
Feel free to request more benchmarks, I am closing this issue now
