### ISSUE TITLE
**Not an issue**

### ISSUE THREAD

**Issue by glennsamuel32** [syzygy1/Cfish#80]
Is there a way to change the FiftyMoveDistance in the source ?
I'm trying to have Cfish solve blocked and fortress type positions faster.

Thanks.

**Comment by syzygy1** [comment]
Change 99 to 39 for a 20-move rule:
https://github.com/syzygy1/Cfish/blob/6d89c63ba12a8f96df8d626366880a1903e7d027/src/position.c#L1323
(But if you increase the value, Cfish will likely crash.)

**Comment by glennsamuel32** [comment]
I'd like to make it a 10 move rule ?

**Comment by MichaelB7** [comment]
For 10 use 19.

**Comment by glennsamuel32** [comment]
Thank you Ronald and Michael !!
