### ISSUE TITLE
**Just question**

### ISSUE THREAD

**Issue by AlexB123** [syzygy1/Cfish#82]
Hello, mr Ronald!
Many thanks for your great work! I would like to ask you, is the Cfish dead? Will new versions of Cfish appear in the near future?
I'm asking because,Stockfish 10 was released,and latest versions of it are even stronger (~8-10 elo),but Cfish stay at the same place and now it is behind by far, this is sad.

**Comment by ChessMan3** [comment]
@syzygy1 
Hello Ronald!
I added some patches to Cfish (up to: **"simplify opposite_colors
protonspring authored and snicolet committed 9 days ago"  bench 3773021**)

https://github.com/ChessMan3/Cfish/commits/m7

and now i am trying to add patch "Tweak CMH pruning" but i got a wrong bench
https://github.com/ChessMan3/Cfish/commit/8d955700ca908469f0f01f25b924be7c9cde7001

If you are not busy, please look at this.
