### ISSUE TITLE
error message:  "Unable to allocate large page.."

### ISSUE THREAD

**Issue by abdulbadii** [syzygy1/Cfish#83]
I got error message in the first line on execution load:

"Unable to allocate large pages for the transposition table"
how to solve this?

**Comment by d3vv** [comment]
Using Windows 10 with LP activated, start Cfish several times we have strange thing seems like "global memory leak": no cfish or any interface into system processes but we have no free memory anymore. When it occur - cfish return this message into terminal (Unable to allocate large pages for the transposition table).

**Comment by sohel1214** [comment]
when use 2 gb hash then ok with LP but more then 2 gb then show (Unable to allocate large pages for the transposition table). how we solved it ?

**Comment by syzygy1** [comment]
Not a problem specific to Cfish, as far as I understand.
