### ISSUE TITLE
is cfish completely up to date?

### ISSUE THREAD

**Issue by Denzwell** [syzygy1/Cfish#89]
In Cfish -- ucioption.c
{ "Analysis Contempt", OPT_TYPE_COMBO, 0, 0, 0, "Off var Off var White var Black", NULL, 0, NULL }

In Stockfish -- ucioption.cpp
o["Analysis Contempt"]     << Option("**Both** var Off var White var Black var Both", "**Both**");

Best Regards

**Comment by MichaelB7** [comment]
Cfish has the default selection correct for the savy and serious minded analysis users.  The evaluation is more stable as you move through a game tree.  Under the SF method, the evaluation tends to jump around as you constantly switch sides - some people may prefer that, but my guess is that most serious users prefer the Cfish default selection here as it does not pollute the hash tables with inconsistent evaluations from both the white and black perspective.   It is certainly Ronald's preference as he commented on this previously and his opinion counts the most here ;>)

**Comment by Denzwell** [comment]
Hi,
thank you for your explanation. But I noticed for weeks that cfish was out of date. Can the author please confirm

**Comment by maxchess** [comment]
Trying to compile on macOS .. what to do here please ?

_SOURCE=199506L -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -mbmi2 -march=native -flto   -c -o misc.o misc.c
misc.c:242:3: warning: implicit declaration of function 'madvise' is invalid in
      C99 [-Wimplicit-function-declaration]
  madvise(data, *map, MADV_RANDOM);
  ^
misc.c:242:23: error: use of undeclared identifier 'MADV_RANDOM'
  madvise(data, *map, MADV_RANDOM);
                      ^
1 warning and 1 error generated.
make[2]: *** [misc.o] Error 1
make[1]: *** [gcc-profile-make] Error 2
make: *** [profile-build] Error 2

**Comment by maxchess** [comment]
Oops apologies - maybe wrong place to ask.

**Comment by MichaelB7** [comment]
@maxchess - that's ok - it's a makefile issue - change line 183 (removing "Darwin") to this: 
```
ifneq ($(KERNEL),$(filter $(KERNEL),Linux Haiku))
```
and of course -, numa should be set to "no" on macOS ( line 79)

@syzygy1  the change above will fix this error for macOS
```
_SOURCE=199506L -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -mbmi2 -march=native -flto -c -o misc.o misc.c
misc.c:242:3: warning: implicit declaration of function 'madvise' is invalid in
C99 [-Wimplicit-function-declaration]
madvise(data, *map, MADV_RANDOM);
^
misc.c:242:23: error: use of undeclared identifier 'MADV_RANDOM'
madvise(data, *map, MADV_RANDOM);
^
1 warning and 1 error generated.
make[2]: *** [misc.o] Error 1
make[1]: *** [gcc-profile-make] Error 2
make: *** [profile-build] Error 2
```

**Comment by maxchess** [comment]
Thanks Mike - did exactly as you requested - got this (again) .. ??

gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -Wno-pedantic-ms-format -D_POSIX_C_SOURCE=199506L -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -mbmi2 -march=native   -c -o material.o material.c
warning: unknown warning option '-Wno-pedantic-ms-format'; did you mean
      '-Wno-pedantic'? [-Wunknown-warning-option]
1 warning generated.
gcc -Wall -std=c11 -fprofile-generate -pedantic -Wextra -Wshadow -m64 -Wno-pedantic-ms-format -D_POSIX_C_SOURCE=199506L -arch x86_64 -mmacosx-version-min=10.9 -DNDEBUG -O3 -mdynamic-no-pic -DIS_64BIT -msse -msse3 -mpopcnt -DUSE_POPCNT -DUSE_PEXT -mbmi2 -march=native   -c -o misc.o misc.c
warning: unknown warning option '-Wno-pedantic-ms-format'; did you mean
      '-Wno-pedantic'? [-Wunknown-warning-option]
misc.c:242:3: warning: implicit declaration of function 'madvise' is invalid in
      C99 [-Wimplicit-function-declaration]
  madvise(data, *map, MADV_RANDOM);
  ^
misc.c:242:23: error: use of undeclared identifier 'MADV_RANDOM'
  madvise(data, *map, MADV_RANDOM);
                      ^
2 warnings and 1 error generated.
make[2]: *** [misc.o] Error 1
make[1]: *** [gcc-profile-make] Error 2
make: *** [profile-build] Error 2

**Comment by MichaelB7** [comment]
Hi Max, Something is not correct - you should not be seeing this flag at all:
```
-D_POSIX_C_SOURCE=199506L
```
The attached makefile works with both gcc and clang on my Mac Pro - if it doses not work on your Mac , something else is in play.

[Makefile.zip](https://github.com/syzygy1/Cfish/files/2907868/Makefile.zip)

**Comment by syzygy1** [comment]
@Denzwell 
As @MichaelB7 explained, this is on purpose.

**Comment by maxchess** [comment]
@MichaelB7 
Something is definitely amiss - I have other errors. Anyway my decrepit Windoze machine works fine
so I'll analyze with that for now. I have another ICCF tournament just started so need to concentrate on that for now. Mnay many thanks for your help - much appreciated.

**Comment by MichaelB7** [comment]
@maxchess when you have a chance, no rush ,  let me know which version of gcc you are using - “gcc -version” and did you install by the using Macports ?

**Comment by maxchess** [comment]
Cannot say whether I used MacPorts - dont know unfortunately .. :(
Anyway ..

Last login: Tue Feb 26 18:57:03 on ttys000
You have new mail.
➜  ~ gcc -version
clang: error: unknown argument: '-version'
clang: error: no input files
➜  ~ gcc
clang: error: no input files
➜  ~ bash
bash-3.2$ gcc -version
clang: error: unknown argument: '-version'
clang: error: no input files
bash-3.2$ 


Paradox : another poster on TalkChess used to upload macOS compilations (executables) for me and I dont recall having issues with his gcc or clang versions. 

Mike .. its not worth the trouble please as I have the Win machine which is slow but okay for my analysis needs.

**Comment by MichaelB7** [comment]
@maxchess - new makefile
[Makefile.zip](https://github.com/syzygy1/Cfish/files/2908321/Makefile.zip)
try the attached makefile   "make  profile-build ARCH=x86-64-modern COMP=gcc" , if that doesn't work, try this with the quotes, this will tell you where the error is occurring and provide a few more clues as to what is going on...
```
 make profile-build ARCH=x86-64-modern  COMPCC="gcc -v"
```
and post  the last 30 lines up to and including the error message lines.

**Comment by MichaelB7** [comment]
@maxchess gcc version
[cfish.zip](https://github.com/syzygy1/Cfish/files/2908329/cfish.zip)

Also here's a clang version - note the zip files have the same name , but they contain different binaries
[cfish.zip](https://github.com/syzygy1/Cfish/files/2908423/cfish.zip)
try clang first, gcc prob will not work

**Comment by maxchess** [comment]
@MichaelB7 
My machine is crazy .. !!
Take a guess .. both run just fine and I know the only version that used to work on my machine was your clang executable.

Thanks for the makefile and both the executables.

Its 4:30am and I'm not fully awake plus I have more than a few ICCF games to respond to so later today I'll try the Makefile and whatever else you requested.

+3 many thanks !!

**Comment by maxchess** [comment]
@MichaelB7 

No point in running the Makefile now ??
What do you think - both your versions are working just fine and I'd rather not tempt fate and have something else unscrewing itself in my machine .. :)

**Comment by hero2017** [comment]
> @MichaelB7
> Something is definitely amiss - I have other errors. Anyway my decrepit Windoze machine works fine
> so I'll analyze with that for now. I have another ICCF tournament just started so need to concentrate on that for now. Mnay many thanks for your help - much appreciated.

What is your rating there?
