### ISSUE TITLE
cfish not support hash (large pages) more the 2 gb ?

### ISSUE THREAD

**Issue by sohel1214** [syzygy1/Cfish#91]
not support more then 2 gb ?

**Comment by syzygy1** [comment]
Try a 64-bit compile.

**Comment by sohel1214** [comment]
windows 64 bit and use also 64-bit pls check why not support hash(LP)

**Comment by JavaMast** [comment]
@sohel1214 
For me LP works fine with big hash

**Disabled LP in OS:**
![Screenshot_147](https://user-images.githubusercontent.com/42765009/54702670-5eb29080-4b48-11e9-9cc0-b2e3ca96edcf.png)

**Enabled LP in OS:**
8192
![Screenshot_149](https://user-images.githubusercontent.com/42765009/54702699-725df700-4b48-11e9-812e-5de5fa489c5e.png)

1024
![Screenshot_151](https://user-images.githubusercontent.com/42765009/54702759-8e619880-4b48-11e9-9dac-b2becae46019.png)
