### ISSUE TITLE
""not issue""

### ISSUE THREAD

**Issue by AlexB123** [syzygy1/Cfish#94]
Hello mr.Ronald!
Can you kindly update the Cfish? 
Thank you, and my best regards!

**Comment by d3vv** [comment]
What a reason for this prey? :D

**Comment by AlexB123** [comment]
> 
> 
> What a reason for this prey? :D
I like this engine, i use it for a long time! There is a lot of people that use this engine as well!

**Comment by AlexB123** [comment]
I like this engine, i use it for a long time! There is a lot of people that use this engine as well!

**Comment by sohel1214** [comment]
i req already release cfish 10

**Comment by AlexB123** [comment]
Hello mr.Ronald! It's been more than a month, i'm just curious :). Will you update the engine or the same fate (as AsmFish) awaits it?

**Comment by AlexB123** [comment]
Hello mr.Ronald! 
4 months it's a long time.. :( I hope you are well, and soon we will see updated Cfish!! A lot of people, including me, miss the engine. On my AMD processor Cfish is stronger than other engines, on Android platform it's simply the King :1st_place_medal: (miles away from any engine, i've did a lot of tests on both platforms). :+1: :+1: :+1: :1st_place_medal:
Many thanks and regards!

**Comment by JavaMast** [comment]
Please update.

**Comment by mymoso** [comment]
Hello Mr. Ronald

I have to disturb your spiritual retreat by asking Cfish to have its code updated again.
Unfortunately there are no substitutes for your work.
What happens is that when we have updated versions and your code is close to Stockfish Dev we have the best engine.
I know your time should be scarce, family, work, personal life and other factors.
But it's your fault for accustoming us to such competence.
Please come back. Make Cfish again be big and current.

Greetings from Brazil.

**Comment by wiseguy100** [comment]
Amen :)
