### ISSUE TITLE
8.1.0 MinGW issue on Windows 64 bit

### ISSUE THREAD

**Issue by AlexB123** [syzygy1/Cfish#99]
Hi Ronald! 
After your last update ->

### 3.6 popcnt
ifeq ($(popcnt),yes)
	ifeq ($(arch),ppc64)
		CFLAGS += -DUSE_POPCNT
	else ifeq ($(comp),icc)
		CFLAGS += -msse3 -DUSE_POPCNT
	else
		CFLAGS += -msse3 -mpopcnt -DUSE_POPCNT
	endif
endif

I'm getting the follow errors ->
Makefile:330: Extraneous text after `else' directive
Makefile:332: *** only one `else' per conditional.  Stop.
Makefile:330: Extraneous text after `else' directive
Makefile:332: *** only one `else' per conditional.  Stop.
strip: 'CFish.exe': No such file
The system cannot find the file specified.
Makefile:330: Extraneous text after `else' directive
Makefile:332: *** only one `else' per conditional.  Stop.
Makefile:330: Extraneous text after `else' directive
Makefile:332: *** only one `else' per conditional.  Stop.
strip: 'CFish.exe': No such file
The system cannot find the file specified.
Makefile:330: Extraneous text after `else' directive
Makefile:332: *** only one `else' per conditional.  Stop.
Makefile:330: Extraneous text after `else' directive
Makefile:332: *** only one `else' per conditional.  Stop.
strip: 'CFish.exe': No such file
The system cannot find the file specified.
Makefile:330: Extraneous text after `else' directive
Makefile:332: *** only one `else' per conditional.  Stop.
Makefile:330: Extraneous text after `else' directive
Makefile:332: *** only one `else' per conditional.  Stop.
strip: 'CFish.exe': No such file
The system cannot find the file specified.
Makefile:330: Extraneous text after `else' directive
Makefile:332: *** only one `else' per conditional.  Stop.
Press any key to continue . . .
**The only way to avoid this problem, is to return to the old lines ->**
### 3.6 popcnt
ifeq ($(popcnt),yes)
	ifeq ($(comp),icc)
		CFLAGS += -msse3 -DUSE_POPCNT
	else
		CFLAGS += -msse3 -mpopcnt -DUSE_POPCNT
	endif
endif
**Can you fix this please? **

**Comment by JavaMast** [comment]
I have not this issue on MinGW 8.1.0 and MinGW 9.1.0

**Comment by AlexB123** [comment]
Hello! Looks like this issue came from the Stockfish. I've tried to compile Stockfish and Brainfish, same problem. What cause this issue?

1. Makefile:320: Extraneous text after `else' directive
Makefile:322: *** only one `else' per conditional.  Stop.
Makefile:320: Extraneous text after `else' directive
Makefile:322: *** only one `else' per conditional.  Stop.
strip: 'stockfish.exe': No such file
The system cannot find the file specified.
Makefile:320: Extraneous text after `else' directive
Makefile:322: *** only one `else' per conditional.  Stop.
Press any key to continue . . .

**Comment by AlexB123** [comment]
Hi! Problem solved, I just needed to upgrade MSYS from 1.0 to 1.0.11. Now everything working fine!
